### ISSUE TITLE
daily data - trying to get components - get Invalid format string

### ISSUE THREAD

**Issue by monkeydust** [facebookincubator/prophet#102]
Any idea what might be happening here? Thanks

*************
m.plot(forecast)
Out[6]:

In [7]:

m.plot_components(forecast)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-34f56bf61ffc> in <module>()
----> 1 m.plot_components(forecast)

C:\Anaconda3\lib\site-packages\fbprophet-0.1.post1-py3.6.egg\fbprophet\forecaster.py in plot_components(self, fcst, uncertainty)
    672             artists += plot(fcst, ax=ax, uncertainty=uncertainty)
    673 
--> 674         fig.tight_layout()
    675         return artists
    676 

C:\Anaconda3\lib\site-packages\matplotlib\figure.py in tight_layout(self, renderer, pad, h_pad, w_pad, rect)
   1750                                          renderer,
   1751                                          pad=pad, h_pad=h_pad, w_pad=w_pad,
-> 1752                                          rect=rect)
   1753 
   1754         self.subplots_adjust(**kwargs)

C:\Anaconda3\lib\site-packages\matplotlib\tight_layout.py in get_tight_layout_figure(fig, axes_list, subplotspec_list, renderer, pad, h_pad, w_pad, rect)
    347                                      subplot_list=subplot_list,
    348                                      ax_bbox_list=ax_bbox_list,
--> 349                                      pad=pad, h_pad=h_pad, w_pad=w_pad)
    350 
    351     if rect is not None:

C:\Anaconda3\lib\site-packages\matplotlib\tight_layout.py in auto_adjust_subplotpars(fig, renderer, nrows_ncols, num1num2_list, subplot_list, ax_bbox_list, pad, h_pad, w_pad, rect)
    124                                                ax_bbox_list,
    125                                                num1num2_list):
--> 126         tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
    127         tight_bbox = TransformedBbox(tight_bbox_raw,
    128                                      fig.transFigure.inverted())

C:\Anaconda3\lib\site-packages\matplotlib\tight_layout.py in <listcomp>(.0)
    124                                                ax_bbox_list,
    125                                                num1num2_list):
--> 126         tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
    127         tight_bbox = TransformedBbox(tight_bbox_raw,
    128                                      fig.transFigure.inverted())

C:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py in get_tightbbox(self, renderer, call_axes_locator)
   3807             bb.append(self._right_title.get_window_extent(renderer))
   3808 
-> 3809         bb_xaxis = self.xaxis.get_tightbbox(renderer)
   3810         if bb_xaxis:
   3811             bb.append(bb_xaxis)

C:\Anaconda3\lib\site-packages\matplotlib\axis.py in get_tightbbox(self, renderer)
   1091             return
   1092 
-> 1093         ticks_to_draw = self._update_ticks(renderer)
   1094         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1095                                                                 renderer)

C:\Anaconda3\lib\site-packages\matplotlib\axis.py in _update_ticks(self, renderer)
    967 
    968         interval = self.get_view_interval()
--> 969         tick_tups = [t for t in self.iter_ticks()]
    970         if self._smart_bounds:
    971             # handle inverted limits

C:\Anaconda3\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    967 
    968         interval = self.get_view_interval()
--> 969         tick_tups = [t for t in self.iter_ticks()]
    970         if self._smart_bounds:
    971             # handle inverted limits

C:\Anaconda3\lib\site-packages\matplotlib\axis.py in iter_ticks(self)
    914         self.major.formatter.set_locs(majorLocs)
    915         majorLabels = [self.major.formatter(val, i)
--> 916                        for i, val in enumerate(majorLocs)]
    917 
    918         minorLocs = self.minor.locator()

C:\Anaconda3\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    914         self.major.formatter.set_locs(majorLocs)
    915         majorLabels = [self.major.formatter(val, i)
--> 916                        for i, val in enumerate(majorLocs)]
    917 
    918         minorLocs = self.minor.locator()

C:\Anaconda3\lib\site-packages\matplotlib\dates.py in __call__(self, x, pos)
    465                              'plotting dates, e.g., with ax.xaxis_date()')
    466         dt = num2date(x, self.tz)
--> 467         return self.strftime(dt, self.fmt)
    468 
    469     def set_tzinfo(self, tz):

C:\Anaconda3\lib\site-packages\matplotlib\dates.py in strftime(self, dt, fmt)
    569             # Note: in python 3.3 this is okay for years >= 1000,
    570             # refer to http://bugs.python.org/issue177742
--> 571             return cbook.unicode_safe(dt.strftime(fmt))
    572 
    573         return self.strftime_pre_1900(dt, fmt)

ValueError: Invalid format string

**Comment by monkeydust** [comment]
data structure is this

***
	ds	t	trend	seasonal_lower	seasonal_upper	trend_lower	trend_upper	yhat_lower	yhat_upper	weekly	weekly_lower	weekly_upper	yearly	yearly_lower	yearly_upper	seasonal	yhat
8167	2018-11-27	1.030976	65.629183	0.729351	0.729351	61.570035	69.749895	48.059918	83.560493	-0.303455	-0.303455	-0.303455	1.032806	1.032806	1.032806	0.729351	66.358534
8168	2018-11-28	1.031062	65.643669	1.368327	1.368327	61.517438	69.812986	49.768927	83.298027	0.375069	0.375069	0.375069	0.993257	0.993257	0.993257	1.368327	67.011995
8169	2018-11-29	1.031148	65.658154	0.975222	0.975222	61.501371	69.857505	48.744893	85.209738	0.031841	0.031841	0.031841	0.943381	0.943381	0.943381	0.975222	66.633376
8170	2018-11-30	1.031234	65.672640	0.674963	0.674963	61.501570	69.895725	48.564015	85.288078	-0.208763	-0.208763	-0.208763	0.883726	0.883726	0.883726	0.674963	66.347603
8171	2018-12-01	1.031320	65.687125	0.841008	0.841008	61.476602	69.929784	48.937040	84.624043	0.025990	0.025990	0.025990	0.815017	0.815017	0.815017	0.841008	66.528133

**Comment by bletham** [comment]
I wonder if this is the same as #99. If you disable yearly seasonality does it work?

**Comment by bletham** [comment]
Should be fixed in #99.
