### ISSUE TITLE
may be a math problem

### ISSUE THREAD

**Issue by stevenjk2012** [facebookincubator/prophet#104]
# Seasonality features
        if self.yearly_seasonality:
            seasonal_features.append(self.make_seasonality_features(
                df['ds'],
                365.25,
                10,#?
                'yearly',
            ))

        if self.weekly_seasonality:
            seasonal_features.append(self.make_seasonality_features(
                df['ds'],
                7,
                3,#?
                'weekly',
            ))

I don't understand the 3rd parameter,why yearly is 10, why weekly is 3 ? Fourier series?

**Comment by datafool** [comment]
Yes, this depends on Fourier Series. 10 means you are taking 10 terms of  Fourier series i.e. total of 21 values including the value of constant term i.e. a0 of a0 + a1sin(2*pi*t/T) + a2cos(2*pi*t/T) + .. 

More number of terms might lead to over-fitting and less will lead to under-fitting. So, prophet team would have found that for yearly 10 terms work and for weekly 3 terms work best. However, you can make it as hyper-parameter and can check the results for multiple terms.

Hope this helps!
