### ISSUE TITLE
How to change default forecasting Technique

### ISSUE THREAD

**Issue by jmarrietar** [facebookincubator/prophet#107]
Hi, 
Reading this blog https://research.fb.com/prophet-forecasting-at-scale/ It says this

>  The forecast package includes many different forecasting techniques (ARIMA, exponential smoothing, etc),

However reading documentation for Quick Start https://facebookincubator.github.io/prophet/docs/quick_start.html

It is not clear How to change forecasting technique into prophet objetc. 
```
# Python
m = Prophet()
m.fit(df);
```

**Any Example or documentation How to change it?.** 

Thanks.

**Comment by bletham** [comment]
That part of the blog post is talking about the R package `forecast` (https://cran.r-project.org/web/packages/forecast/index.html), which contains a collection of various methods. I'm not aware of a Python package that has a similar collection of methods. Prophet implements one specific approach.

**Comment by jmarrietar** [comment]
Thanks, I will close this now. 
I would like also to know if there is more in depth documentation in another Urls.

**Comment by bletham** [comment]
The documentation here provides an overview: https://facebookincubator.github.io/prophet/docs/quick_start.html

And the documentation for the R package gives a detailed description of each method: https://cran.r-project.org/web/packages/prophet/prophet.pdf

That's about the extent of the documentation at the moment.
