### ISSUE TITLE
Lookahead bias?

### ISSUE THREAD

**Issue by eonsmile** [facebookincubator/prophet#108]
Does prediction in prophet have any lookahead bias?  That is, does a prediction from a particular day use any future information that it cannot possibly have seen on that day?

**Comment by bletham** [comment]
I'm not exactly sure what you mean but I think the answer is "sometimes. "

The model is essentially a regression on the history. This means that if your history contains dates Jan 1 to Jan 31, then the (in-sample) model prediction for Jan 15 will use the entire history, and thus will use the future-to-it observations of Jan 16-Jan31.

If we are making a prediction for Feb 1, then we will use only the history (Jan 1 to Jan 31) and so there is no lookahead bias. This is true for any date past the history.

Is that what you were asking about?

**Comment by eonsmile** [comment]
Yes exactly.  Therefore, let's say if I want to test the out of sample performance of a trading strategy using prophet prediction, I will not be able to do that by calling prophet only once, but I will need to call prophet once each day in history and pass to each call a rolling window of history up to that point in time only.  Am I missing anything?  Is there a smart way of just calling prophet only once and achieving the same goal?

By the way, if I set up a loop to call prophet multiple times, there's a high chance of a crash as reported by other users in separate threads.

**Comment by seanjtaylor** [comment]
Unfortunately there's no way around writing the loop. It's a common exercise to run forecasts at many simulated forecast dates (see our paper on this).  The people reporting crashes are forecasting thousands of times, you likely only need a few hundred forecasts to do this.
