### ISSUE TITLE
What freq to use for weekday data?

### ISSUE THREAD

**Issue by rockoder** [facebookincubator/prophet#110]
I have daily data except for the weekends. How do I set the frequency for the same?

**Comment by bletham** [comment]
In the Python version, `freq` is passed to Pandas `date_range` which has a long list of possible frequencies: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases . It looks like `'B'` is what you want.

For the R version, `freq` is passed to `seq.Date` which supports only "day", "week", "month", "quarter" or "year". In this case (and more generally), you can always create the dataframe of future dates manually. 

The output of `make_future_dataframe` in both Python and R is just a dataframe with a column `ds` containing the dates for which predictions will be made. You can manually construct a dataframe with only weekday dates and then use that as the input to `predict` (e.g. http://stackoverflow.com/questions/15139768/fill-a-vector-with-weekdays-only)
