### ISSUE TITLE
period of seasonality

### ISSUE THREAD

**Issue by datafool** [facebookincubator/prophet#111]
As per my understanding period of seasonality will depend on data aggregation. For example, if data is aggregated at weekly level and there is yearly seasonality. So, period in this case would be 52 or 53, and not 365.5, as week 1 of Jan 2014 will be similar to week 1 of Jan 2015, and as data is weekly aggregated there are 52 or 53 points between the two similar period.

This could be cause of concern as using period of 52 and period of 365.5 gives different seasonality curve. See attached images 
Period 365.5

![period 365 5](https://cloud.githubusercontent.com/assets/5044483/23909218/2eb3c902-08fc-11e7-859c-0964cb55edb3.png)

Period 52

![period 52](https://cloud.githubusercontent.com/assets/5044483/23909267/416efa80-08fc-11e7-8916-a824c9ed2c21.png)

Even if seasonality with 365.5 seems to be smoother, but the one created with 52 seems better. 

Please let me know, if my understanding is correct!

**Comment by seanjtaylor** [comment]
Adding this an enhancement.  We can think about getting this into 0.2 or the 0.3 release.

**Comment by datafool** [comment]
Adding this as an enhancement will be awesome. As we have an agreement on this, we can close this issue!

**Comment by extrospective** [comment]
non-daily-data docs link does not work at this time, an updated link would appear to be: https://facebook.github.io/prophet/docs/non-daily_data.html
