### ISSUE TITLE
Questions about using prophet

### ISSUE THREAD

**Issue by virusdefender** [facebookincubator/prophet#112]
![image](https://cloud.githubusercontent.com/assets/4939404/23938427/3e985e5a-0997-11e7-9c49-48b8e082e847.png)

I'm using prophet to predict website page view，but why there is a fast degradation after `2017-02-25`？

My code

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet

import sqlite3
conn = sqlite3.connect("mt.db")
c = conn.cursor()

c.execute("select * from log where time_stamp >= '2017-02-18'")
logs = c.fetchall()

print("query done")

columns = ["id", "time_stamp", "ip", "url", "url_path"]
df = pd.DataFrame(logs, columns=columns)
df.index = pd.DatetimeIndex(df.time_stamp)

data = df.resample("5Min").count()
data = data.rename(columns={"id": "y"})
# data["y"] = np.sqrt(data["y"])
data["ds"] = data.index

m = Prophet()
m.fit(data)

future = m.make_future_dataframe(periods=24 * 5 * 5, freq="5min")

forecast = m.predict(future)

m.plot(forecast)
# m.plot_components(forecast)
plt.show()
```

I'm using Python 3.5 and latest version of prophet in pypi.

If you need my raw data, please tell me, I'll try to upload a copy.

**Comment by datafool** [comment]
If I am not wrong you are using data from Sunday to Friday and forecasting for Saturday and Sunday.  There could be two reason for this behaviour, as per my understanding -
1. weekly seasonality might be affecting the prediction. You can try giving `weekly_seasonality=False` when instantiating Prophet, or if you want weekly seasonality, reduce the prior value i.e. `seasonality_prior_scale=10.0` from 10 to probably somewhere between 1 to 5, and asses the effect

2. model might be getting biased by change points, so you could also try by reducing    `changepoint_prior_scale=0.05` from 0.05 to 0.01 or something similar

You can apply each changes in different run to understand how these are affecting your model and finally you can apply all of them together to see combined effect. 

I hope this solves your problem. Do let me know if my suggestions solves your problem.

**Comment by virusdefender** [comment]
@datafool Thank you. 

yes, I should set `weekly_seasonality=False`
