### ISSUE TITLE
Failed to Install fbprophet in Ubuntu 14 with Error :- 'x86_64-linux-gnu-gcc' failed with exit status 4 

### ISSUE THREAD

**Issue by arima-sambunath** [facebookincubator/prophet#113]
Already  insalled pystan 

but still Error at intallation 

root@Timeseries:/home/CapacityPrediction# pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (from fbprophet)
Requirement already satisfied: pystan in /usr/local/lib/python2.7/dist-packages (from fbprophet)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/dist-packages (from pandas->fbprophet)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from pandas->fbprophet)
Requirement already satisfied: numpy>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from pandas->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in /usr/local/lib/python2.7/dist-packages (from pystan->fbprophet)
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/dist-packages (from python-dateutil->pandas->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SwBLKm/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbVHUXTpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/fbprophet
  creating build/lib.linux-x86_64-2.7/fbprophet/stan_models
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SwBLKm/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xqgB9j-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fbprophet
    creating build/lib.linux-x86_64-2.7/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SwBLKm/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xqgB9j-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-SwBLKm/fbprophet/

**Comment by arima-sambunath** [comment]
pip install fbprophet fail in Ubuntu 14 with Error : ---------   'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by bletham** [comment]
Here are what seem to be the most common issues in a Linux install (#88), hopefully one of them does it:

(1) If this is a VM, then Stan requires at least 2Gb of memory, make sure you aren't running out.
(2) Compilers installed and up-to-date:
```
sudo apt-get install gcc-5 g++-5 python-dev
```
(3) If you are using Anaconda, then try `conda install gcc`

Does one of those do it?

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/0e76b79dde5ae8243a6ba4da1fa5ffe0bc748912 lists these packages in the installation documentation, hopefully this will help with this in the future.
