### ISSUE TITLE
some error when installing fbprophet on centos 7

### ISSUE THREAD

**Issue by zhangjianleaves** [facebookincubator/prophet#115]
Python version： Python 2.7.5 
OS version:  CentOS Linux release 7.2.1511 (Core) 

**PyStan has already installed.**

Error message when running 'pip install fbprophet'
[root@localhost build]# pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
[root@localhost build]#

**Comment by bletham** [comment]
Could you make sure pip is up to date?
```
python -m pip install --upgrade --force pip 
```
There's some more discussion of what seems to be the same issue here:
http://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given

**Comment by zhangjianleaves** [comment]
thanks, it can solve this problem by upgrade setuptools 

> pip install setuptools==33.1.1

but i got another error:
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
Requirement already satisfied: pandas in /usr/lib64/python2.7/site-packages (from fbprophet)
Requirement already satisfied: pystan in /usr/lib64/python2.7/site-packages (from fbprophet)
Requirement already satisfied: numpy>=1.7.0 in /usr/lib64/python2.7/site-packages (from pandas->fbprophet)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from pandas->fbprophet)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in /usr/lib64/python2.7/site-packages (from pystan->fbprophet)
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BSNrHt/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YibC0H-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BSNrHt/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YibC0H-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-BSNrHt/fbprophet/


Do you have any idea of how to solve it?
My gcc version is gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
 

BTW, i saw many people asking help to install it, do we have docker image have environment set up already?  it will save us a lot of time

**Comment by bbfoto** [comment]
for me - cent7, very similar error output 

- I needed to install gcc-c++

**Comment by zhangjianleaves** [comment]
@bbfoto  I installed gcc-c++, still got same error.  Can your fbprophet run now on centos 7?
my gcc-c++version:  gcc-c++.x86_64 0:4.8.5-11.el7

**Comment by bbfoto** [comment]
Yes fbprophet working like a champ after this for me.  What I had done was found some other thread somewhere that indicated this was a problem in pystan. Some threads on pystan suggested a simple test function against pystan directly. It failed, but it was suggested to add 'verbose=True' to the arguments and once I did that, it spit out that gcc-c++ was not found... I would suggest googleing pystan and the error message. Sorry can't find the exact thread on my phone right now.

**Comment by zhangjianleaves** [comment]
thanks a lot @bbfoto   i will try it again~~
