### ISSUE TITLE
Can prophet deal with hourly data?

### ISSUE THREAD

**Issue by wangyifan1004** [facebookincubator/prophet#118]
I have hourly electric load data from 2011 to 2013 and I want to predict the next 3 days hourly data. What should I do using prophet?

![image](https://cloud.githubusercontent.com/assets/26034442/24033583/a005fa98-0b28-11e7-8d52-c75fd32f9871.png)

**Comment by wujushan** [comment]
In python, when you call the function 'make_future_dataframe',you can set the parameter 'freq' to 'H' and 'periods' to 72.Like the following: 
future = m.make_future_dataframe(freq='H',periods=72)
forecasts = m.predict(future)

**Comment by wangyifan1004** [comment]
@wujushan 
thks! I can use your method to predict hourly data,but the result seems to be really weird.
This is the power of Jan 1st to Jan 3th in 2013
![image](https://cloud.githubusercontent.com/assets/26034442/24052241/becb96da-0b6f-11e7-8f2c-4574b4df62da.png)
but my result of prediction is something like this:
![image](https://cloud.githubusercontent.com/assets/26034442/24052270/d9129d7c-0b6f-11e7-81bc-3cbc64a560de.png)
Is it possible this prophet can not fit the hourly data? because Daily data in area of load forecasting has a strong cyclical.

**Comment by jeslago** [comment]
Please refer to #29. Support for hourly data will be included in next releases.

**Comment by wangyifan1004** [comment]
@jeslago   Thank you！ Looking forward to it!

**Comment by ofir887** [comment]
@wangyifan1004 
Hi !
How did you plot the hourly graph you attached on top ?
![a005fa98-0b28-11e7-8d52-c75fd32f9871](https://cloud.githubusercontent.com/assets/22930172/26210652/fd6e5f94-3bf8-11e7-8ca0-993fb5a1dd39.png)
