### ISSUE TITLE
Make it easy to configure which day should be first in weekly seasonality plot

### ISSUE THREAD

**Issue by jonsjoberg** [facebookincubator/prophet#119]
It would be great if it was easy to chose what weekday was displayed first in the weekly seasonality plot, should be possible to do with a small modification to plot_weekly (for R):

```
plot_weekly <- function(df, uncertainty = TRUE, days = NULL) {
  if (is.null(days)){
    # Get weekday names in current locale
    days <- weekdays(seq.Date(as.Date('2017-01-01'), by='d', length.out=7))
  }
df.s <- df %>%
    dplyr::mutate(dow = factor(weekdays(ds), levels = days)) %>%
...
```
And add a days parameter `prophet_plot_components(... days = NULL)` which is just passed directly through to plot_weekly

**Comment by seanjtaylor** [comment]
This is a great point that I think someone made in #45  (particularly about this and internationalization).  Let's add this as an enhancement.

**Comment by bletham** [comment]
This is added in https://github.com/facebookincubator/prophet/commit/cacfdc635ec44cb514a69ed7a9ffb4163c326b66. There is an argument `weekly_start` which is an int representing which day to start the plot on relative to Sunday. So to start on monday.
```
prophet_plot_components(m, fcst, weekly_start = 1)
```

If you install from Github then you can try it out:
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```
