### ISSUE TITLE
Can I use prophet on data set with only a few months?

### ISSUE THREAD

**Issue by tomkee** [facebookincubator/prophet#120]
In prophet readme on github there's information:
> It works best with daily periodicity data with at least one year of historical data. 

The data I am using unfortunately has range of a few months. 
Is prophet useless in such a case?

**Comment by seanjtaylor** [comment]
You can but you'll need to turn off yearly seasonality.

**Comment by tomkee** [comment]
Thank you!
Can you tell me - how can I turn it off?

**Comment by SaswatMahapatra** [comment]
Hi ,
I have 1 year data from Jan 1 to dec 31, when im applying prophet with yearly seasonality =True , it should show a spike in next predicted Jan month, where as the model prediction goes on decreasing. can you let me know why is it happening like this.

**Comment by vhpietil** [comment]
It would be easier to comment if you could include the component plot 🙂

**Comment by SaswatMahapatra** [comment]
![components plot](https://user-images.githubusercontent.com/44432711/51672574-d0aba500-1ff1-11e9-8b17-2ec6339f88cc.png)
 @vhpietil  and the forecasting is decreasing as the future time frame increases, can you help me out on that too ??
see this 
![decreasing trend](https://user-images.githubusercontent.com/44432711/51672634-fa64cc00-1ff1-11e9-883e-dbc56df39fcd.png)

**Comment by SaswatMahapatra** [comment]
the value somehow comes to -640 in December end , I want the foecasts to be on the increasing trend. like Multiplicative , but it doesnt work ... can u help ??

https://github.com/facebook/prophet/issues/826

**Comment by vhpietil** [comment]
You can see in component plot that prophet estimates negative trend. That is why your forecast is going down. 
I dont think it is possible to turn trend estimation off. But you can estimate the downward trend in you forecast data frame and remove it from the forecast
