### ISSUE TITLE
Plot not appearing when using Python

### ISSUE THREAD

**Issue by robertdknight** [facebookincubator/prophet#121]
Using the Python code from the website, I can't get it to display the plot.  It shows the values, and the convergence message, just like R, but where R shows the plot, the Python one does not.  2.7.5, CentOS 7.

**Comment by robertdknight** [comment]
![python peyton](https://cloud.githubusercontent.com/assets/26532630/24087450/26338f70-0ced-11e7-9461-dadca6a9e7cd.png)
![r peyton](https://cloud.githubusercontent.com/assets/26532630/24087451/2755ac44-0ced-11e7-89a9-abc5a318c6bc.png)

This is with the quick start code from the .io website.

**Comment by robertdknight** [comment]
I'm also having trouble making the plot appear when running it via R in source mode rather than manually typing each line in the entry.

**Comment by pravj** [comment]
Have you tried adding `plt.show()`?

I assume that you are *not* running the code in the IPython notebook.

**Comment by robertdknight** [comment]
plot.show doesn't work, nor does plot.show().  I looked at the prophet.py,
and was happy to see MatPlotlib imported, so I attempted to save the
figure. I didn't see how the plot itself would be passed.  I have learned
what I know of Python via books and website self-teaching.    I was hoping
to get it to show using Python 2.7.5 because of the CENT OS support cycle.

The data path works, because I see the computations table. None of the PLOT
portions work, and I am still working on how to possibly modify the source
code to pass it.  I can try to check out that notebook, but the books I
purchased, and my code is python 2.7, and might require an additional
learning curve to move to 3.

# Python
import pandas as pd
import numpy as np
from fbprophet import Prophet
# Python
df = pd.read_csv('working_data/test2.csv')
df['y'] = np.log(df['y'])
df.head()
# Python
m = Prophet()
m.fit(df);
# Python
future = m.make_future_dataframe(periods=365)
future.tail()
# Python
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
# Python
# Python
# m.plot_components(forecast);
m.plot(forecast)
plot.show()
#plt.savefig('test.png')

**Comment by robertdknight** [comment]
Thank you!  I read the prophet.py and saw it returning Fig, and it escaped me to plot it in that fashion!  Thank you very much.

**Comment by pravj** [comment]
Welcome!

I think the issue can be closed now.
