### ISSUE TITLE
Redundant Plot

### ISSUE THREAD

**Issue by evanzhu2013** [facebookincubator/prophet#124]
### Redundant Plot

```
df.columns = ['ds','y']
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=12, freq='M')
fcst = m.predict(future)
fcst.loc[109:,'yhat']
m.plot(fcst)
```

<img width="897" alt="2017-03-22 10 17 07" src="https://cloud.githubusercontent.com/assets/7533756/24179308/4eeac458-0ee9-11e7-8553-fd8395534a5e.png">

**Comment by bletham** [comment]
This is a Jupyter notebook thing. Jupyter automatically plots anything generated by matplotlib, but then also displays the output of the last line in the block, which in this case is the plot again.

You can stop this by putting a semicolon after the plot command:
```
m.plot(fcst);
```

**Comment by evanzhu2013** [comment]
Thanks so much. I Got it.

2017年3月23日 +0800 19:46 Ben Letham <notifications@github.com>，写道：

**Comment by SehyunPark** [comment]
`model.plot_components(forecast);`
this solved.
