### ISSUE TITLE
R API: make_future_dataframe does not support Hourly frequency (freq='H')

### ISSUE THREAD

**Issue by singh-abhijeet** [facebookincubator/prophet#126]
While trying to to create a _future_dataframe_ with Hourly granularity, the following code fails in R:
`future <- make_future_dataframe(model, periods = 365, freq='H')`

Went through the doc `?make_future_dataframe`, and noticed that `freq` flag does not support `hour`:
> freq 'day', 'week', 'month', 'quarter', or 'year'.

I achieved success by switching to Python API though:
`future=model.make_future_dataframe(periods=24*10,freq='H')`

In ideal scenario, feature of a software/procedure should be similar irrespective of API. Why we don't have Hourly frequency (freq='H') support in R? We can cohesively work at addressing the limitations, if any.

**Comment by bletham** [comment]
Right now everything is really geared around daily data. Expanding to support hourly (or shorter) data is definitely on the roadmap (https://github.com/facebookincubator/prophet/issues/29) but not available yet. As you noticed, the data type in R is a daily datatype so the changes will have to start by replacing that by a timestamp. Python uses the Pandas datetime format which does include hourly, although currently seasonality is computed at a daily level, so we'll need some upgrades there too to handle hourly data.

**Comment by bletham** [comment]
I'm going to close this here and we can discuss this issue in the future on #29.
