### ISSUE TITLE
exported functions

### ISSUE THREAD

**Issue by mwhitaker** [facebookincubator/prophet#13]
Hi there,

Since the `get_changepoint...` functions are documented in the [help files](https://cran.r-project.org/web/packages/prophet/prophet.pdf) should those be exported or are they just used internally?

Many thanks,
Michael

**Comment by seanjtaylor** [comment]
Thanks for the feedback!  We don't current export any functions but I suspect we should export more.  I'll add this to the 0.2 release milestone.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/58fa0bcec57f60ee3a71a550976f63166681bf93 suppresses all of the functions that are meant for internal use from the reference manual pdf. This should make it much more useful once this is pushed to cran.
