### ISSUE TITLE
subset data for plotting (R)

### ISSUE THREAD

**Issue by RobertMyles** [facebookincubator/prophet#133]
Is it possible to introduce a method for subsetting the data to plotted with `plot()`? For example, if I have a large time series and I want to focus in on the time period just before the forecast and the forecast period itself. 
The current `plot()` method makes it a little difficult to approach this, since it uses the the prophet model object and the forecast period dataframe. It would be great to have a simple function to subset both objects for plotting.

**Comment by ellisvalentiner** [comment]
@RobertMyles if you inspect `plot.prophet` you can see that it is just a light-weight wrapper that joins the history from the prophet model object and the forecast, then uses ggplot to produce the plot. You could modify the code to produce a plot around a specific timeframe.

**Comment by RobertMyles** [comment]
Great, I'll have a look at that.

**Comment by pmaji** [comment]
@RobertMyles -- your question here paired with @ellisvalentiner's answer inspired me to write a fix for this. You can see it at work in the vignette that I wrote up here: https://github.com/pmaji/data-science-toolkit/blob/master/time-series/forecasting_with_prophet.ipynb

If you're just interested in how to get the plots to be subsettable, you can find that code here. Enjoy! https://github.com/pmaji/data-science-toolkit/blob/master/time-series/prophet_helper_functions.py
