### ISSUE TITLE
R Session Gets Aborted

### ISSUE THREAD

**Issue by vivekadithya** [facebookincubator/prophet#134]
I heard about Prophet and wanted to give it a try. So just took a small forecasting problem, to forecast the trends of a Wikipedia page. I got the data and while trying to build the model by executing the following statement:
model<-prophet(df)

[Click here](https://drive.google.com/open?id=0B8sA5trmXxInZGdqRzJVV0h3TU0) for the screenshot of error message.

The R session immediately crashes! Please find my complete code below.

```
#Wikipedia Trend Data
library(wikipediatrend)
data<-wp_trend(page = "Data_science", from = "2012-01-01", to = "2016-01-31")

library(ggplot2)
qplot(date,count,data = data)
summary(data)

#Missing data and Log transformation
data$count[data$count==0] <- NA
ds<-data$date
y<-log(data$count)
df<-data.frame(ds,y)

qplot(ds,y, data = df)

#Forecasting
library(prophet)
model<-prophet(df)
```

Thanks in advance!

**Comment by bletham** [comment]
From the error message I'm wondering if something isn't working with RStan. Can you verify that it is working by running this code?
```
library(rstan)
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)  # this will take a minute
mean(extract(fit)$y)  # should be close to 0
```

If it doesn't work, then I would make sure that the toolchain is working correctly RStan has really good guidance on that here: https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows

**Comment by bletham** [comment]
If there are any further issues here please reopen, but I'm going to close for now.
