### ISSUE TITLE
How to save image with plot_components?

### ISSUE THREAD

**Issue by arvindacumos** [facebookincubator/prophet#136]
I am wondering if I can use plot_components and later save the figures to an image.
I tried this

`plt = m.plot_components(forecast)

plt.savefig('output')`

however plot_components returns a list and not a matplotlib figure. Hence the error was thrown...

`Traceback (most recent call last):
  File "get_predictions.py", line 33, in <module>
    plt.savefig(output_file)
AttributeError: 'list' object has no attribute 'savefig'
`

Any ideas is very much appreciated.

**Comment by guiled** [comment]
This is what I use and it works...
`m.plot_components(forecast).savefig('2.png');`

**Comment by arvindacumos** [comment]
Thanks @guiled will try that one.

**Comment by arvindacumos** [comment]
Unfortunately that didn't work either

`Traceback (most recent call last):
  File "get_predictions.py", line 31, in <module>
    m.plot_components(forecast).savefig(detailed_file)
AttributeError: 'list' object has no attribute 'savefig'`

**Comment by arvindacumos** [comment]
Looking at the plot_components method it doesn't really return a figure but rather a list..

`    def plot_components(self, fcst, uncertainty=True):
        """Plot the Prophet forecast components.
        Will plot whichever are available of: trend, holidays, weekly
        seasonality, and yearly seasonality.
        Parameters
        ----------
        fcst: pd.DataFrame output of self.predict.
        uncertainty: Optional boolean to plot uncertainty intervals.
        Returns
        -------
        a matplotlib figure.
        """
        # Identify components to be plotted
        components = [('plot_trend', True),
                      ('plot_holidays', self.holidays is not None),
                      ('plot_weekly', 'weekly' in fcst),
                      ('plot_yearly', 'yearly' in fcst)]
        components = [(plot, cond) for plot, cond in components if cond]
        npanel = len(components)

        fig, axes = plt.subplots(npanel, 1, facecolor='w',
                                 figsize=(9, 3 * npanel))

        artists = []
        for ax, plot in zip(axes,
                            [getattr(self, plot) for plot, _ in components]):
            artists += plot(fcst, ax=ax, uncertainty=uncertainty)

        fig.tight_layout()
        return artists`

**Comment by stephanelebrun** [comment]
Hello,
I have the same problem:
`m.plot(forecast).savefig('Prophet_Forecast.png');` works all right
but `m.plot_components(forecast).savefig('Prophet_Components.png');` does not work with the same error as @arvindacumos: 
`AttributeError: 'list' object has no attribute 'savefig'`
Thanks in advance
Stéphane

**Comment by robertdknight** [comment]
Here's one example

projection = plt.figure(2)
components = plt.figure(1)

projection.savefig('filename.png', bbox_inches='tight')
components.savefig('Components.png', bbox_inches='tight')

**Comment by robertdknight** [comment]
Here's a working example.

forecast = plt.figure(2)
components = plt.figure(1)

forecast.savefig('filename.png')
components.savefig('Components.png')

**Comment by arvindacumos** [comment]
@robertdknight thanks can you provide more detailed code?

**Comment by robertdknight** [comment]
Use your existing code, and instead of calling the show and figure saving methods on the plot object that returned a list of figures, inherit each of those list items as its own object, and call the desired methods on them individually.

I think that's the correct explanation, I'm not school-taught.

**Comment by robertdknight** [comment]
Use your existing code or the code example on the website, and instead of calling the show and figure saving methods on the plot object that returned a list of figures (components and forecast), inherit each of those list items as its own object, and call the desired methods on them individually.

**Comment by robertdknight** [comment]
Use your existing code or the code example on the website, and instead of calling the show and figure saving methods on the plot object that returned a list of figures (components and forecast), inherit each of those list items as its own object, and call the desired methods on them individually.  This may not be memory efficient, best practices. Its how I would do it in C#

**Comment by robertdknight** [comment]
Use your existing code or the code example on the website, and instead of calling the show and figure saving methods on the plot object that returned a list of figures (components and forecast), inherit each of those list items as its own object, and call the desired methods on them individually. This may not be memory efficient, best practices. Its how I would do it in C#, and I'm not school or boot-camp taught.

**Comment by robertdknight** [comment]
That code I handed you was a beefy fishing Rod.  I'd hate to give you the mackerel too.

**Comment by robertdknight** [comment]
Not really.  I'm an autodidact who went to C# first.  My lines are terse and full of code smells.

**Comment by robertdknight** [comment]
Not really.  I sort of learned C# first.  my code is terse, and some of it smells.

**Comment by robertdknight** [comment]
''' plot returns a matplotlib figure, the top level drawing canvas containing subplots.  plot_components also calls the plot method and returns that figure as a zipped 'pair' with seasonal aspect. '''

m.plot_components(forecast)
m.plot(forecast)

''' use inheritance to take the properties of the returned items on some new items '''
forecast = plt.figure(2)
components = plt.figure(1)
forecast.savefig('forecast.png')
components.savefig('Components.png')
#  enjoy C sharp like easy to read tersy code-smell.

**Comment by robertdknight** [comment]
I'm new to GitHub, and learned about objects with C sharp. More detailed isn't my syntax forte, but I do remember something about PEP 8 wanting things done a certain way. My answer might be totally wrong for best practices.  

“”” plot returns a matplotlib figure, the top level drawing containing container. plot_components also calls the plot method and returns a zipped tuple with the seasonal aspect added as a new figure.  Each one gets a new 'figure number' in matplotlib.  You can find this by calling plt.show() a single time and seeing two plots appear, with a number in the Window name “””

“”” per website's official instructions “””
m.plot(forecast)  # adds a subplot to 'figure'
m.plot_components(forecast)  # adds a subplot to 'figure', which now returns a list of figures

“” Everything straight from the website instructions, until the following portion.  Use inheritance to take the properties of the returned object on some new objects and work with the easier to use terse syntax, treating each, matplotlib object you want, as its own new object “””

forecast = plt.figure(2) 
components = plt.figure(1)
forecast.savefig('forecast.png')  # could use forecast.show() instead of plt.show
components.savefig('Components.png') # could use components.show() instead of plt.show

**Comment by robertdknight** [comment]
working on it...  seeing if there's a github version of 1990's Debian IRC   RTFM.

**Comment by robertdknight** [comment]
I'm working on it...I'm hoping to find a github version of Linux's RTFM.

**Comment by robertdknight** [comment]
I'm working on it...I'm hoping to find a github version of Linux's RTFM that I put in the comments for you.

**Comment by robertdknight** [comment]
I'm working on it...I'm hoping to find a github version of Linux's RTFM that I can put in the comment.

**Comment by robertdknight** [comment]
More detail in that code would make my brain hurt.  Sorry.

**Comment by robertdknight** [comment]
More detail in that code would make my brain hurt.

**Comment by robertdknight** [comment]
Terse is beautiful, so, no.

**Comment by robertdknight** [comment]
not really. I thought that answer would close it.

**Comment by robertdknight** [comment]
Not sure what you mean.  Combine the instructions from the getting started with those four lines and you have a complete script.

**Comment by robertdknight** [comment]
I'm not sure whether that question is rhetorical.  In either case, No.

**Comment by robertdknight** [comment]
No, and the question hurt my feelings.

**Comment by robertdknight** [comment]
Is that a rhetorical question?

**Comment by robertdknight** [comment]
Hmm, well, here's a cocktail for you.

def ProphetChart180():
  ''' Create a chart using Prophet from Facebook Incubator '''
   # Import dataframe from CSV
  try: 
    plt.close('all')
    df = pd.read_csv('data.csv')
    df.head()    
    # Fit the model by instantiating a new Prophet object.
    m = Prophet()
    m.fit(df);
   
    # Predictions made on a dataframe with column ds containing dates for 
    # which the prediction is to be made
    # Then create a suitable dataframe for the future number of periods
    future = m.make_future_dataframe(periods=365)
    future.tail()
    forecast = m.predict(future)
   
    # The predict method assigns each row in future a predicted value which
    # it names yhat.  The forecast object is a new dataframe that includes
    # columns for components and uncertainty intervals
    # yhat_upper being the top of the interval, and yhat_lower being the lower
    
    forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
    m.plot_components(forecast)
    m.plot(forecast)
    plt.xlabel('', fontsize=16)
    plt.ylabel("($)", fontsize=16)
    plt.xlabel('', fontsize=16)
    projection = plt.figure(2)
    components = plt.figure(1)
    
    
    projection.savefig('Forecast.png')
    components.savefig('Components.png')
  except Exception, err:
    print 'ProphetChart180: '
    print sys.stderr.write('ERROR: %sn' % str(err))
    print
  pass

#  I'm not calling it for you too.

**Comment by robertdknight** [comment]
#  Here's a definition that you must call yourself

import sys
import os
import pandas as pd
import numpy as np
from fbprophet import Prophet
import matplotlib.pyplot as plt

def ProphetChart(self):
  ''' Create a chart using Prophet from Facebook Incubator '''
   # Import dataframe from CSV
  try: 
    plt.close('all')
    df = pd.read_csv('data.csv') 
    df.head()
    
    # Fit the model by instantiating a new Prophet object.
    m = Prophet()
    m.fit(df);
   
    # Predictions made on a dataframe with column ds containing dates for 
    # which the prediction is to be made
    # Then create a suitable dataframe for the future number of periods
    future = m.make_future_dataframe(periods=365)
    future.tail()
    forecast = m.predict(future)
   
    # The predict method assigns each row in future a predicted value which
    # it names yhat.  The forecast object is a new dataframe that includes
    # columns for components and uncertainty intervals
    # yhat_upper being the top of the interval, and yhat_lower being the lower
    
    forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
    m.plot_components(forecast)
    m.plot(forecast)
    plt.xlabel('X', fontsize=16)
    plt.ylabel('Y', fontsize=16)
    projection = plt.figure(2)
    components = plt.figure(1)
    
    
    projection.savefig('Forecast.png')
    components.savefig('Components.png')
  except Exception, err:
    print 'ProphetChart: '
    print sys.stderr.write('ERROR: %sn' % str(err))
    print
  pass

**Comment by robertdknight** [comment]
No.  That code was sufficient.

**Comment by robertdknight** [comment]
I can only hand you the code.  I can't drink it for you.

**Comment by robertdknight** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by robertdknight** [comment]
Noooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!

**Comment by robertdknight** [comment]
No.  I think that code solved the issue.

**Comment by robertdknight** [comment]
No.  That code solves the issue.  More detail would be frivolous, unless you want commentary on object oriented methods, in which case, the point is to use a subtype of the larger object you get from matplotlib when you call prophet.  Instantiate the subtype, and work with it, and type less.  Terse, yes.  Proper stylish, perhaps not.  Style the code yourself, or write your own if you don't like it.

**Comment by robertdknight** [comment]
No.   

P.S.  I am uncertain about your question.

**Comment by robertdknight** [comment]
No.

P.S. I am not certain that question makes sense.

**Comment by robertdknight** [comment]
No.

P.S. I am not certain that question makes sense,  and I feel a little irritated by it.

**Comment by robertdknight** [comment]
No.

P. S.  That question is irritating.

**Comment by robertdknight** [comment]
No, and I do not thank you for asking.

**Comment by robertdknight** [comment]
No.  You should close the thread unless you can explain why you're asking.

**Comment by robertdknight** [comment]
That was a great solution.  Your question there at the end really dismisses the quality of the contribution. Did you even try it?  I bet it solved Stephanie's problem.

**Comment by robertdknight** [comment]
Would need to see where it failed to help you.

**Comment by robertdknight** [comment]
No, but I did delete that one since it didn't suffice to aid you.

**Comment by robertdknight** [comment]
No. I removed it for you.

**Comment by robertdknight** [comment]
No. I removed it from your thread.

**Comment by robertdknight** [comment]
I'm not willing to write that much code for you.  You didn't up-vote a solution that you could just add to the example on the website and have a fully functioning script.

**Comment by robertdknight** [comment]
You didn't even up-vote that complete answer to question. I removed it, and won't write more code for you.

**Comment by robertdknight** [comment]
As that was a complete answer to your initial question, which you didn't even up-vote (by the way) - more detail would be superfluous.  I removed it and won't write more for you.  Best regards.

**Comment by akmalsabri** [comment]
how to save image into folder?
