### ISSUE TITLE
How to get forecasted data?

### ISSUE THREAD

**Issue by guiled** [facebookincubator/prophet#139]
Is there a way (preferably with python library) to export to csv the forecasted data in the same scale than the input data ?
I mean : I have a day with a number of 1484, and the forecasted data is around 7.8. I would like to have a data like 1734 instead of 7.9.

Thank you

**Comment by bletham** [comment]
I'm not exactly sure what you mean, the forecast should be on the same scale as the input data. Can you run the following
```
m = Prophet()
m.fit(df)
fcst = m.predict()
```
and then post the output of:
```
m.history.head()
```
and
```
fcst[['ds', 't', 'yhat']].head()
```
?
Then I should be able to see what is happening.

**Comment by bletham** [comment]
I'm guessing this was resolved, but if not please reopen.

**Comment by jon-aiq** [comment]
I am having the exact same problem: 

head(data)
          ds         y           dy
2 2016-07-31 0.9885522 -0.011447811
3 2016-08-01 0.9872054 -0.001346801
4 2016-08-02 0.9757576 -0.011447811
5 2016-08-03 0.9616162 -0.014141414
6 2016-08-04 0.9528620 -0.008754209
7 2016-08-05 0.9555556  0.002693603
> p <- prophet(prophet.input, interval.width = 0.99 ,yearly.seasonality=TRUE,weekly.seasonality=TRUE)
Initial log joint probability = -321202
Error evaluating model log probability: Non-finite gradient.

Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
> future <- make_future_dataframe(p, periods = 30);
> forecast <- predict(p, future)
> head(forecast[,c('ds','yhat')])
          ds        yhat
1 2016-07-31 -0.07128006
2 2016-08-01 -0.11460096
3 2016-08-02 -0.08993042
4 2016-08-03 -0.04705855
5 2016-08-04 -0.04115133
6 2016-08-05 -0.04712793
>

**Comment by jon-aiq** [comment]
It is unclear to me what transformation is being done to the data?
