### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by slavakurilyak** [facebookincubator/prophet#140]
When I run `$ pip install fbprophet` on Python 2.7.13, macOS 10.12.4, I get the following error:

```
Collecting fbprophet
  Using cached fbprophet-0.1.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v9/5n8070c96854w3mhd9knc73w0000gn/T/pip-build-zZTmYY/fbprophet/setup.py", line 96, in <module>
        """
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/dist.py", line 373, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/dist.py", line 441, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/skurilyak/Envs/prophet/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with Cython>=0.22 and NumPy are required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v9/5n8070c96854w3mhd9knc73w0000gn/T/pip-build-zZTmYY/fbprophet/
```

**Comment by slavakurilyak** [comment]
I fixed the issue by typing: 

```
$ pip install pystan
$ python setup.py install
```

**Comment by conradbm** [comment]
I got hit with the same issue, your first command was successful, however when running the second command I get the following: 

Blakes-MacBook-Pro:~ bmc$ sudo python setup.py install
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

![screen shot 2017-04-17 at 7 42 59 pm](https://cloud.githubusercontent.com/assets/19720478/25108738/150110e0-23a6-11e7-8b24-fcba5312ed21.png)

**Comment by carlosgino** [comment]
I have the same error Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/shapely
Storing debug log for failure in /root/.pip/pip.log

root@LAPTOP-98SB3UC8:~# pip install flask shapely
Downloading/unpacking flask
  Downloading Flask-0.12.1-py2.py3-none-any.whl (82kB): 82kB downloaded
Downloading/unpacking shapely
  Downloading Shapely-1.5.17.tar.gz (180kB): 180kB downloaded
  Running setup.py (path:/tmp/pip_build_root/shapely/setup.py) egg_info for package shapely
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`

Failed `CDLL(libgeos_c.so)`

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/shapely/setup.py", line 38, in <module>

    from shapely._buildcfg import geos_version_string, geos_version, \

  File "shapely/_buildcfg.py", line 167, in <module>

    fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])

  File "shapely/_buildcfg.py", line 161, in load_dll

    libname, fallbacks or []))

OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/shapely
Storing debug log for failure in /root/.pip/pip.log
root@LAPTOP-98SB3UC8:~#

**Comment by suresudheer** [comment]
I solved this by using this below command.

sudo apt-get install libmysqlclient-dev

**Comment by ongrid** [comment]
`apt install -y libmysqlclient-dev` helped on Ubuntu 16 LTS

**Comment by hwmarcos** [comment]
I use ubuntu and this worked for me.
pip install mysqlclient

**Comment by HUMPHREY94** [comment]
Thanks for the soln solved

**Comment by annizhao** [comment]
how about for mac?

**Comment by the94air** [comment]
This [stackoverflow](https://stackoverflow.com/questions/42152729/error-installing-mysqlclient-on-ubuntu-16-04-using-pip-and-python-3-6) question solved my issue

**Comment by uzair28** [comment]
i'm unable to resolve the following error while installing openstack
![img_9633](https://user-images.githubusercontent.com/34480064/33887390-72e8b3a8-df6b-11e7-97bd-7f54c09b3486.JPG)

**Comment by MaynulIslam** [comment]
how can i fix it

![ss](https://user-images.githubusercontent.com/25595362/35038225-59234c80-fba4-11e7-969d-ddcb70cf632c.png)

**Comment by devvvshah** [comment]
![capture](https://user-images.githubusercontent.com/34328483/35183631-7329c5b0-fe0f-11e7-91ad-252161031d7d.PNG)
I've tried almost everything to fix it , anyone can help ?
Thanks in advance.

**Comment by shubozhang** [comment]
I solved it by:
pip install --upgrade setuptools

**Comment by MaynulIslam** [comment]
Thanks for the cooperation

**Comment by reproteq** [comment]
sudo apt-get install  python-xlib

test this solution

**Comment by AnirudhKonduru** [comment]
After a lot of tinkering, a quick `sudo apt-cache search mysqlclient` hinted that I needed to install default-libmysqlclient-dev with:
`sudo apt-get install default-libmysqlclient-dev`

**Comment by Trisha1212** [comment]
https://14code.com/blog/20171026_1294 might help you folks

**Comment by packageman** [comment]
I solved this problem by running `pip install --upgrade pip`

**Comment by abuayub** [comment]
sudo apt-get install libmysqlclient-dev

**Comment by kikku2506** [comment]
Still stuck with this error even after trying everything mentioned on this post. Anyone found any solution?

**Comment by Delta777** [comment]
Try:  pip install --upgrade setuptools
Worked for me.

**Comment by Sangramsingkayte** [comment]
from cuda_functional import SRU
ModuleNotFoundError: No module named 'cuda_functional'

**Comment by cs-julio-ferraz** [comment]
I solved this problem by running : # sudo  yum install -y mysql-community-devel python2-devel.x86_64
I used Fedora 26.

**Comment by MahrezBH** [comment]
try to use as super user  : 
sudo -s
Then : 
sudo apt-get install python3.6-dev libmysqlclient-dev

**Comment by sumit27p** [comment]
I have tried all the methods mentioned inthis post but nothing has worked.


Sumit-macbook:~ admin$ sudo -s
bash-3.2# sudo apt-get install python3.6-dev libmysqlclient-dev
sudo: apt-get: command not found
bash-3.2#

**Comment by johncornelius091** [comment]
@sumit27p 
apt-get is for Ubuntu but not for mac, try other solution.

**Comment by palavaianoop** [comment]
I got the same error!
it asked me to install setuptools 
after installing setuptools, its successfully installed all the requirements.txt file
cat requirements.txt
daemons >= 1.3.0
influxdb >= 2.12.0
urllib3 >= 1.13.1
isi_sdk_8_0 >= 0.1.2, < 0.2.0
isi_sdk_7_2 >= 0.1.2, < 0.2.0
Equation >= 1.2.01
gevent >= 1.2.1

**Comment by rabiaasif** [comment]
brew install mysql-connector-c
brew install mysql
brew unlink mysql-connector-c
sudo pip install pymysql
sudo pip install mysqlclient


Try these in this order

**Comment by mayurkmane** [comment]
to run python setup.py install you will need to go the root directory where python files downloaded.

**Comment by gongadisrihari** [comment]
> I solved it by:
> pip install --upgrade setuptools

i have tried many things, but this worked for me

**Comment by persas701** [comment]
![imagen](https://user-images.githubusercontent.com/61815585/75947317-8c7e0b80-5e65-11ea-8fb3-8889282c61c5.png)

- I have the problem installing pygresql

**Comment by MahrezBH** [comment]
@persas701  
The PostgreSQL bin directory containing pg_config must be on your PATH. Try to verify that ^^

**Comment by mobinalhassan** [comment]
Easy solution step by step work for me and work for almost everyone!
1st You need to install apt-get package
`sudo apt-get install mysql-server`
`sudo apt-get install libmysqlclient-dev`
`sudo apt-get install libmariadbclient-dev`
2nd you need to install pip package
`pip install mysqlclient`
then you are ready to install any package which have problem of 
> python setup.py egg_info Check

`pip install your-package-name`

**Comment by zobisco** [comment]
> I solved it by:
> pip install --upgrade setuptools

Life saver

**Comment by poonamsharma40** [comment]
I am still facing the same problem after trying all the above mentions :


ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-19hXIq/ase/setup.py'"'"'; __file__='"'"'/tmp/pip-install-19hXIq/ase/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-HpI2bl
         cwd: /tmp/pip-install-19hXIq/ase/
    Complete output (1 lines):
    Python 3.5 or later is required!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Mar1noc** [comment]
I did absolutely everything and it got fixed. Here are the commands I entered last

- pip install psycopg2-binary
- conda install py-xgboost
- pip3 install --user --upgrade pip setuptools wheel
- pip install shapely
- pip3 install minepy
- pip install --upgrade pip
- pip install --upgrade setuptools
- pip install mysqlclient
- pip install pystan
- pip install matplotlib
