### ISSUE TITLE
The following forecast values are less than previous ones

### ISSUE THREAD

**Issue by beloteloff** [facebookincubator/prophet#146]
I have a data, which have accumulative nature: financial index. The indicator must constantly grow or similiar to previous value;It's meaning that values in time series can't fall.
In the prediction I have value for (x+1) element less than x or (x-1).
What you can recommend me for fixing this problem?
Thanks!

**Comment by bletham** [comment]
This is an interesting problem. I'd suggest fitting Prophet to the difference of your data (`numpy.diff` in Python, or `diff` in R), and then computing the cumulative sum of the forecast (`yhat` in the forecast dataframe) afterwards.

It is still possible that the forecast for the diff would be negative, which would mean the cumulative sum decreases. You could either rectify all of the forecasted values to be >=0 (set the negative values equal to 0), or you could do the forecasting in a log-scale which would ensure positivity. I would guess that rectifying would work well but it probably depends on the time series.

**Comment by beloteloff** [comment]
Yes, I did it, using numpy.diff. This is a open problem for predicting ever-increasing time series

**Comment by bletham** [comment]
Did it work well enough? I'm not sure that this is something we will build automatic support in for since I suspect the right way to do this will be pretty problem specific.

**Comment by bletham** [comment]
I'm going to close this out since I don't think we're going to tackle this specific problem anytime soon.
