### ISSUE TITLE
Prophet docs contributing.html points to the wrong Github link

### ISSUE THREAD

**Issue by jharia** [facebookincubator/prophet#15]
Clicking on the "Edit on GitHub" link on the bottom right of this page https://facebookincubator.github.io/prophet/docs/contributing.html goes to https://github.com/facebookincubator/prophet/tree/gh-pages/_docs/contributing.md, which is a 404. Perhaps you meant to link to https://github.com/facebookincubator/prophet/blob/master/docs/_docs/contributing.md instead?

**Comment by seanjtaylor** [comment]
Good catch!  Should be fixed now!  Thanks @jharia!
