### ISSUE TITLE
Log probability evaluates to log(0), i.e. negative infinity.

### ISSUE THREAD

**Issue by AjitDingankar** [facebookincubator/prophet#150]
While trying to run the "Quick start" example I get the following error: 
```
> m <- prophet(df)
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.

Error in sampler$call_sampler(c(args, dotlist)) :
```
I had to figure out how to get the data for the exampel in csv file by myself, 
so it's possible that my dataframe is not as expected, but it looks OK. 
```
> head (df)
            ds        y
20 2007-12-10  9.590761
19 2007-12-11  8.519590
22 2007-12-12  8.183677
21 2007-12-13  8.072467
16 2007-12-14  7.893572
15 2007-12-15  7.783641
```
It'll be good to make the example *reproducible* by including commands to get 
the example ready (or pointing to the csv file).

**Comment by bletham** [comment]
The csv used in the quickstart is available here:
https://github.com/facebookincubator/prophet/blob/master/examples/example_wp_peyton_manning.csv
https://github.com/facebookincubator/prophet/commit/961716ba554da1caa260355d0c9ee45158a12956 adds this link to the Quickstart.

As for the issue you're running into, could you upload your csv to this issue so I can replicate?

**Comment by bletham** [comment]
Hopefully the link to the CSV resolved this but feel free to reopen if you are still running into this issue.
