### ISSUE TITLE
Plot functionality doesn't work

### ISSUE THREAD

**Issue by estowers5** [facebookincubator/prophet#151]
From the get started documentation, I was able to get everything running as expected. It's great.

However, I can't get a graph to show and there is no error in the code when I build.

I have confirmed that matplotlib will work outside of fbprophet so I believe something is going on with forecaster.py. Just a hunch though.

Any thoughts on how I can resolve this? Running Windows 10, Anaconda 4.3.1 if that helps.

Thanks for taking a look!

**Comment by bletham** [comment]
The examples in the documentation are in a jupyter notebook which displays matplotlib plots automatically, but if you are running this outside a notebook you will probably have to tell matplotlib to show the figures. You can do that like this:
```
from matplotlib import pyplot as plt
plt.show()
```
Anytime you run `plt.show()` it will show the generated plots. Does that do it?

**Comment by estowers5** [comment]
@bletham Thank you big time for helping out with that explanation.

So this is an interesting fix... It does look like adding .show() in the forecaster file did the trick so I didn't have to modify my actual script. HOWEVER, the plot would appear and then immediately disappear. Figured out that I could save the image so that I can actually look at the graph. So I still have an issue technically but it's solved enough for me to be happy now. Thanks!
