### ISSUE TITLE
Lower bound for forecasts

### ISSUE THREAD

**Issue by jimanvlad** [facebookincubator/prophet#152]
Hi,

Is there any way to set a lower bound for forecasts? For example I have a negative trend for a customer lifetime value forecast, and if I forecast enough periods into the future this will actually go under 0, which is impossible.

I am basically looking for the opposite of "capacity" in the future dataframe. Ideas?

Vlad

**Comment by bletham** [comment]
Not built-in at the moment, but this is something that will come in the future (#81).

In the meantime, I'd try taking the log of your data, fitting prophet to the logged data, and then exponentiate the forecast (`yhat` in the forecast dataframe). That will force the forecast to always be positive and will essentially give exponential decay towards 0, which sounds like it may be a good model.

**Comment by jimanvlad** [comment]
Hi,

Sure, logging works for this scenario. However, it tends to flatten seasonal spikes when there is a downward trend, so the forecast is affected. 

Vlad

**Comment by bletham** [comment]
That's true, it converts the seasonality to be multiplicative instead of additive.

It'd be great to have lower saturation with additive seasonality, and also to get multiplicative seasonality without saturation. I expect this to involve creating new forms for the trend part of the model. Definitely on the todo list!

**Comment by bletham** [comment]
I'm going to close this out and consolidate the discussion into #152.

**Comment by jimanvlad** [comment]
This Ian #152...

**Comment by jimanvlad** [comment]
Is*

**Comment by bletham** [comment]
Whoops I meant #81
