### ISSUE TITLE
Values in yhat don't look like truthful

### ISSUE THREAD

**Issue by beloteloff** [facebookincubator/prophet#153]
Hi!
After I do np.exp for yhat* values and print in table
```
from math import exp
forecast = m.predict(future)
yy=forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

yy['yhat'] = np.exp(yy['yhat'])

yy['yhat_lower'] = np.exp(yy['yhat_lower'])

yy['yhat_upper'] = np.exp(yy['yhat_upper'])

yy
```
I saw historical values, which don't seems like in my initial data:
```
ds 	yhat 	yhat_lower 	yhat_upper
0 	2015-01-01 	374.115050 	323.454765 	430.314696
1 	2015-01-02 	404.581531 	352.531571 	463.097451
2 	2015-01-03 	454.509094 	393.739375 	520.577848
3 	2015-01-04 	417.631754 	360.478112 	477.366897
```

When my initial data:
```
2015-01-01,433
2015-01-02,471
2015-01-03,424
2015-01-04,404

```
I think,that it some mistake or model is very-very bad

**Comment by bletham** [comment]
I don't think I can really say what exactly is happening here. It is entirely possible that the model is a poor fit for these data, and that seems most likely. You might try setting the input parameter `mcmc_samples` to something like 500 to get better results (certainly better uncertainty) and try using plots to diagnose the source of the bad fit (maybe outliers? overfitting that can be adjusted with parameters?). If you post a plot of the forecast I might be able to give some comment on why the model is fitting poorly.

**Comment by stevenjk2012** [comment]
maybe I know what's your meaning, the 2015 data is real data,not the predict data . So ,the df.head should be equal to the initial data , maybe there is some problem with output function

**Comment by stevenjk2012** [comment]
def make_future_dataframe(self, periods, freq='D', include_history=True):

**Comment by bletham** [comment]
This seems to be a matter of a bad forecast on this dataset, I don't think there is a bug here so I'm going to close this for now.
