### ISSUE TITLE
Error in R

### ISSUE THREAD

**Issue by marishadorosh** [facebookincubator/prophet#16]
It looks like this:
"Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2f455284a4.dll" OBJECTS="file2f455284a4.o"' had status 127 "

**Comment by seanjtaylor** [comment]
Thanks for the report!  Can you let me know what version of Windows and R you're using.  And also verify that you've installed [RTools](http://cran.r-project.org/bin/windows/Rtools/)?

**Comment by marishadorosh** [comment]
I use R version 3.3.2 (2016-10-31) and windows 10 pro 32bit. I installed RTools and I created prophet model. 
Now I have another error -"Error in UseMethod("predict") : no applicable method for 'predict' applied to an object of class "character"". My code : 
`df0=data.frame(ds=(seq.Date(make_date(2017,01,01),make_date(2017,02,01),by = 1)),y = c(1:32))
pr0 =prophet(df0)
make_future_dataframe(pr0,periods = 10)
future0=make_future_dataframe(pr0,periods = 10)
forecast0 <- predict(pr0, future0)`

**Comment by seanjtaylor** [comment]
Hmm this does not replicate for me, can you give me the output of
```
> class(prr0)
> pr0
```

Just to see what class was returned?

**Comment by marishadorosh** [comment]
I think it is a model of prophet.
`class(pr0)` returned: "list"    "prophet"
And `pr0` returned list of list ($growth, $changepoints and etc.)

**Comment by bletham** [comment]
Does
`forecast0 <- prophet:::predict.prophet(pr0, future0)`
work?

**Comment by marishadorosh** [comment]
Yes, it works! thank you

**Comment by seanjtaylor** [comment]
@bletham is this an S3 object issue?

**Comment by bletham** [comment]
@seanjtaylor I'm not sure exactly sure what could have happened here.

@marishadorosh can you paste the output of
```
library(prophet)
methods(predict)
```
And could you try restarting R and see if the issue persists? (a lame suggestion I know).

**Comment by bletham** [comment]
Fix confirmed in #94, but post if you have further issues with this!
