### ISSUE TITLE
No space left on device error when running with pyspark

### ISSUE THREAD

**Issue by j-chou** [facebookincubator/prophet#162]
Hi, I've had a lot of fun using Prophet and recently I've been trying to use Prophet with pyspark to forecast hundreds of time series, but have been running into 

>File "/grid/2/tmp/yarn-local/usercache/tuser/appcache/application_1495315135132_1960981/container_e12_1490213517705735_1960981_01_000002/Python2.7.12/lib/python2.7/site-packages/pystan/model.py", line 360, in _setstate_
>f.write(self.module_bytes)
>IOError: [Errno 28] No space left on device

My script does the following: for each time series ts, I have a for loop that uses the first "i" days of data to build a model and then forecasts the next 21 days where i ranges from 20 to the length of the time series. Some of these time series could be 200-300 days long. 

    for i in range(20, len(ts)):
        ts_sub = ts.head(i)
        m.fit(ts_sub)
        m.make_future_dataframe(periods=21)
        forecast = m.predict(future).tail(k)[["ds", "yhat"]]
        del m
        output_df = output_df.append(forecast)
    
Here's my pyspark code: 

    if __name__ == "__main__":
        sc = SparkContext(appName="forecaster")
        mydata = sc.textFile('test_time_series.csv')
        mydata_ts = mydata.map(lambda x: x.split(',')).map(lambda y: ((y[1],y[2],y[3]), (y[0],y[4])))
        mydata_ts_g = mydata_ts.groupByKey().map(lambda x: (x[0], list(x[1])))
        mydata_ts_df = mydata_ts_g.map(lambda x: (x[0], pd.DataFrame(x[1], columns=['ds', 'y'])))
        mydata_ts_df = mydata_ts_df.map(lambda x: (x[0], x[1].sort_values(by='ds')))
        mydata_ts_df = mydata_ts_df.filter(lambda x: len(x[1]) >= 20)

        m = Prophet(n_changepoints=0)
        mydata_ts_df_predict = mydata_ts_df.flatMap(fb_forecast)
        mydata_ts_df_predict.saveAsTextFile('forecast_results')
    
It looks like a bunch of models are being stored on my local tmp directory, but not being cleaned up. Is there a way for me to immediately delete a stan model after I generate forecasts? For each model, I only need the single 20-day forecast. 

Thanks!

**Comment by seanjtaylor** [comment]
Hmm this is likely a pystan thing we didn't account for.   We should ask in the Pystan Github and see what temporary files it is creating.

**Comment by bletham** [comment]
I can replicate this issue. The temp files persist until the Python session is ended, despite https://github.com/stan-dev/pystan/blob/develop/pystan/model.py#L366-L367. Should be able to fix this on our end.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/5971a2369be1fc76af96c8ab6de1747c835acc95 should fix this issue by only loading the Stan model once, on package import. It fixes it for me, @j-chou do you mind installing from Github and checking if that does it?

**Comment by j-chou** [comment]
Latest changes worked on pyspark! Thanks!

**Comment by vavlopes** [comment]
@j-chou  do you have this project in a repository ? I'm doing the same proccess with another data, but i'm facing problems trying to parallelize the code. Seems for me that you could work with prophet and pyspark, and effectively parallelize the execution. Would you help me ?
