### ISSUE TITLE
Make it easy to configure which month should be first in monthly seasonality plot

### ISSUE THREAD

**Issue by saracv** [facebookincubator/prophet#163]
This would be great since there are instances where the 'year' doesn't start in January. For example, I work with schools were we are interested on seasonality starting in August or September and ending in June or July. 
Saw there was a similar request weekly seasonality that says it should be too hard, but I am just a beginner so not sure.
[https://github.com/facebookincubator/prophet/issues/119](url)

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/df4b6158ebe977044867664e005edb38cd7fe936 adds this feature via a parameter `yearly_start`, which specifies the number of days to shift the start of the plot from Jan 1.

For a Aug 1 plot that's approximately 210 days, so in R you can now do:
```
prophet_plot_components(m, fcst, yearly_start = 210)
```
and it should give what you want. Try it out by installing the latest version from Github:
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```

In Python the argument is the same,
```
m.plot_components(fcst, yearly_start=210)
```
and you can download from the repository and install from source to get this update.

**Comment by saracv** [comment]
Thanks! It works as expected. I also saw the ability to pick yearly and weekly seasonality. This package is great. I wish there was a way I could contribute.
