### ISSUE TITLE
Which algorithm is used to find the parameters?

### ISSUE THREAD

**Issue by beloteloff** [facebookincubator/prophet#164]
What kind of algorithm is used for finding optimized the parameters? [maximum likelihood estimation](https://en.wikipedia.org/wiki/Maximum_likelihood_estimation) or [Ordinary Least Squares](https://en.wikipedia.org/wiki/Least_squares) ?

**Comment by seanjtaylor** [comment]
Prophet uses Stan to do L-BFGS optimization.  We're performing [MAP](https://en.wikipedia.org/wiki/Maximum_a_posteriori_estimation) estimation.  Similar to maximum likelihood, but incorporates the prior distributions.
