### ISSUE TITLE
fatal error: stan/model/model_header.hpp: No such file or directory

### ISSUE THREAD

**Issue by Tomislav2309** [facebookincubator/prophet#165]
Hi,
Having next issue:
 m <- prophet(df) and getting next:
> df <- read.csv('K:/S21.csv') %>%
+ mutate(y = y)
> m <- prophet(df)
file39b8750e5772.cpp:8:39: fatal error: stan/model/model_header.hpp: No such file or directory
 #include <stan/model/model_header.hpp>
                                       ^
compilation terminated.
make: *** [file39b8750e5772.o] Error 1
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file39b8750e5772.dll" OBJECTS="file39b8750e5772.o"' had status 2 

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: 
  2: // includes from the plugin
  3: 
  4: 
  5: // user includes
  6: #define STAN__SERVICES__COMMAND_HPP// Code generated by Stan version 2.14
  7: 
  8: #include <stan/model/model_header.hpp>
  9: 
 10: namespace model39b8611424c9_prophet_linear_growth_namespace {
 11: 
 12: using std::istream;
 13: using std::string;
 14: using std::stringstream;
 15: using std::vector;
 16: using stan::io::dump;
 17: using stan::math::lgamma;
 18: using stan::model::prob_grad;
 19: using namespace stan::math;
 20: 
 21: typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
 22: typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
 23: typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;
 24: 
 25: static int current_statement_begin__;
 26: 
 27: class model39b8611424c9_prophet_linear_growth : public prob_grad {
 28: private:
 29:     int T;
 30:     int K;
 31:     vector_d t;
 32:     vector_d y;
 33:     int S;
 34:     matrix_d A;
 35:     vector<int> s_indx;
 36:     matrix_d X;
 37:     double sigma;
 38:     double tau;
 39: public:
 40:     model39b8611424c9_prophet_linear_growth(stan::io::var_context& context__,
 41:         std::ostream* pstream__ = 0)
 42:         : prob_grad(0) {
 43:         typedef boost::ecuyer1988 rng_t;
 44:         rng_t base_rng(0);  // 0 seed default
 45:         ctor_body(context__, base_rng, pstream__);
 46:     }
 47: 
 48:     template <class RNG>
 49:     model39b8611424c9_prophet_linear_growth(stan::io::var_context& context__,
 50:         RNG& base_rng__,
 51:         std::ostream* pstream__ = 0)
 52:         : prob_grad(0) {
 53:         ctor_body(context__, base_rng__, pstream__);
 54:     }
 55: 
 56:     template <class RNG>
 57:     void ctor_body(stan::io::var_context& context__,
 58:                    RNG& base_rng__,
 59:                    std::ostream* pstream__) {
 60:         current_statement_begin__ = -1;
 61: 
 62:         static const char* function__ = "model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth";
 63:         (void) function__; // dummy call to supress warning
 64:         size_t pos__;
 65:         (void) pos__; // dummy call to supress warning
 66:         std::vector<int> vals_i__;
 67:         std::vector<double> vals_r__;
 68:         double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
 69:         (void) DUMMY_VAR__;  // suppress unused var warning
 70: 
 71:         // initialize member variables
 72:         context__.validate_dims("data initialization", "T", "int", context__.to_vec());
 73:         T = int(0);
 74:         vals_i__ = context__.vals_i("T");
 75:         pos__ = 0;
 76:         T = vals_i__[pos__++];
 77:         context__.validate_dims("data initialization", "K", "int", context__.to_vec());
 78:         K = int(0);
 79:         vals_i__ = context__.vals_i("K");
 80:         pos__ = 0;
 81:         K = vals_i__[pos__++];
 82:         validate_non_negative_index("t", "T", T);
 83:         t = vector_d(static_cast<Eigen::VectorXd::Index>(T));
 84:         context__.validate_dims("data initialization", "t", "vector_d", context__.to_vec(T));
 85:         vals_r__ = context__.vals_r("t");
 86:         pos__ = 0;
 87:         size_t t_i_vec_lim__ = T;
 88:         for (size_t i_vec__ = 0; i_vec__ < t_i_vec_lim__; ++i_vec__) {
 89:             t[i_vec__] = vals_r__[pos__++];
 90:         }
 91:         validate_non_negative_index("y", "T", T);
 92:         y = vector_d(static_cast<Eigen::VectorXd::Index>(T));
 93:         context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(T));
 94:         vals_r__ = context__.vals_r("y");
 95:         pos__ = 0;
 96:         size_t y_i_vec_lim__ = T;
 97:         for (size_t i_vec__ = 0; i_vec__ < y_i_vec_lim__; ++i_vec__) {
 98:             y[i_vec__] = vals_r__[pos__++];
 99:         }
100:         context__.validate_dims("data initialization", "S", "int", context__.to_vec());
101:         S = int(0);
102:         vals_i__ = context__.vals_i("S");
103:         pos__ = 0;
104:         S = vals_i__[pos__++];
105:         context__.validate_dims("data initialization", "A", "matrix_d", context__.to_vec(T,S));
106:         validate_non_negative_index("A", "T", T);
107:         validate_non_negative_index("A", "S", S);
108:         A = matrix_d(static_cast<Eigen::VectorXd::Index>(T),static_cast<Eigen::VectorXd::Index>(S));
109:         vals_r__ = context__.vals_r("A");
110:         pos__ = 0;
111:         size_t A_m_mat_lim__ = T;
112:         size_t A_n_mat_lim__ = S;
113:         for (size_t n_mat__ = 0; n_mat__ < A_n_mat_lim__; ++n_mat__) {
114:             for (size_t m_mat__ = 0; m_mat__ < A_m_mat_lim__; ++m_mat__) {
115:                 A(m_mat__,n_mat__) = vals_r__[pos__++];
116:             }
117:         }
118:         context__.validate_dims("data initialization", "s_indx", "int", context__.to_vec(S));
119:         validate_non_negative_index("s_indx", "S", S);
120:         s_indx = std::vector<int>(S,int(0));
121:         vals_i__ = context__.vals_i("s_indx");
122:         pos__ = 0;
123:         size_t s_indx_limit_0__ = S;
124:         for (size_t i_0__ = 0; i_0__ < s_indx_limit_0__; ++i_0__) {
125:             s_indx[i_0__] = vals_i__[pos__++];
126:         }
127:         context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(T,K));
128:         validate_non_negative_index("X", "T", T);
129:         validate_non_negative_index("X", "K", K);
130:         X = matrix_d(static_cast<Eigen::VectorXd::Index>(T),static_cast<Eigen::VectorXd::Index>(K));
131:         vals_r__ = context__.vals_r("X");
132:         pos__ = 0;
133:         size_t X_m_mat_lim__ = T;
134:         size_t X_n_mat_lim__ = K;
135:         for (size_t n_mat__ = 0; n_mat__ < X_n_mat_lim__; ++n_mat__) {
136:             for (size_t m_mat__ = 0; m_mat__ < X_m_mat_lim__; ++m_mat__) {
137:                 X(m_mat__,n_mat__) = vals_r__[pos__++];
138:             }
139:         }
140:         context__.validate_dims("data initialization", "sigma", "double", context__.to_vec());
141:         sigma = double(0);
142:         vals_r__ = context__.vals_r("sigma");
143:         pos__ = 0;
144:         sigma = vals_r__[pos__++];
145:         context__.validate_dims("data initialization", "tau", "double", context__.to_vec());
146:         tau = double(0);
147:         vals_r__ = context__.vals_r("tau");
148:         pos__ = 0;
149:         tau = vals_r__[pos__++];
150: 
151:         // validate, data variables
152:         check_greater_or_equal(function__,"K",K,1);
153:         check_greater_or_equal(function__,"sigma",sigma,0);
154:         check_greater_or_equal(function__,"tau",tau,0);
155:         // initialize data variables
156: 
157:         try {
158:         } catch (const std::exception& e) {
159:             stan::lang::rethrow_located(e,current_statement_begin__);
160:             // Next line prevents compiler griping about no return
161:             throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
162:         }
163: 
164:         // validate transformed data
165: 
166:         // set parameter ranges
167:         num_params_r__ = 0U;
168:         param_ranges_i__.clear();
169:         ++num_params_r__;
170:         ++num_params_r__;
171:         num_params_r__ += S;
172:         ++num_params_r__;
173:         num_params_r__ += K;
174:     }
175: 
176:     ~model39b8611424c9_prophet_linear_growth() { }
177: 
178: 
179:     void transform_inits(const stan::io::var_context& context__,
180:                          std::vector<int>& params_i__,
181:                          std::vector<double>& params_r__,
182:                          std::ostream* pstream__) const {
183:         stan::io::writer<double> writer__(params_r__,params_i__);
184:         size_t pos__;
185:         (void) pos__; // dummy call to supress warning
186:         std::vector<double> vals_r__;
187:         std::vector<int> vals_i__;
188: 
189:         if (!(context__.contains_r("k")))
190:             throw std::runtime_error("variable k missing");
191:         vals_r__ = context__.vals_r("k");
192:         pos__ = 0U;
193:         context__.validate_dims("initialization", "k", "double", context__.to_vec());
194:         // generate_declaration k
195:         double k(0);
196:         k = vals_r__[pos__++];
197:         try {
198:             writer__.scalar_unconstrain(k);
199:         } catch (const std::exception& e) { 
200:             throw std::runtime_error(std::string("Error transforming variable k: ") + e.what());
201:         }
202: 
203:         if (!(context__.contains_r("m")))
204:             throw std::runtime_error("variable m missing");
205:         vals_r__ = context__.vals_r("m");
206:         pos__ = 0U;
207:         context__.validate_dims("initialization", "m", "double", context__.to_vec());
208:         // generate_declaration m
209:         double m(0);
210:         m = vals_r__[pos__++];
211:         try {
212:             writer__.scalar_unconstrain(m);
213:         } catch (const std::exception& e) { 
214:             throw std::runtime_error(std::string("Error transforming variable m: ") + e.what());
215:         }
216: 
217:         if (!(context__.contains_r("delta")))
218:             throw std::runtime_error("variable delta missing");
219:         vals_r__ = context__.vals_r("delta");
220:         pos__ = 0U;
221:         context__.validate_dims("initialization", "delta", "vector_d", context__.to_vec(S));
222:         // generate_declaration delta
223:         vector_d delta(static_cast<Eigen::VectorXd::Index>(S));
224:         for (int j1__ = 0U; j1__ < S; ++j1__)
225:             delta(j1__) = vals_r__[pos__++];
226:         try {
227:             writer__.vector_unconstrain(delta);
228:         } catch (const std::exception& e) { 
229:             throw std::runtime_error(std::string("Error transforming variable delta: ") + e.what());
230:         }
231: 
232:         if (!(context__.contains_r("sigma_obs")))
233:             throw std::runtime_error("variable sigma_obs missing");
234:         vals_r__ = context__.vals_r("sigma_obs");
235:         pos__ = 0U;
236:         context__.validate_dims("initialization", "sigma_obs", "double", context__.to_vec());
237:         // generate_declaration sigma_obs
238:         double sigma_obs(0);
239:         sigma_obs = vals_r__[pos__++];
240:         try {
241:             writer__.scalar_lb_unconstrain(0,sigma_obs);
242:         } catch (const std::exception& e) { 
243:             throw std::runtime_error(std::string("Error transforming variable sigma_obs: ") + e.what());
244:         }
245: 
246:         if (!(context__.contains_r("beta")))
247:             throw std::runtime_error("variable beta missing");
248:         vals_r__ = context__.vals_r("beta");
249:         pos__ = 0U;
250:         context__.validate_dims("initialization", "beta", "vector_d", context__.to_vec(K));
251:         // generate_declaration beta
252:         vector_d beta(static_cast<Eigen::VectorXd::Index>(K));
253:         for (int j1__ = 0U; j1__ < K; ++j1__)
254:             beta(j1__) = vals_r__[pos__++];
255:         try {
256:             writer__.vector_unconstrain(beta);
257:         } catch (const std::exception& e) { 
258:             throw std::runtime_error(std::string("Error transforming variable beta: ") + e.what());
259:         }
260: 
261:         params_r__ = writer__.data_r();
262:         params_i__ = writer__.data_i();
263:     }
264: 
265:     void transform_inits(const stan::io::var_context& context,
266:                          Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
267:                          std::ostream* pstream__) const {
268:       std::vector<double> params_r_vec;
269:       std::vector<int> params_i_vec;
270:       transform_inits(context, params_i_vec, params_r_vec, pstream__);
271:       params_r.resize(params_r_vec.size());
272:       for (int i = 0; i < params_r.size(); ++i)
273:         params_r(i) = params_r_vec[i];
274:     }
275: 
276: 
277:     template <bool propto__, bool jacobian__, typename T__>
278:     T__ log_prob(vector<T__>& params_r__,
279:                  vector<int>& params_i__,
280:                  std::ostream* pstream__ = 0) const {
281: 
282:         T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
283:         (void) DUMMY_VAR__;  // suppress unused var warning
284: 
285:         T__ lp__(0.0);
286:         stan::math::accumulator<T__> lp_accum__;
287: 
288:         // model parameters
289:         stan::io::reader<T__> in__(params_r__,params_i__);
290: 
291:         T__ k;
292:         (void) k;  // dummy to suppress unused var warning
293:         if (jacobian__)
294:             k = in__.scalar_constrain(lp__);
295:         else
296:             k = in__.scalar_constrain();
297: 
298:         T__ m;
299:         (void) m;  // dummy to suppress unused var warning
300:         if (jacobian__)
301:             m = in__.scalar_constrain(lp__);
302:         else
303:             m = in__.scalar_constrain();
304: 
305:         Eigen::Matrix<T__,Eigen::Dynamic,1>  delta;
306:         (void) delta;  // dummy to suppress unused var warning
307:         if (jacobian__)
308:             delta = in__.vector_constrain(S,lp__);
309:         else
310:             delta = in__.vector_constrain(S);
311: 
312:         T__ sigma_obs;
313:         (void) sigma_obs;  // dummy to suppress unused var warning
314:         if (jacobian__)
315:             sigma_obs = in__.scalar_lb_constrain(0,lp__);
316:         else
317:             sigma_obs = in__.scalar_lb_constrain(0);
318: 
319:         Eigen::Matrix<T__,Eigen::Dynamic,1>  beta;
320:         (void) beta;  // dummy to suppress unused var warning
321:         if (jacobian__)
322:             beta = in__.vector_constrain(K,lp__);
323:         else
324:             beta = in__.vector_constrain(K);
325: 
326: 
327:         // transformed parameters
328:         Eigen::Matrix<T__,Eigen::Dynamic,1>  gamma(static_cast<Eigen::VectorXd::Index>(S));
329:         (void) gamma;  // dummy to suppress unused var warning
330:         stan::math::initialize(gamma, DUMMY_VAR__);
331:         stan::math::fill(gamma,DUMMY_VAR__);
332: 
333: 
334:         try {
335:             current_statement_begin__ = 32;
336:             for (int i = 1; i <= S; ++i) {
337: 
338:                 current_statement_begin__ = 33;
339:                 stan::math::assign(get_base1_lhs(gamma,i,"gamma",1), (-(get_base1(t,get_base1(s_indx,i,"s_indx",1),"t",1)) * get_base1(delta,i,"delta",1)));
340:             }
341:         } catch (const std::exception& e) {
342:             stan::lang::rethrow_located(e,current_statement_begin__);
343:             // Next line prevents compiler griping about no return
344:             throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
345:         }
346: 
347:         // validate transformed parameters
348:         for (int i0__ = 0; i0__ < S; ++i0__) {
349:             if (stan::math::is_uninitialized(gamma(i0__))) {
350:                 std::stringstream msg__;
351:                 msg__ << "Undefined transformed parameter: gamma" << '[' << i0__ << ']';
352:                 throw std::runtime_error(msg__.str());
353:             }
354:         }
355: 
356:         const char* function__ = "validate transformed params";
357:         (void) function__;  // dummy to suppress unused var warning
358: 
359:         // model body
360:         try {
361: 
362:             current_statement_begin__ = 39;
363:             lp_accum__.add(normal_log<propto__>(k, 0, 5));
364:             current_statement_begin__ = 40;
365:             lp_accum__.add(normal_log<propto__>(m, 0, 5));
366:             current_statement_begin__ = 41;
367:             lp_accum__.add(double_exponential_log<propto__>(delta, 0, tau));
368:             current_statement_begin__ = 42;
369:             lp_accum__.add(normal_log<propto__>(sigma_obs, 0, 0.5));
370:             current_statement_begin__ = 43;
371:             lp_accum__.add(normal_log<propto__>(beta, 0, sigma));
372:             current_statement_begin__ = 46;
373:             lp_accum__.add(normal_log<propto__>(y, add(add(elt_multiply(add(k,multiply(A,delta)),t),add(m,multiply(A,gamma))),multiply(X,beta)), sigma_obs));
374:         } catch (const std::exception& e) {
375:             stan::lang::rethrow_located(e,current_statement_begin__);
376:             // Next line prevents compiler griping about no return
377:             throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
378:         }
379: 
380:         lp_accum__.add(lp__);
381:         return lp_accum__.sum();
382: 
383:     } // log_prob()
384: 
385:     template <bool propto, bool jacobian, typename T_>
386:     T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
387:                std::ostream* pstream = 0) const {
388:       std::vector<T_> vec_params_r;
389:       vec_params_r.reserve(params_r.size());
390:       for (int i = 0; i < params_r.size(); ++i)
391:         vec_params_r.push_back(params_r(i));
392:       std::vector<int> vec_params_i;
393:       return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
394:     }
395: 
396: 
397:     void get_param_names(std::vector<std::string>& names__) const {
398:         names__.resize(0);
399:         names__.push_back("k");
400:         names__.push_back("m");
401:         names__.push_back("delta");
402:         names__.push_back("sigma_obs");
403:         names__.push_back("beta");
404:         names__.push_back("gamma");
405:     }
406: 
407: 
408:     void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
409:         dimss__.resize(0);
410:         std::vector<size_t> dims__;
411:         dims__.resize(0);
412:         dimss__.push_back(dims__);
413:         dims__.resize(0);
414:         dimss__.push_back(dims__);
415:         dims__.resize(0);
416:         dims__.push_back(S);
417:         dimss__.push_back(dims__);
418:         dims__.resize(0);
419:         dimss__.push_back(dims__);
420:         dims__.resize(0);
421:         dims__.push_back(K);
422:         dimss__.push_back(dims__);
423:         dims__.resize(0);
424:         dims__.push_back(S);
425:         dimss__.push_back(dims__);
426:     }
427: 
428:     template <typename RNG>
429:     void write_array(RNG& base_rng__,
430:                      std::vector<double>& params_r__,
431:                      std::vector<int>& params_i__,
432:                      std::vector<double>& vars__,
433:                      bool include_tparams__ = true,
434:                      bool include_gqs__ = true,
435:                      std::ostream* pstream__ = 0) const {
436:         vars__.resize(0);
437:         stan::io::reader<double> in__(params_r__,params_i__);
438:         static const char* function__ = "model39b8611424c9_prophet_linear_growth_namespace::write_array";
439:         (void) function__; // dummy call to supress warning
440:         // read-transform, write parameters
441:         double k = in__.scalar_constrain();
442:         double m = in__.scalar_constrain();
443:         vector_d delta = in__.vector_constrain(S);
444:         double sigma_obs = in__.scalar_lb_constrain(0);
445:         vector_d beta = in__.vector_constrain(K);
446:         vars__.push_back(k);
447:         vars__.push_back(m);
448:         for (int k_0__ = 0; k_0__ < S; ++k_0__) {
449:             vars__.push_back(delta[k_0__]);
450:         }
451:         vars__.push_back(sigma_obs);
452:         for (int k_0__ = 0; k_0__ < K; ++k_0__) {
453:             vars__.push_back(beta[k_0__]);
454:         }
455: 
456:         if (!include_tparams__) return;
457:         // declare and define transformed parameters
458:         double lp__ = 0.0;
459:         (void) lp__; // dummy call to supress warning
460:         stan::math::accumulator<double> lp_accum__;
461: 
462:         double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
463:         (void) DUMMY_VAR__;  // suppress unused var warning
464: 
465:         vector_d gamma(static_cast<Eigen::VectorXd::Index>(S));
466:         (void) gamma;  // dummy to suppress unused var warning
467:         stan::math::initialize(gamma, std::numeric_limits<double>::quiet_NaN());
468:         stan::math::fill(gamma,DUMMY_VAR__);
469: 
470: 
471:         try {
472:             current_statement_begin__ = 32;
473:             for (int i = 1; i <= S; ++i) {
474: 
475:                 current_statement_begin__ = 33;
476:                 stan::math::assign(get_base1_lhs(gamma,i,"gamma",1), (-(get_base1(t,get_base1(s_indx,i,"s_indx",1),"t",1)) * get_base1(delta,i,"delta",1)));
477:             }
478:         } catch (const std::exception& e) {
479:             stan::lang::rethrow_located(e,current_statement_begin__);
480:             // Next line prevents compiler griping about no return
481:             throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
482:         }
483: 
484:         // validate transformed parameters
485: 
486:         // write transformed parameters
487:         for (int k_0__ = 0; k_0__ < S; ++k_0__) {
488:             vars__.push_back(gamma[k_0__]);
489:         }
490: 
491:         if (!include_gqs__) return;
492:         // declare and define generated quantities
493: 
494: 
495:         try {
496:         } catch (const std::exception& e) {
497:             stan::lang::rethrow_located(e,current_statement_begin__);
498:             // Next line prevents compiler griping about no return
499:             throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
500:         }
501: 
502:         // validate generated quantities
503: 
504:         // write generated quantities
505:     }
506: 
507:     template <typename RNG>
508:     void write_array(RNG& base_rng,
509:                      Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
510:                      Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
511:                      bool include_tparams = true,
512:                      bool include_gqs = true,
513:                      std::ostream* pstream = 0) const {
514:       std::vector<double> params_r_vec(params_r.size());
515:       for (int i = 0; i < params_r.size(); ++i)
516:         params_r_vec[i] = params_r(i);
517:       std::vector<double> vars_vec;
518:       std::vector<int> params_i_vec;
519:       write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
520:       vars.resize(vars_vec.size());
521:       for (int i = 0; i < vars.size(); ++i)
522:         vars(i) = vars_vec[i];
523:     }
524: 
525:     static std::string model_name() {
526:         return "model39b8611424c9_prophet_linear_growth";
527:     }
528: 
529: 
530:     void constrained_param_names(std::vector<std::string>& param_names__,
531:                                  bool include_tparams__ = true,
532:                                  bool include_gqs__ = true) const {
533:         std::stringstream param_name_stream__;
534:         param_name_stream__.str(std::string());
535:         param_name_stream__ << "k";
536:         param_names__.push_back(param_name_stream__.str());
537:         param_name_stream__.str(std::string());
538:         param_name_stream__ << "m";
539:         param_names__.push_back(param_name_stream__.str());
540:         for (int k_0__ = 1; k_0__ <= S; ++k_0__) {
541:             param_name_stream__.str(std::string());
542:             param_name_stream__ << "delta" << '.' << k_0__;
543:             param_names__.push_back(param_name_stream__.str());
544:         }
545:         param_name_stream__.str(std::string());
546:         param_name_stream__ << "sigma_obs";
547:         param_names__.push_back(param_name_stream__.str());
548:         for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
549:             param_name_stream__.str(std::string());
550:             param_name_stream__ << "beta" << '.' << k_0__;
551:             param_names__.push_back(param_name_stream__.str());
552:         }
553: 
554:         if (!include_gqs__ && !include_tparams__) return;
555:         for (int k_0__ = 1; k_0__ <= S; ++k_0__) {
556:             param_name_stream__.str(std::string());
557:             param_name_stream__ << "gamma" << '.' << k_0__;
558:             param_names__.push_back(param_name_stream__.str());
559:         }
560: 
561:         if (!include_gqs__) return;
562:     }
563: 
564: 
565:     void unconstrained_param_names(std::vector<std::string>& param_names__,
566:                                    bool include_tparams__ = true,
567:                                    bool include_gqs__ = true) const {
568:         std::stringstream param_name_stream__;
569:         param_name_stream__.str(std::string());
570:         param_name_stream__ << "k";
571:         param_names__.push_back(param_name_stream__.str());
572:         param_name_stream__.str(std::string());
573:         param_name_stream__ << "m";
574:         param_names__.push_back(param_name_stream__.str());
575:         for (int k_0__ = 1; k_0__ <= S; ++k_0__) {
576:             param_name_stream__.str(std::string());
577:             param_name_stream__ << "delta" << '.' << k_0__;
578:             param_names__.push_back(param_name_stream__.str());
579:         }
580:         param_name_stream__.str(std::string());
581:         param_name_stream__ << "sigma_obs";
582:         param_names__.push_back(param_name_stream__.str());
583:         for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
584:             param_name_stream__.str(std::string());
585:             param_name_stream__ << "beta" << '.' << k_0__;
586:             param_names__.push_back(param_name_stream__.str());
587:         }
588: 
589:         if (!include_gqs__ && !include_tparams__) return;
590:         for (int k_0__ = 1; k_0__ <= S; ++k_0__) {
591:             param_name_stream__.str(std::string());
592:             param_name_stream__ << "gamma" << '.' << k_0__;
593:             param_names__.push_back(param_name_stream__.str());
594:         }
595: 
596:         if (!include_gqs__) return;
597:     }
598: 
599: }; // model
600: 
601: } // namespace
602: 
603: typedef model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth stan_model;
604: 
605: #include <rstan/rstaninc.hpp>
606: /**
607:  * Define Rcpp Module to expose stan_fit's functions to R.
608:  */
609: RCPP_MODULE(stan_fit4model39b8611424c9_prophet_linear_growth_mod){
610:   Rcpp::class_<rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth,
611:                boost::random::ecuyer1988> >("stan_fit4model39b8611424c9_prophet_linear_growth")
612:     // .constructor<Rcpp::List>()
613:     .constructor<SEXP, SEXP>()
614:     // .constructor<SEXP, SEXP>()
615:     .method("call_sampler",
616:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::call_sampler)
617:     .method("param_names",
618:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_names)
619:     .method("param_names_oi",
620:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_names_oi)
621:     .method("param_fnames_oi",
622:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_fnames_oi)
623:     .method("param_dims",
624:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_dims)
625:     .method("param_dims_oi",
626:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_dims_oi)
627:     .method("update_param_oi",
628:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::update_param_oi)
629:     .method("param_oi_tidx",
630:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::param_oi_tidx)
631:     .method("grad_log_prob",
632:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::grad_log_prob)
633:     .method("log_prob",
634:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::log_prob)
635:     .method("unconstrain_pars",
636:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::unconstrain_pars)
637:     .method("constrain_pars",
638:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::constrain_pars)
639:     .method("num_pars_unconstrained",
640:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::num_pars_unconstrained)
641:     .method("unconstrained_param_names",
642:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::unconstrained_param_names)
643:     .method("constrained_param_names",
644:             &rstan::stan_fit<model39b8611424c9_prophet_linear_growth_namespace::model39b8611424c9_prophet_linear_growth, boost::random::ecuyer1988>::constrained_param_names)
645:     ;
646: }
647: 
648: // declarations
649: extern "C" {
650: SEXP file39b8750e5772( ) ;
651: }
652: 
653: // definition
654: 
655: SEXP file39b8750e5772(  ){
656:  return Rcpp::wrap("prophet_linear_growth");
657: }
658: 
659: 
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file39b8750e5772.cpp:8:39: fatal error: stan/model/model_header.hpp: No such file or directory
 #include <stan/model/model_header.hpp>
                                       ^
compilation terminated.
make: *** [file39b8750e5772.o] Error 1
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file39b8750e5772.dll" OBJECTS="file39b8750e5772.o"' had status 2 
In addition: Warning message:
running command 'C:/PROGRA~1/R/R-33~1.3/bin/i386/R CMD SHLIB file39b8750e5772.cpp 2> file39b8750e5772.cpp.err.txt' had status 1

**Comment by bletham** [comment]
It looks like there may be some C compiler issues. Can you try following the directions here (https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows) to reinstall Rtools and then follow the instructions at the bottom to make sure it is functioning properly with Stan?

**Comment by bletham** [comment]
I'm going to close this, but if you're still having this issue please reopen!
