### ISSUE TITLE
Cannot use 'pip install fbprophet' to install prophet on mac

### ISSUE THREAD

**Issue by l0vest0rm** [facebookincubator/prophet#17]
Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-1Wz6u0/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fHkhKl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-1Wz6u0/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fHkhKl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-1Wz6u0/fbprophet/

**Comment by Tafkas** [comment]
The fbprophet package requires pystan, which requires Cython. Try installing Cython with

    pip install Cython
    
This should fix the issue.

**Comment by l0vest0rm** [comment]
the problem exists when Cython already installed

**Comment by seanjtaylor** [comment]
[This question](http://stackoverflow.com/questions/22697440/cc-failed-with-exit-status-1-error-when-install-python-library) suggests that maybe your XCode is outdated.  Can you check `cc --version`.  Here's mine:

```
sjt-mbp1:examples sjt$ cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by l0vest0rm** [comment]
it is ok now when i installed the xcode,thanks to seanjtaylor

**Comment by stories2** [comment]
Failed install fbprophet.
`sudo pip3.5 install fbprophet`

It stocks in `Downloading fbprophet-0.1.1.tar.gz`

I already installed Xcode and Cython.

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by thomzi12** [comment]
FWIW I am encountering same issue as @stories2 

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by stories2** [comment]
@thomzi12 In my case, it just took soooooooooooo long time.
Drink coffee. The time will solve your problem :)

**Comment by philipperemy** [comment]
```
I had the same issue and I could make it work that way:

```
git clone --recursive https://github.com/stan-dev/pystan.git
cd pystan
python setup.py install
pip install fbprophet
```
```

**Comment by matse004** [comment]
Run into the same issue on MacOS ElCapitan (10.11.6). Nothing worked for me except for manually downgrading pystan package from 2.18 to 2.17.1.0.

**Comment by jisumanbu** [comment]
Same issue I met when I install **pystan (2.18.0.0) & fbprophet (0.3.post2)** on macOS(10.13.6)
Issue disappeared after downgrading pystan from 2.18 to 2.17.1.0 as **matse004**'s suggestion.

**Comment by BruceBinBoxing** [comment]
As @matse004  said, using pystan==2.17.1.0 rather than 2.18 works for me!
Do as bellow:

```
sudo pip uninstall pystan
sudo pip install pystan==2.17.1.0
sudo pip install fbprophet
```

**Comment by OliverJBoom** [comment]
Installing via Conda fixed all problems for me

**Comment by anshul-tak** [comment]
Another solution that worked for me is force pip to use homebrew GCC compiler instead of CLANG
1. After installing homebrew
`env CXX=/usr/local/Cellar/gcc/9.2.0/bin/g++-9 CC=/usr/local/Cellar/gcc/9.2.0/bin/gcc-9 pip install fbprophet==0.4.post2`
or Add env variable in your bash rc file.

**Comment by jeroenjanssens** [comment]
I just want to chip in by saying that @anshul-tak's solution worked for me as well. Thanks for that, @anshul-tak. 

For what it's worth, I use `env CC=$(which gcc-9) CXX=$(which g++-9) pip install fbprophet` which (no pun intended) is slightly more sustainable should the version of gcc change (currently it's at 9.2.0_3).

**Comment by maddy2u** [comment]
> Installing via Conda fixed all problems for me

This is the only thing that worked for me in the whole thread.

**Comment by buxizhizhoum** [comment]
export CC=$(which gcc)
export CXX=$(which g++)
pip install fbprophet
And my error is: error: command 'clang' failed with exit status 1
This works, thanks @anshul-tak

**Comment by andreamoro** [comment]
Hi, I have the same problems in installing Prophet. Irrespective of the two exports above, I still get the following error:

```
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/andreamoro/.pyenv/versions/3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-wheel-jmh6cp00
       cwd: /private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Importing plotly failed. Interactive plots will not work.
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
  error: command '/usr/bin/gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/andreamoro/.pyenv/versions/3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-record-s04b7vvw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/andreamoro/.pyenv/versions/3.8.6/include/python3.8/fbprophet
         cwd: /private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Importing plotly failed. Interactive plots will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command '/usr/bin/gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/andreamoro/.pyenv/versions/3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-install-dpr3g5ph/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/pip-record-s04b7vvw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/andreamoro/.pyenv/versions/3.8.6/include/python3.8/fbprophet Check the logs for full command output.
```

I'm not using Anaconda or anything like it, Xcode is installed. 
As far as I can understand from the above, it seems the error code is due to some writing permission, which as a matter of fact are correct because on this working laptop IT prevents me to write into the private folder.

I had a look at the settings, but couldn't spot anything that allow me to specify a different folder.

Has anybody had a similar issue?

Thanks
Andrea

**Comment by vemuri-nath** [comment]
@andreamoro facing the same problem as you mentioned. Please update me if you find a solution
thanks

**Comment by andreamoro** [comment]
It might me a problem with pystan, which relies on C++ libraries that are not found where expected. I'm trying to speak with a developer there. Are you able to run pyStan and a demo example with success on your end @vemuri-nath ?

**Comment by gregwalla** [comment]
Same problem here , nothing seems to work.  I am on MAC OS BIG SUR 11.1
Additional requirements : 
- I use a venv for 'light weight' reproductibilty.

**Comment by erikabergman** [comment]
Hey @gregwalla, I'm also on Big sure, 11.2.1 at this point. I tried normal pip install, conda install, nothing worked, until I followed the advice of @BruceBinBoxing  and downgraded pystan. This worked. For a mac I don't think we need to sudo, but it also didn't hurt, I used it verbatum: 

> sudo pip uninstall pystan
> sudo pip install pystan==2.17.1.0
> sudo pip install fbprophet

**Comment by mahanh** [comment]
reinstalling pystan on macOS Big Sur didn't help me!
I properly installed fbprophet using pip after running the following:
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by espoirMur** [comment]
> xcode-select --install



> reinstalling pystan on macOS Big Sur didn't help me!
> I properly installed fbprophet using pip after running the following:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```

Thanks @mahanh this help to solve the issue on my side

**Comment by seanyboi** [comment]
I'm going to add my two cents, if any one is still having problems make sure you update your Xcode using:
 `xcode-select --install` 
This was my lifesaver along with making sure `pystan` is installed BEFORE you install `fbprophet`

**Comment by plank3ffect** [comment]
Could it be that we are using pyenv and virtualenv?  Mine fails as well because it cannot find pystan, which I definitely installed.  It is executing from a /private/ folder.....

`  File "/private/var/folders/km/1jh10x6x4l11w3bmxqrbgtp40000gn/T/pip-install-ppew3k63/fbprophet_263d1ca7a61543b0bfe1544fa2f11904/fbprophet/models.py", line 209, in build_model
        import pystan
    ModuleNotFoundError: No module named 'pystan'`

Any ideas on how to specify the pystan from the virtualenv?

**Comment by plank3ffect** [comment]
actually, I got it working.  From the FB Prophet GitHub, they acknowledge that the pystan 3.0.0 version broke fbprophet.  The team is currently working on a new version and should publish soon. In the meantime, i had to do a `pip uninstall pystan` to remove 3.0.0 and then install using `pip install pystan~=2.14` to install an older version.  It seems the newer pystan 3.0.0 calls their module `stan` instead of `pystan`, which was breaking a few things.  There were probably more changes to the updated `pystan` rewrite.

**Comment by amadalla** [comment]
> Actually, I just got it working. From the FB Prophet GitHub, they acknowledge that the pystan 3.0.0 version broke fbprophet (#1856). The team is currently working on a new version and should publish soon. In the meantime, i had to do a `pip uninstall pystan` to remove 3.0.0 and then install using `pip install pystan~=2.14` to install an older version. It seems the newer pystan 3.0.0 calls their module `stan` instead of `pystan`, which was breaking a few things. There were probably more changes to the updated `pystan` rewrite.

Thank you @plank3ffect! My error was 'unable to find module pystan', even though it was installed. 
This helped fix the issue.

**Comment by andreamoro** [comment]
It seems this error still persists with pystan 3.2.0. Am I wrong? 

I cannot install the library at all. Anybody else?

**Comment by sarvesha-jaiswal** [comment]
when i tried installing fbprophet I've got the same error? 
anyone know how to install it ?

**Comment by exxcong** [comment]
> Hey @gregwalla, I'm also on Big sure, 11.2.1 at this point. I tried normal pip install, conda install, nothing worked, until I followed the advice of @BruceBinBoxing and downgraded pystan. This worked. For a mac I don't think we need to sudo, but it also didn't hurt, I used it verbatum:
> 
> > sudo pip uninstall pystan
> > sudo pip install pystan==2.17.1.0
> > sudo pip install fbprophet

Thanks a lot! I use mac M1 with Big Sur. I tried all kinds of methods and all failed. But I used your method and it succeed. Thanks!

**Comment by GwenVCX** [comment]
My environment:
OSX : Big Sur 11.6
python : python:3.7-slim
```
$ pip install pystan==2.19
$ pip install fbprophet
```
