### ISSUE TITLE
fail to pip install fbprophet on macOS Sierra. (sorrow)

### ISSUE THREAD

**Issue by evanzhu2013** [facebookincubator/prophet#171]
AI:~ evan$ pip install -U fbprophet
Collecting fbprophet
  Using cached fbprophet-0.1.1.tar.gz
Requirement already up-to-date: matplotlib in ./miniconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already up-to-date: numpy in ./miniconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already up-to-date: pandas>=0.18.1 in ./miniconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already up-to-date: pystan>=2.14 in ./miniconda3/lib/python3.6/site-packages (from fbprophet)
Requirement already up-to-date: six>=1.10 in ./miniconda3/lib/python3.6/site-packages (from matplotlib->fbprophet)
Requirement already up-to-date: python-dateutil in ./miniconda3/lib/python3.6/site-packages (from matplotlib->fbprophet)
Requirement already up-to-date: pytz in ./miniconda3/lib/python3.6/site-packages (from matplotlib->fbprophet)
Requirement already up-to-date: cycler>=0.10 in ./miniconda3/lib/python3.6/site-packages (from matplotlib->fbprophet)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./miniconda3/lib/python3.6/site-packages (from matplotlib->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... error
  Complete output from command /Users/evan/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpggh42yf3pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_models
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 126, in <module>
      """
    File "/Users/evan/miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/evan/miniconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/evan/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/evan/miniconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/evan/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 46, in run
      build_stan_models(target_dir)
    File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 34, in build_stan_models
      sm = StanModel(model_code=model_code)
    File "/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py", line 315, in __init__
      self.module = load_module(self.module_name, lib_dir)
    File "/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py", line 50, in load_module
      return __import__(module_name)
  ImportError: dlopen(/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpgraf9sbn/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_691899172216248136.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
    Referenced from: /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpgraf9sbn/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_691899172216248136.cpython-36m-darwin.so
    Expected in: flat namespace
   in /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpgraf9sbn/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_691899172216248136.cpython-36m-darwin.so
  
  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /Users/evan/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-5shzz7t1-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 126, in <module>
        """
      File "/Users/evan/miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/evan/miniconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/evan/miniconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/evan/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/evan/miniconda3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/evan/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/evan/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 46, in run
        build_stan_models(target_dir)
      File "/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py", line 34, in build_stan_models
        sm = StanModel(model_code=model_code)
      File "/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py", line 315, in __init__
        self.module = load_module(self.module_name, lib_dir)
      File "/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py", line 50, in load_module
        return __import__(module_name)
    ImportError: dlopen(/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmp_38vib2l/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_3185748252074251775.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
      Referenced from: /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmp_38vib2l/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_3185748252074251775.cpython-36m-darwin.so
      Expected in: flat namespace
     in /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmp_38vib2l/stanfit4anon_model_7a788197ac3493030b72020b9ffdbe7d_3185748252074251775.cpython-36m-darwin.so
    
    ----------------------------------------
Command "/Users/evan/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-5shzz7t1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/pip-build-ezf40u31/fbprophet/

**Comment by seanjtaylor** [comment]
Hmm we did just release a new version.  I'll try to repo tomorrow on my laptop, but it would be useful to know if it's a regression.  Would you mind trying to install the previous version? 

https://pypi.python.org/packages/b1/ba/237a6875e9a61dcef997399b988afedbbdea112ae5ef7e0ad99faca1e9f4/fbprophet-0.1.post1.tar.gz#md5=a7afb620fa2f98a27219a62b6f1b2db0

**Comment by evanzhu2013** [comment]
It did work on previous version. The error happened when I updated it.

Thanks for your reply.

**Comment by bletham** [comment]
Do you mind verifying that pystan is working?

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
Just want to make sure it didn't get messed up by the upgrade somehow.

**Comment by evanzhu2013** [comment]
Yeah. The reported error is :

In [1]: import pystan
   ...: model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
   ...: model = pystan.StanModel(model_code=model_code)  # this will take a minu
   ...: te
   ...: y = model.sampling(n_jobs=1).extract()['y']
   ...: y.mean()  # should be close to 0
   ...:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19d1f2b2eeb1> in <module>()
      1 import pystan
      2 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
----> 3 model = pystan.StanModel(model_code=model_code)  # this will take a minute
      4 y = model.sampling(n_jobs=1).extract()['y']
      5 y.mean()  # should be close to 0

/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    313                 os.dup2(orig_stderr, sys.stderr.fileno())
    314
--> 315         self.module = load_module(self.module_name, lib_dir)
    316         self.module_filename = os.path.basename(self.module.__file__)
    317         # once the module is in memory, we no longer need the file on disk

/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py in load_module(module_name, module_path)
     48         pyximport.install()
     49         sys.path.append(module_path)
---> 50         return __import__(module_name)
     51     else:
     52         import imp

ImportError: dlopen(/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpogcf9ldq/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_1380477929625010121.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpogcf9ldq/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_1380477929625010121.cpython-36m-darwin.so
  Expected in: flat namespace
 in /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpogcf9ldq/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_1380477929625010121.cpython-36m-darwin.so

**Comment by evanzhu2013** [comment]
After re-install the pystan. The problem continues.

**Comment by rolando** [comment]
Probably has to do with the compiler flags. Conda-Forge uses this flags on OSX: https://github.com/conda-forge/toolchain-feedstock/blob/master/recipe/activate.sh#L3

You can install `fbprophet` from `conda-forge` channel: `conda install -c conda-forge fbprophet`

**Comment by evanzhu2013** [comment]
It works after conda install from conda-forge.

I  really appreciate your help.

**Comment by mujeebla** [comment]
@rmax Your solution worked. However, the fbprophet is a later version, I am currently working on a project in which I need the new updates present in version 3.0. Kindly advise on how to work around this.

**Comment by philipperemy** [comment]
I had the same issue and I could make it work that way:

```
git clone --recursive https://github.com/stan-dev/pystan.git
cd pystan
python setup.py install
pip install fbprophet
```
