### ISSUE TITLE
how to use prophet to predict two related varible

### ISSUE THREAD

**Issue by stevenjk2012** [facebookincubator/prophet#172]
I want to predict the product sales volume .for example: one data y1 is the 2014designed sale record of 2015,2016;  another data y2 is 2015 designed sale record of 2016;  how to predict y2 of 2017?
if I just use y1, the trend always down...

**Comment by stevenjk2012** [comment]
![1010_1](https://cloud.githubusercontent.com/assets/26265579/25160493/f3457808-24e8-11e7-984a-ac518c22158c.png)

**Comment by stevenjk2012** [comment]
and I want predict y3 2016 designed ,

**Comment by bletham** [comment]
This seems related to the request in #101, or possibly #49. There is currently no support for this type of multiple-series modeling, but hopefully will be soon!

**Comment by bletham** [comment]
I'm going to close this so that we can keep the discussion over in #101 and #49.
