### ISSUE TITLE
Incorrect placement of x-axis tick labels in trend and holidays plot (Python only)

### ISSUE THREAD

**Issue by geoninja** [facebookincubator/prophet#173]
If you compare the x-axis labels in the R and Python plots for the trend and holidays components in the holiday_effects [notebook](https://github.com/facebookincubator/prophet/blob/master/notebooks/holiday_effects.ipynb) for example, you can see that the labels are misplaced in the Python version. I have manually re-created these two plots with Matplotlib (cell input 29 [here](https://github.com/geoninja/Forecasting/blob/master/ProphetTutorials/ProphetTutorial.ipynb)) just to check, and indeed the labels were then matching the correct positions as seen in the output from R.

**Comment by bletham** [comment]
Thanks for pointing this out. This axis labeling bug was fixed in the 0.1.1 release last week but we hadn't corrected the notebooks (d02b6f62b2f394f60d526644d09e0cd81583acb0 does this).

If you download the latest version on pip this bug will be fixed:
```
pip install fbprophet --upgrade
```

**Comment by geoninja** [comment]
Great! I upgraded and tested, it's all working. I will close this. Thank you!
