### ISSUE TITLE
Automatically prediction for multiple columns in file

### ISSUE THREAD

**Issue by beloteloff** [facebookincubator/prophet#175]
Hi!
Thanks for this project!
I have a task, where I need to do predictions for 64 columns in file.
I create a function, which takes each column from file.
`
table = pd.pivot_table(df_plot,aggfunc=np.sum,columns=['numb'], values=["users"], index=['ds',])

table.columns = table.columns.droplevel(level=0)

def fun_function(i):
   return table.dropna(subset=[table.columns[i]]).iloc[:,i].to_frame()
for i in range(len(table.columns)):
    xz(i)=table.loc[:,i]
    x(i)=xz(i).reset_index()
    x(i).columns.values[1] = "y"
    m(i) = Prophet().fit(i)
    future(i) = m(i).make_future_dataframe(periods=365)
    forecast(i) = m.predict(future(i))
    forecast(i)[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail();` 

But I have mistake in first steps:

` File "<ipython-input-2-61911440b1c8>", line 20
    xz(i)=table.loc[:,i]
    ^
SyntaxError: can't assign to function call
`
How can I decide this problem?

**Comment by bletham** [comment]
The problem is that the parentheses in `xz(i)` treat it as a function. It should probably be `[ ]`, and also needs to be defined along with the other things with `(i)`.
