### ISSUE TITLE
Can we use it to forecast different peoples' daily page views for the Wikipedia simultaneously?

### ISSUE THREAD

**Issue by liyumeng** [facebookincubator/prophet#18]
In the examples, I see we can use it to forecast the time series of daily page views for the Wikipedia page for Peyton Manning. **If I get many quarterbacks' data and want to forecast their page views in one model, is it possible?** Because I think there should be many same features in their time series, such as periodic seasonality, holidays and other potential features. The model should be better if it can see many other people's data. Is it right? Thanking you!

**Comment by seanjtaylor** [comment]
Right now Prophet does not support multivariate time series models.  It's certainly something we're thinking about, but right now the easiest way to proceed is just to loop through them and forecast them independently.
