### ISSUE TITLE
Bugfix for scale in setup_dataframe for negative values

### ISSUE THREAD

**Issue by GustafRydevik** [facebookincubator/prophet#182]
Hi,

On line 11-12 in prophet:::setup_dataframe, it currently says:
```
if (initialize_scales) {
    m$y.scale <- max(df$y)
    m$start <- min(df$ds)
    m$t.scale <- as.numeric(max(df$ds) - m$start)
  }
```
The definition of y.scale can cause a problem if dealing with negative numbers. I believe a more correct version would be  to use the absolute value, as per the following:

```
if (initialize_scales) {
    m$y.scale <- max(abs(df$y))
    m$start <- min(df$ds)
    m$t.scale <- as.numeric(max(df$ds) - m$start)
  }
```

(This came up because I was fitting a trend to a time series of proportions - thus using the log of the proportion as response variable to ensure non-negative results, and with a max value of log(1)=0 -> a y scale of infinity).

**Comment by bletham** [comment]
This is fixed in https://github.com/facebookincubator/prophet/commit/3ebedb111004ac97378ab497a8636b86c45296bd. Thanks!
