### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by EskreisWinkler** [facebookincubator/prophet#183]
I appreciated the Quick Start guide a lot to get me using the model comfortably, but do you have a more extensive documentation for the use of Prophet in Python? For instance, I would be interested in what the syntax is for each parameter that can be specified in the prophet/fit functions. 

Also, is there a way to suppress output in the model fitting?

**Comment by bletham** [comment]
I think you should find the docstrings for each method to be pretty complete. So for instance
```
help(Prophet)
```
It would be good to put this in the online documentation too though.

As for suppressing output, see #170 . The output is coming from the underlying C++ Stan routines and so it's proving challenging to suppress. We might end up having to wait for upstream changes from Stan but I need to look more into it.

**Comment by EskreisWinkler** [comment]
Thanks!

**Comment by bletham** [comment]
@p9anand I'm not exactly sure what you mean by online training - if you mean updating the model as new data come in, then there is some discussion of that in #46. Basically you just have to re-fit the model from scratch each time.
