### ISSUE TITLE
which days are the exact day the holiday start and end separately？

### ISSUE THREAD

**Issue by kobesxl** [facebookincubator/prophet#185]
Thanks for this project.
I have a question for predicting clothing sales, when holiday comes, the number of sales will increase a lot, but which day is the exact day the holiday start and end, because the trend usually up a few days ahead of day, and it may not end just at the holiday ends. How can i set lower_window and upper_window? I think this can be handled with some statistical methods.

**Comment by datafool** [comment]
Refer to the notebook https://github.com/facebookincubator/prophet/blob/master/notebooks/holiday_effects.ipynb , to understand how to effectively model holidays. Hope this works!

**Comment by kobesxl** [comment]
@datafool thx

**Comment by bletham** [comment]
Thanks @datafool!
