### ISSUE TITLE
Holidays effect does not work when predicting with weekly frequency 

### ISSUE THREAD

**Issue by trungngv** [facebookincubator/prophet#186]
<img width="645" alt="screen shot 2017-05-12 at 11 32 46 am" src="https://cloud.githubusercontent.com/assets/1892212/25978710/5ab94886-3707-11e7-93ed-b126af401176.png">

I train a model with daily data and specify holidays explicitly. This was learned by the model and works well with daily prediction. However when I make weekly predictions, the model does not seem to extrapolate for future holidays. For example on the graph above, there should be a spike around Nov 2017 due to the holiday.

One quick fix is  to predict on daily level and roll them up into weeks, but it's better to have the correct predictions automatically.

**Comment by bletham** [comment]
Can you give some more detail on what you mean by weekly predictions? Are you fitting the model to weekly roll-up data? And then what dates are you passing to the `predict` method, the first day of the week for the future weeks?

**Comment by datafool** [comment]
@trungngv So, are you training using daily data and making weekly prediction? If yes, then specifying future holiday using weekly date might be helpful than giving exact date of holiday. 

Also, its much better to train using weekly data and predict using weekly data, as there will not be any mis-match between holiday window effect, whereas when using daily data for training and predicting at weekly level, the window mismatch might over-estimate the effect of the holiday.

Do, let me know if this helps.

**Comment by bletham** [comment]
I'm going to close this for now but please re-open if you still have questions about working with weekly data.

**Comment by raginikr** [comment]
Hi, I am working with weekly data. I want to show impact of easter holiday (just one day) on my entire week. For eg. 20th April 2014 was a easter and I noticed a spike in my data for the previous week (week ending 19th April 2014 - I have Saturday ending)

Creating a list of dataframe with easter holiday for every year is not capturing any impact.
