### ISSUE TITLE
Set verbosity for Printing Meta Information

### ISSUE THREAD

**Issue by Hasil-Sharma** [facebookincubator/prophet#188]
`print` statements such as one in [forecaster.py](forecaster.py)  line number - 380 and 381 should either write to stderr instead of stdout or such there should an option to turn off these messages.

When such a statement is executed in a distributed environment such as hive with a custom script using `fbprophet`, output includes such rougue statements as well.

```python
print('Disabling yearly seasonality. Run prophet with '
                      'yearly_seasonality=True to override this.')
```

**Comment by bletham** [comment]
Yes this should be done with INFO level logging. This is tangentially related to #170 in setting verbosity.
