### ISSUE TITLE
file dump request

### ISSUE THREAD

**Issue by rt711** [facebookincubator/prophet#19]
Could you please provide the filedump used in example? wikipediatrend package is not usable at the moment since 
stats.grok.se is down and it's unknown if it will be available again.

as an alternative, this site can be used: [https://tools.wmflabs.org/](https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2015-07-01&end=2017-02-05&pages=Peyton_Manning)
[pageviews.zip](https://github.com/facebookincubator/prophet/files/801377/pageviews.zip)

**Comment by seanjtaylor** [comment]
The Peyton Manning data is available in the examples directory: https://github.com/facebookincubator/prophet/blob/master/examples/example_wp_peyton_manning.csv
