### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by vaidaga** [facebookincubator/prophet#190]
How do I generate the scoring equation for FBProphet?
If I have to score it on Teradata with no Python connector can I do that?
If I need to use Python do i have to fit the model and score every time? 

I am not a technical person so not so sure how would I implement in production set up.

**Comment by bletham** [comment]
Sorry, I'm not sure what you mean by the scoring equation. Do you mean the gradient of the log-likelihood (https://en.wikipedia.org/wiki/Score_(statistics))?

**Comment by vaidaga** [comment]
I was referring to - Let's say i build model in Python on a VM whereas my data comes from Teradata / Bigquery. How do I implement automatically on BigQuery once I have built a model on Python. I dont want to use Python / R post i have trained the model.
________________________________________

**Comment by bletham** [comment]
I don't think what you are describing will be possible. Evaluating the model to produce a new forecast will require Python / R.
