### ISSUE TITLE
logistic growth model "strange behaviour"

### ISSUE THREAD

**Issue by motyocska** [facebookincubator/prophet#191]
Dear All,

wonder if you could help with the following question:

y <-log(c(0.3684693,0.4938679,0.4429201,0.452598,0.4301452,0.4315169, 0.447026,0.496179,0.4045693,0.398533,
      0.3551111,0.431079,0.4063136,0.4120126,0.5210375,0.402897,0.4466131,0.5005669,0.5014164,0.5042271,
      0.5498575,0.6014215,0.4415863,0.4377443, 0.4316092,0.4156757,0.3517915,0.3669508,0.3899471,0.3964143,
      0.4001074,0.3851003,0.4222451,0.375324,0.3652045,0.3376978,0.383012,0.3763665,0.3550609,0.2958678,0.3726571,
      0.3442298
      
      ))

ds<-seq(as.Date("2013-07-01"), by = "month", length = 42)

cap<-rep(min(y),length(ds))
df<-data.frame(ds=ds,y=y,cap=cap)

m <- prophet(df = df, growth ="logistic", changepoints = NULL,
            # n.changepoints = 25, 
             yearly.seasonality = TRUE,
             weekly.seasonality = FALSE, holidays = NULL,
             seasonality.prior.scale = 10000000, 
            #holidays.prior.scale = 10,
             changepoint.prior.scale = 0.7, mcmc.samples = 5000, 
            interval.width = 0.75,
             uncertainty.samples = 1000, fit = TRUE
            ,control = list(adapt_delta = 0.99
            ,max_treedepth =15
            )
)

m[['history']]['y']<-exp(m[['history']]['y'])

future <- make_future_dataframe(m, periods = 24,freq="month")
future['cap'] = min(y)
forecast <- predict(m, future)
forecast$cap<-exp(forecast$cap)
forecast$yhat<-exp(forecast$yhat)
forecast$yhat_lower<-exp(forecast$yhat_lower)
forecast$yhat_upper<-exp(forecast$yhat_upper)

plot(m, forecast)

ones plotted you will see the predicted line "pulls towards" the upper range of the interval... If I run a linear model with full bayesian inference or logistic with MAP, the results of the fit are reasonable, but not optimal to my liking, so trying the full bayesian inference with logistic, which gives me the plotted results you see...

Ant thoughts on what I may be doing wrong or how I can improve upon the modelling?

Appreciate your help..

Andras

**Comment by bletham** [comment]
There seem to be 2 things going on here. The first is that the logistic growth doesn't work properly with negative data (#182) - this is a bug. The second is that the logistic growth only provides saturation to an upper bound, not a lower bound (#81). Saturating lower bounds is a future feature.
