### ISSUE TITLE
what happend in the two edition？

### ISSUE THREAD

**Issue by stevenjk2012** [facebookincubator/prophet#195]
I use the same code and the same data to test，the result is quite different

**Comment by stevenjk2012** [comment]
![fb0 1 1](https://cloud.githubusercontent.com/assets/26265579/26183873/3ac6478e-3bb4-11e7-98d7-9630e6d61615.png)
![fb0 1](https://cloud.githubusercontent.com/assets/26265579/26183874/3b9dfa26-3bb4-11e7-860b-882f21e69ac2.png)

**Comment by stevenjk2012** [comment]
the first picture is fbprophet0.1post; the other is fbprophet0.1.1

**Comment by datafool** [comment]
One of the major change is creation of automatic creation of weekly and yearly seasonality. Below is copied from the code - 
1.  Turns on yearly seasonality if there is >=2 years of history.
2. Turns on weekly seasonality if there is >=2 weeks of history, and the spacing between dates in the history is <7 days.

So, if your data has changed as per above given pointers then forecast will indeed change. If above does not answer the question, it would be good to have a look at the data

**Comment by stevenjk2012** [comment]
ok，3q

**Comment by arvindacumos** [comment]
Is there a way to disable automatic creation of weekly and yearly seasonality i.e. boolean parameter?

**Comment by datafool** [comment]
@arvindacumos yes it can be disabled! when instantiating Prophet() give following argument as False.
yearly_seasonality=False
weekly_seasonality=False

i.e. instantiate Prophet as p = Prophet(yearly_seasonality=False, weekly_seasonality=False)

De-fault setting is 'auto' and in this case prophet will decide to create seasonality as given in my previous comment!

Hope this helps!

**Comment by arvindacumos** [comment]
Thanks allot @datafool
