### ISSUE TITLE
Python kernel dies when ds has missing data

### ISSUE THREAD

**Issue by aechase** [facebookincubator/prophet#198]
I was having trouble getting the Quick Start sample code to run on my machine, because every call to `m.fit(df)` caused my kernel to die. Turns out the data I was importing contained a sum as the final row.

<img width="261" alt="screen shot 2017-05-19 at 14 10 44" src="https://cloud.githubusercontent.com/assets/5527610/26249171/4e01f50c-3c9d-11e7-9165-03226fd41a9f.png">

Removing the final row fixes the problem, and I assume that the NaT is the cause. Should Prophet raise an error about NaTs somewhere around [here](https://github.com/facebookincubator/prophet/blob/master/python/fbprophet/forecaster.py#L130) and [here](https://github.com/facebookincubator/prophet/blob/master/R/R/prophet.R#L127)?

**Comment by bletham** [comment]
Thanks for pointing this out, yes this should be filtered out.

**Comment by aechase** [comment]
Ah it turns out R already has an error raise [here](https://github.com/facebookincubator/prophet/blob/master/R/R/prophet.R#L221), so I just need to add something similar in Python, then write a couple tests.

**Comment by bletham** [comment]
This is fixed in https://github.com/facebookincubator/prophet/commit/8383d3bea6ea2e70399abbbadeffeee75edd9d60. Thanks!
