### ISSUE TITLE
How to plot hourly graph ?

### ISSUE THREAD

**Issue by ofir887** [facebookincubator/prophet#199]
Hi,
How can I plot hourly graph like this in prophet ?
Thanks !
![a005fa98-0b28-11e7-8d52-c75fd32f9871](https://cloud.githubusercontent.com/assets/22930172/26274285/48c59e56-3d4f-11e7-8f62-3b808b6c3f65.png)

**Comment by ofir887** [comment]
Help someone??

**Comment by bletham** [comment]
Sorry for the slow response. Right now Prophet is based on daily data. Extending to hourly data is on the roadmap in #29. The model extends naturally to hourly data, the main blocker is that the R version uses the Date object type which needs to be swapped out for datetime. (And we'll need to handle holidays differently for non-daily data).

**Comment by bletham** [comment]
I'm going to close this and will post in #29 once this new feature is ready.
