### ISSUE TITLE
Time-varying seasonality in prophet

### ISSUE THREAD

**Issue by tvatter** [facebookincubator/prophet#20]
I was wondering: is there a way of taking into account a time-varying seasonality?

For instance, an increase in level is often accompanied by an increase in the magnitude of the seasonal oscillations.

The following example in R:
```
library(prophet)
library(forecast)
data(gas)
df <- data.frame(ds = as.Date.ts(gas), y = as.numeric(gas))
m <- prophet(df)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
plot(m, forecast)
```
In this case, it looks like prophet overestimates the oscillations at the beginning and underestimates them at the end.

How should I deal with such a feature?

**Comment by seanjtaylor** [comment]
Good question!  I suggest log-transforming the data:
```
df <- data.frame(ds = as.Date.ts(gas), y = log(as.numeric(gas)))
```

By default, the seasonality is additive, while in this case it's likely to be multiplicative.  By taking the log you get a constant seasonality:

![image](https://cloud.githubusercontent.com/assets/7317/23336464/37286a1c-fb86-11e6-84a0-a52611170750.png)

However as of right now there's now way for Prophet to learn time-varying seasonal parameters.  It's certainly an extension to the model we've thought about but adding the complexity is a tradeoff.

**Comment by sanjeev66** [comment]
I notice this applies to holidays as well. I input a bunch of holidays into the model and saw that they were all assigned the same coefficient. Am I right in assuming you don't model the variation from year to year for a given holiday? Would it help to pass every holiday type as a separate holiday itself?
