### ISSUE TITLE
Failed building wheel for fbprophet

### ISSUE THREAD

**Issue by sonic3366** [facebookincubator/prophet#201]
pip install fbprophet  
Collecting fbprophet
  Using cached fbprophet-0.1.1.tar.gz
Requirement already satisfied: matplotlib in /root/anaconda2/lib/python2.7/site-packages (from fbprophet)
Requirement already satisfied: numpy in /root/anaconda2/lib/python2.7/site-packages (from fbprophet)
Requirement already satisfied: pandas>=0.18.1 in /root/anaconda2/lib/python2.7/site-packages (from fbprophet)
Requirement already satisfied: pystan>=2.14 in /root/anaconda2/lib/python2.7/site-packages (from fbprophet)
Requirement already satisfied: six>=1.10 in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: python-dateutil in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: functools32 in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: subprocess32 in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pytz in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: cycler>=0.10 in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /root/anaconda2/lib/python2.7/site-packages (from matplotlib->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... error
  Complete output from command /root/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8Yl5PE/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpICUNmGpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_models
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
  error: command 'gcc' failed with exit status 4
  
  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /root/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8Yl5PE/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-FZ012k-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7a788197ac3493030b72020b9ffdbe7d NOW.
    error: command 'gcc' failed with exit status 4
    
    ----------------------------------------
Command "/root/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8Yl5PE/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-FZ012k-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8Yl5PE/fbprophet/

**Comment by bletham** [comment]
It looks like gcc isn't working correctly in anaconda.

The easiest way to install Prophet in anaconda is through conda-forge:
```
conda install -c conda-forge fbprophet
```
Alternatively, try installing gcc in Anaconda:
```
conda install gcc
```
and then try pip install again.

**Comment by bletham** [comment]
If that didn't work then feel free to re-open!

**Comment by saravanansaminathan** [comment]
For pip install users change the python interpreter to python 3.7 issue will get solved. With python 3.6 interpreter pystan and fbprophet problem comes

**Comment by yuvrajyadav13** [comment]
Try installing fbprophet on pycharm. Then copy those package folders(fbprophet, fbprophet-0.5-py3.6.egg-info) from 
**PycharmProjects/SMAP/venv/lib/python3.6/site-packages**
to **.local/lib/python3.6/site-packages** .
And if plotly error raises install plotly.

**Comment by foorman** [comment]
> 
> 
> Try installing fbprophet on pycharm. Then copy those package folders(fbprophet, fbprophet-0.5-py3.6.egg-info) from
> **PycharmProjects/SMAP/venv/lib/python3.6/site-packages**
> to **.local/lib/python3.6/site-packages** .
> And if plotly error raises install plotly.

Cannot install fbprophet on pycharm also
