### ISSUE TITLE
Is there a Continuous Integration service available?

### ISSUE THREAD

**Issue by luiscape** [facebookincubator/prophet#203]
Is this project using a Continuous Integration service of some kind (e.g. Travis, CircleCI)? I didn't find those in the usual configuration files. Those are plenty useful for running the test suite and building projects.

**Comment by bletham** [comment]
@seanjtaylor and #160

**Comment by bletham** [comment]
@luiscape I just merged #160 which adds the .travis.yml file. Does that give you what you need?

**Comment by bletham** [comment]
This should be resolved, but if there are further needs related to Travis feel free to reopen.

**Comment by luiscape** [comment]
Hi @bletham yes, sorry for not getting back earlier to you. Good addition! Thanks!
