### ISSUE TITLE
Prophet package in R: Unable to load from library

### ISSUE THREAD

**Issue by ryathind** [facebookincubator/prophet#205]
Can someone help me with "prophet" package addition to library?

I am on Windows and was successful in installing the package on R version 3.3.3 including the dependent files, however when I try using it "library (prophet)" - I get the error posted below. I did look for solutions on the link provided in the error along with various other forums but found no solutions.

Does this package require C++ Compiler to be installed? How do I resolve this issue?

Warning: running command '"C:/Documents/R/R-3.3.3/bin//R" CMD config CXX' had status 1
No C++ compiler found, so the following will probably not work.
See https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows#toolchain
Warning: running command 'C:/Documents/R/R-3.3.3/bin/i386/R CMD SHLIB file54474622720.cpp 2> file54474622720.cpp.err.txt' had status 1
Warning message:
running command 'make -f "C:/DOCUME~1/R/R-33~1.3/etc/i386/Makeconf" -f "C:/DOCUME~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' S

**Comment by ryathind** [comment]
I forgot to mention that Rtools too is installed!

**Comment by Ic3fr0g** [comment]
Try the following -  devtools::find_rtools(TRUE)
1. Restart your system and uninstall `devtools`, `rstan`, `prophet`
2. Install packages - `devtools`, `prophet`
Try loading the package now with `library(prophet)` 
If it still doesn't work, show us the output of - `devtools::find_rtools(TRUE)` and then do this - 
3.  Install C++ compiler from `http://landinghub.visualstudio.com/visual-cpp-build-tools`

**Comment by bletham** [comment]
The issue does seem to be with Rtools. Could you re-install Rtools following the link that it printed out (https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows#toolchain)? Be sure to check the box to add RTools to the path. Then follow the directions under "verify that Rtools can be used in R" to check that it is working.

**Comment by bletham** [comment]
I'm hoping this was resolved, if it wasn't then please reopen!
