### ISSUE TITLE
run error in specific data

### ISSUE THREAD

**Issue by kevindu1993** [facebookincubator/prophet#209]
Hello fellow prophets I have a stock data which contains the following data..
"ds","y"
2014-09-04,1
2014-09-05,2
...
2014-12-07,95
2014-12-08,96
and the code run error in m.fit(df)

while I delete the first line or the last line：
"ds","y"
2014-09-04,1
2014-09-05,2
...
2014-12-07,95
then the code run success

**Comment by bletham** [comment]
Could you paste the actual error that you are getting? And would it be possible to attach a csv with the data so I can try to replicate?

**Comment by bletham** [comment]
If the issue is the same as #200 , please check my response and hopefully fix there.

**Comment by bletham** [comment]
I'm pretty confident this is the same as #200 and so am going to close, but if the fix there doesn't work please reopen.
