### ISSUE TITLE
inst folder is missing in R

### ISSUE THREAD

**Issue by zedoul** [facebookincubator/prophet#21]
Thank you for your open source!

It seems R package in this Github does not contain inst folder,
although there is "stan" folder in R library when I install it from CRAN
i.e. dir.exists(system.file("stan", package = 'prophet')) == T

but it will show build break with R CMD INSTALL command. I will show "cannot open file ... "

**Comment by zedoul** [comment]
If in case of it is missing, I created a pull request 

https://github.com/facebookincubator/prophet/pull/23

**Comment by bletham** [comment]
Thanks @zedoul, there was originally a symlink here that seems to have gone missing while we were getting the repository set up. I've merged in #23.
