### ISSUE TITLE
Is there a parameter to close weekly_season when some events happen?

### ISSUE THREAD

**Issue by stevenjk2012** [facebookincubator/prophet#213]
In my predict situation , I need to predict the sale record of jewelry . The trend is ok ,but the Valentine's day of 2017-02-14 is very poor. after check the data ,I found that : 2015-02-14 is Sat,and 2016.2.14 is Sunday;
the sale record is twice. But 2017-02-14 is Wednesday, so the predict data is lower .
ps:weekly(1~7):0.28  -0.12 -0.11 -0.11 -0.12 -0.08 0.3
If I can reduce the influence of weekly_seasonlity of  Valentine's day ,the predict is ok

**Comment by kobesxl** [comment]
I have the same question, could anyone can help?

**Comment by bletham** [comment]
This should work by adding a holiday effect for Valentine's day (https://facebookincubator.github.io/prophet/docs/holiday_effects.html). Does that do it?

**Comment by stevenjk2012** [comment]
yes ,I set the holiday. but the history is special day of the week ,the week_seasonality make prediction fail

**Comment by vhpietil** [comment]
I guess the problem is that the additive effect might vary a lot depending
on the weekday. Effect of valentine's day on wednesday might be totally
different from effect when valentine's day is on sunday. As prophet
estimates one effect that doesn't depend on the day of week, the forecast
can be unreasonable.


to 8. kesäkuuta 2017 klo 7.20 Stevenjk <notifications@github.com> kirjoitti:

**Comment by maskani-moh** [comment]
@stevenjk2012 Have you tried to smooth the seasonality learned on holidays? 
You can use `holidays_prior_scale` to adjust your fitting curve. The smaller the parameter value is, the smoother your fitting will be.

**Comment by bletham** [comment]
Another thing would be to make separate holidays for Valentines-on-Weekday and Valentines-on-Weekend. Unfortunately given only Valentines-on-Weekend in the data, I don't expect Prophet to be able to predict a different holiday effect in the weekdays. (But moving forward with both it should).

**Comment by bletham** [comment]
This seems to have been resolved, if you have additional questions along this line feel free to reopen!
