### ISSUE TITLE
how to get the value of initial log joint probability?

### ISSUE THREAD

**Issue by bifeng** [facebookincubator/prophet#218]
I have fitted the prophet model, when the time series is not seasonality and set the yearly.seasonality = T, the value of log joint probability is much bigger. So i want to get this value.
(I am using this predicting multiple time series,  some of the time series is seasonality, so i set the yearly.seasonality=T).

Initial log joint probability = -31.32824
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance

**Comment by bletham** [comment]
This is being printed by RStan. Unfortunately I don't expect there to be an easy way to get at the initial value.
