### ISSUE TITLE
Stop printing the logs generated by facebook prophet in python

### ISSUE THREAD

**Issue by nikitagupta55** [facebookincubator/prophet#219]
How do I stop printing the "the print statements" generated by prophet? For eg: Dosabling yearly seasonality ,convergence terminated etc. I just do not want anythinh to be printed on stdout.

**Comment by bletham** [comment]
#197 swaps the `print()` out with logger calls which will handle the seasonality messages (#188). The messages about convergence and optimization related stuff come from Stan, and these seem to be harder to remove (see #170).

**Comment by randlet** [comment]
@nikitagupta55 see #223 for a decorator that can suppress all (I think) output.

**Comment by bletham** [comment]
I'm going to close this and further discussion will happen in #170 and #223.
