### ISSUE TITLE
install pystan on windows 7 Anaconda prompt with python 3.5.3 successfully but failed to pass the test 

### ISSUE THREAD

**Issue by wangyifan1004** [facebookincubator/prophet#22]
Already installed python 3.53, pystan,Visual C++ 2015 Build Tools-win7
when I test the pystan :
>>> import pystan
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)
>>> y = model.sampling(n_jobs=1).extract()['y']
>>> y.mean()  # with luck the result will be near 0

the output:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.

>>-0.016311821652416087

This may means that stan work well on this test.
But when I test pystan in this way :

>>>import pystan
>>>sm = pystan.StanModel(model_code=open('prophet_linear_growth.stan').read())

output:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_35bf14a7f93814266f16b4cf48b40a5a NOW.

DistutilsExecError                        Traceback (most recent call last)
F:\Anaconda2\envs\py33\lib\distutils\_msvccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    381             try:
--> 382                 self.spawn(args)
    383             except DistutilsExecError as msg:

F:\Anaconda2\envs\py33\lib\distutils\_msvccompiler.py in spawn(self, cmd)
    500             os.environ['path'] = self._paths
--> 501             return super().spawn(cmd)
    502         finally:

F:\Anaconda2\envs\py33\lib\distutils\ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

F:\Anaconda2\envs\py33\lib\distutils\spawn.py in spawn(cmd, search_path, verbose, dry_run)
     37     elif os.name == 'nt':
---> 38         _spawn_nt(cmd, search_path, dry_run=dry_run)
     39     else:

F:\Anaconda2\envs\py33\lib\distutils\spawn.py in _spawn_nt(cmd, search_path, verbose, dry_run)
     80             raise DistutilsExecError(
---> 81                   "command %r failed with exit status %d" % (cmd, rc))
     82 

DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-2-9f4c6a7b1014> in <module>()
      1 import pystan
----> 2 sm = pystan.StanModel(model_code=open('prophet_linear_growth.stan').read())

F:\Anaconda2\envs\py33\lib\site-packages\pystan\model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    307 
    308         try:
--> 309             build_extension.run()
    310         finally:
    311             if redirect_stderr:

F:\Anaconda2\envs\py33\lib\distutils\command\build_ext.py in run(self)
    337 
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 
    341     def check_extensions_list(self, extensions):

F:\Anaconda2\envs\py33\lib\distutils\command\build_ext.py in build_extensions(self)
    446             self._build_extensions_parallel()
    447         else:
--> 448             self._build_extensions_serial()
    449 
    450     def _build_extensions_parallel(self):

F:\Anaconda2\envs\py33\lib\distutils\command\build_ext.py in _build_extensions_serial(self)
    471         for ext in self.extensions:
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 
    475     @contextlib.contextmanager

F:\Anaconda2\envs\py33\lib\distutils\command\build_ext.py in build_extension(self, ext)
    531                                          debug=self.debug,
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 
    535         # XXX outdated variable, kept here in case third-part code

F:\Anaconda2\envs\py33\lib\distutils\_msvccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    382                 self.spawn(args)
    383             except DistutilsExecError as msg:
--> 384                 raise CompileError(msg)
    385 
    386         return objects

CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I don't know the reason . could you help me fix this problem? thks a lot!

**Comment by dkzone000** [comment]
I have same problem...did you solve it ?

**Comment by bletham** [comment]
The issue seems to be upstream in pystan Windows not compiling models with matrix multiplication. This is being handled in #2 , I'm going to move this discussion to there.
