### ISSUE TITLE
No such file or directory "linear_growth.pkl"

### ISSUE THREAD

**Issue by Ram0987** [facebookincubator/prophet#222]
I'm quite new to Python and using Python 2.7.13 and got this error while trying to run the "Quick Start" program.
`IOError: [Errno 2] No such file or directory: u'C:\\Python27\\lib\\site-packages\\fbprophet\\stan_models\\linear_growth.pkl'`

Thanks

**Comment by bletham** [comment]
It seems that something may have failed during package installation, which is when that file should be created. What are you running to get this error?

**Comment by Ram0987** [comment]
I tried running this: [https://facebookincubator.github.io/prophet/docs/quick_start.html](url)

How to install fbprophet properly? - I'm currently using Python 2.7.13 
Thanks

**Comment by maskani-moh** [comment]
@Ram0987 

Take a look at the documentation [here](https://facebookincubator.github.io/prophet/docs/installation.html).

Since you are using Python, `pip install fbprophet` command should work.
Be sure however to have `pystan` already installed ([pystan installation](http://pystan.readthedocs.io/en/latest/installation_beginner.html)).

**Comment by Ram0987** [comment]
I have installed `pystan` and when I try to install `fbprophet` with this code,
`import pip`
`pip.main(["install","fbprophet"])`
I encounter this error

Please help me out.
Thanks

>  Collecting fbprophet
  Using cached fbprophet-0.1.1.tar.gz
Requirement already satisfied: matplotlib in c:\python2.7.13\lib\site-packages (from fbprophet)
Requirement already satisfied: numpy in c:\python2.7.13\lib\site-packages (from fbprophet)
Requirement already satisfied: pandas>=0.18.1 in c:\python2.7.13\lib\site-packages (from fbprophet)
Requirement already satisfied: pystan>=2.14 in c:\python2.7.13\lib\site-packages (from fbprophet)
Requirement already satisfied: python-dateutil in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: six>=1.10 in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pytz in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: functools32 in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: cycler>=0.10 in c:\python2.7.13\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\python2.7.13\lib\site-packages (from pystan>=2.14->fbprophet)
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... - \ | / - \ | / - \ | / - \ | error
    Complete output from command C:\Python2.7.13\pythonw.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-build-rmqjdn\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-xdnckk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_models
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_9c941523472e65f75f241e35a8769919 NOW.
    stanfit4anon_model_9c941523472e65f75f241e35a8769919_1332232302.cpp
    c:\python2.7.13\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
.
            C:\Users\User\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\math.h(519): or       'float log(float)'
            C:\Users\User\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\math.h(121): or       'double log(double)'
            while trying to match the argument list '(int)'
            C:\Python2.7.13\lib\site-packages\pystan\stan\lib\stan_math_2.15.0\stan/math/rev/scal/fun/gamma_q.hpp(26) : see reference to function template instantiation 'T stan::math::grad_reg_inc_gamma<double>(T,T,T,T,double,int)' being compiled
            with
            [
                T=double
            ]
    error: command 'C:\\Users\\User\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by maskani-moh** [comment]
@Ram0987 

You are under Windows. Have you followed the instruction commands indicated in the Installation section of Prophet?

Installation for windows: [here](https://github.com/facebookincubator/prophet#windows-1)

**Comment by Ram0987** [comment]
@maskani-moh ,  @bletham 
Thanks for your support friends... I finally Installed it
