### ISSUE TITLE
Pandas .ix indexer is deprecated

### ISSUE THREAD

**Issue by frexvahi** [facebookincubator/prophet#224]
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

When running fbprophet with a recent version of pandas, it gives DeprecationWarnings e.g. here
https://github.com/facebookincubator/prophet/blob/master/python/fbprophet/forecaster.py#L217

**Comment by maskani-moh** [comment]
It's only a `DeprecationWarning`, no big harm. 😄 
The `.ix` locator will eventually be removed in favor of `.loc` and `.iloc` in future (not for next ones) releases of `pandas`.

The implementation of `.ix` is currently 5% to 10% faster than that of `.loc` and `.iloc`.
Prophet uses `.ix` for indexing the dataframes. I think it's important to be able to access rapidly the values of your dataframes if you want to provide a fast forecasting tool.

Eventually, some refactoring in the implementation of `.loc` and `.iloc` will make them faster. At that time one might reconsider to switch to one of the two methods.
> Some refactoring or Cythonization may be able to give some quick perf wins in .loc or .iloc

Look at the [issue about the deprecation](https://github.com/pandas-dev/pandas/issues/14218).

For now, keeping`.ix` might be a reasonable choice, as it still works perfectly fine.

Any thoughts on that?

**Comment by bletham** [comment]
Thanks for pointing this out. It looks like we are using `ix` only in some of the initialization code and so it shouldn't be too difficult to pull it out, and wont' affect performance.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/047a0c3c23011a043da8f748de13b8da53b86f15 replaces `.ix` with `.iloc` as recommended in http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated.

**Comment by bletham** [comment]
Fixed in v0.2 on pypi.
