### ISSUE TITLE
Support hour or minute time series in Python？

### ISSUE THREAD

**Issue by 631068264** [facebookincubator/prophet#226]
`Prophet` is a good tool.  

But it only support daily data, do not support hour or minute timeseries in Python.
I hope `make_future_dataframe(freq=**)`  cat support [pandas timeseries](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)
which can make `Prophet` more perfect.

And I hope I can specific the datetime column name not only `ds`. Or just as the index.

**Comment by maskani-moh** [comment]
@631068264 

**Prophet** was originally thought as a tool to forecast **business time series** which present piece-wise trends, multiple seasonalities and which are affected by holidays. That's why frequencies are usually `days`, `months` or `years`.

What kind of time series are you dealing with?

**Comment by randlet** [comment]
Sub daily frequencies would be useful for us too.  @631068264 The way we currently handle this is roughly as follows:

1. Do our own modeling of intra day variations to generate an intra day weighting function
2. Aggregate our data to generate a daily average time series of the quantity of interest.
3. Use Prophet to predict daily trends based on 2)
4. Use the weighting function generated in 1) to interpolate the daily Prophet model generated in 3) on an hourly basis.

not sure if that helps or not or whether such an approach would work for you.

**Comment by 631068264** [comment]
This my raw data and I will use **date** and **close** as **ds** and **y**   and predict the next minute price  and I have different granularity such as **3min,15min,30min,1h,2h,6h,etc**.
```
    date                               close
0 2017-06-23 09:22:00  19737.14
1 2017-06-23 09:23:00  19750.00
2 2017-06-23 09:24:00  19750.00
3 2017-06-23 09:25:00  19755.00
4 2017-06-23 09:26:00  19750.00
```

**Comment by mraky** [comment]
@maskani-moh hi, you asked, qhy hourly/minutes... i.e have  router interface traffic data...  data are affected by hour, by weekends, by holidays  etc...  my motivation is to have some 'prediction' to triger alarm, if traffic profile is unusuall

**Comment by maskani-moh** [comment]
@mraky, unfortunately, **prophet** was not designed for this kind of time series but more for time series showing monthly/yearly seasonality as most of the business metrics would do.

@bletham maybe you could tell us if it is planned - or desired - to enlarge the scope of **prophet** to a more granular level. We could work then on a PR for this feature if it's the case! 💪

**Comment by bletham** [comment]
Finer-grained time data is the top feature priority, and one of my colleagues is working on it right now. I'd expect this to be ready pretty soon (a few weeks) unless we hit unexpected roadblocks. We'll make a new branch for it and will let you know as soon as it is ready to go.

**Comment by bletham** [comment]
See also #29

**Comment by huevosabio** [comment]
Hi,

Has this been implemented and added to the main branch?

**Comment by theonewolf** [comment]
I believe this is fully supported now, I am going to try using second granularity data: https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data

**Comment by iamshreeram** [comment]
@theonewolf , Did you get chance to use `second` granular data? Can you please share your thoughts or any repo?

@631068264 , I have similar use case as you. Did you find `prophet` compatible? what is your suggestion for `minute` level data?

**Comment by bletham** [comment]
This is now fully supported. See https://facebook.github.io/prophet/docs/non-daily_data.html#sub-daily-data for an example that uses data with 5-minute granularity, but everything is the same with second-levely granularity (or even irregular spacing).

**Comment by iamshreeram** [comment]
@bletham , I believe `future = m.make_future_dataframe(periods=5, freq='H')` provides 5 Hourly sample. Is there a way to calculate next minute data? 

Below is my `ds` and `y`
```
8/25/17 13:37:00 | 230
8/25/17 13:38:00 | 329
8/25/17 13:39:00 | 279
8/25/17 13:40:00 | 314
8/25/17 13:41:00 | 322
8/25/17 13:42:00 | 298
8/25/17 13:43:00 | 307
8/25/17 13:44:00 | 293
8/25/17 13:45:00 | 324
8/25/17 13:46:00 | 306
8/25/17 13:47:00 | 292
```
I would want to forecast below 
```
8/25/17 13:48:00 | 302
8/25/17 13:49:00 | 298
8/25/17 13:50:00 | 309
```

**Comment by bletham** [comment]
```
future = m.make_future_dataframe(periods=5, freq='min')
```
You can also look at
```
help(m.make_future_dataframe)
```
to see a description of what the inputs to any function are.

**Comment by theonewolf** [comment]
@iamshreeram we did some experiments with sub-daily (second) data, but paused those experiments awhile ago.  If I see any significant results or findings I will report them here.
