### ISSUE TITLE
Is there a way to export/reload trained model for reusing?

### ISSUE THREAD

**Issue by zoidburg** [facebookincubator/prophet#227]
Hi, usually I work with the following steps:
1.prepare data for training->2.train a model->3.evaluation->4.export model->5.reload model->6.predict
So is there an easy way to export/reload trained models? Didn't got it from the document.
Thanks~

**Comment by maskani-moh** [comment]
If you're under python, you can easily serialize your `forecaster` instance using [`pickle`](https://docs.python.org/2/library/pickle.html).

Do as follows:
```
import pickle

with open("your_path_to_pickle_the_forecaster", "w") as f:
     pickle.dump(my_forecaster, f)
```

To reload your forecaster, you can simply do:

```
with open("your_path_where_forecaster_pickled", "w") as f:
   my_loaded_forecaster = pickle.load(f)
```

Hope it helps!
Don't hesitate to come back to me if it does not work 😉

**Comment by zoidburg** [comment]
Thanks a lot~

**Comment by zoidburg** [comment]
write() argument must be str, not bytes
hmm， may you could try open file with "wb" flag rather than "w"

**Comment by ss2195** [comment]
thanks , actually I searched it and found the same solution
