### ISSUE TITLE
Pip install makes cc1plus to use 100% cpu

### ISSUE THREAD

**Issue by kumaranvpl** [facebookincubator/prophet#233]
I tried installing fbprophet globally using the command `sudo pip install fbprophet`.
This downloads the tar.gz but pip hangs after that.
Also it makes **cc1plus** system package to use ~100% cpu and ~34% memory in my laptop.
Trying to install fbprophet in a virtual environment also results in an error which is mentioned in this [issue](https://github.com/facebookincubator/prophet/issues/230).

**Comment by bletham** [comment]
During install, Stan is used to compile the models into binaries. This is what is happening when cc1plus is using up 100% CPU. There are two models that are compiled, and each one takes 1-2 minutes, so it is normal for it to be like this for several minutes. You only have to wait for this the one time during install.
