### ISSUE TITLE
Stationary and non-stationary timeseries

### ISSUE THREAD

**Issue by nikitagupta55** [facebookincubator/prophet#234]
Prophet works for any kind of dataset or not? By any kind I mean  that Input dataset to prophet should be Stationary time-series or it works on any kind of dataset?

**Comment by bletham** [comment]
Prophet works well on datasets that have piecewise trends and weekly/yearly seasonality. The examples [in the documentation](https://facebookincubator.github.io/prophet/docs/quick_start.html#python-api) are pretty typical of the types of time series that Prophet works well for, with strong, consistent seasonalities and trends that can reasonably be modeled with a piecewise function. The details of the model are given in [the paper](https://facebookincubator.github.io/prophet/static/prophet_paper_20170113.pdf). Does that help?

**Comment by manugupta1995** [comment]
I have the same doubt

**Comment by delislecl** [comment]
I don't think Prophet will work on non stationary series. It only models trend and seasonality (at different scales). So if working with non stationary series we will have to use methods to make the series stationary such as differentiation.

**Comment by bletham** [comment]
Non-stationarity in the trend would be find, since it anyway fits a piecewise trend. Non-stationarity in seasonality (i.e., changing seasonality from year to year) would not be fit by the model, unless it was due to a stationary but multiplicative effect.

**Comment by argku** [comment]
Suppose the true model is d Y(t) = a + beta*x(t) + e(t), where x(t) is a stationary exogenous regressor and e(t) is random error, and d Y(t) = Y(t) - Y(t-1). If you plug Y(t), and x(t) with add_regressors(), do you think it would work?

My regressors are stationary and dependent variable is not, will this method be able to handle it? If you had an option to specify differencing, then you could do fitting on d Y() then integrate back to Y(t).

**Comment by bletham** [comment]
@argku The model is
```
y(t) = trend(t) + seasonality(t) + beta * extra_regressor(t) + noise
```
so if Y(t) - a + beta*x(t) + e(t), then yes that would be well captured by the model. If extra_regressor(t) is stationary and y(t) is not, will it be able to capture it? It depends on what type of non-stationarity it is. trend(t) is non-stationary, so if a piecewise linear/logistic trend is sufficient to capture the nonstationarity then it will work. Otherwise (including if the non-stationarity is in seasonality(t)), it may not fit the time series well.
