### ISSUE TITLE
cannot import name 'Prophet'

### ISSUE THREAD

**Issue by Ram0987** [facebookincubator/prophet#237]
I have installed `fbprophet` in my windows system. When I tried to import it, 
( `from fbprophet import Prophet`), 
It is throwing an error: `cannot import name 'Prophet'` 

How to solve this issue?
Thanks

**Comment by rohitdeo90** [comment]
I'm also facing the same problem. What's the reason. Just before few minutes, it was running well. Suddenly it has started throwing this.
