### ISSUE TITLE
no valid constructor available for the argument list

### ISSUE THREAD

**Issue by jmrichardson** [facebookincubator/prophet#242]
Hello,

I got this error message in R:

> m <- prophet(df)
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Initial log joint probability = -77.992
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance

Is this an issue I should be concerned about?

**Comment by maskani-moh** [comment]
@jmrichardson 

Same issue raised in #132. Maybe it can help.

**Comment by mucun1988** [comment]
@jmrichardson i have encountered the same issue, but it seems to work without any problem... have you figured out the reason? @maskani-moh  #132 seems not very helpful after reading it through...

**Comment by mucun1988** [comment]
@jmrichardson  i think the error comes from the following piece of code from the tryCatch statement in the function get_prophet_stan_model().

**Comment by MansMeg** [comment]
I get the same error (on Travis). But it seems to work:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)
Matrix products: default
BLAS: /home/travis/R-bin/lib/R/lib/libRblas.so
LAPACK: /home/travis/R-bin/lib/R/lib/libRlapack.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] methods   stats     graphics  grDevices utils     datasets  base     
other attached packages:
[1] MarpleDetective_1.10.1 rstan_2.16.2           StanHeaders_2.16.0-1  
[4] ggplot2_2.2.1          Rcpp_0.12.11           rjags_4-6             
[7] coda_0.19-1            rjstat_0.4.2          
loaded via a namespace (and not attached):
 [1] codetools_0.2-15 lattice_0.20-35  grid_3.4.0       plyr_1.8.4      
 [5] jsonlite_1.5     gtable_0.2.0     backports_1.1.0  stats4_3.4.0    
 [9] scales_0.4.1     rlang_0.1.1      lazyeval_0.2.0   checkmate_1.8.3 
[13] munsell_0.4.3    compiler_3.4.0   inline_0.3.14    colorspace_1.3-2
[17] rstantools_1.2.0 gridExtra_2.2.1  tibble_1.3.3 
```

**Comment by bletham** [comment]
This might be related to http://discourse.mc-stan.org/t/new-cppobject-xp-no-valid-constructur-in-2-16/1192

Is everyone having this only inside Travis?

Can anyone tell where this error is being produced? If it is inside the tryCatch() then it should be re-compiling the model and taking several minutes, is that happening?

**Comment by bletham** [comment]
This must be related to the 2.16.2 release of rstan that happened last week since this is suddenly happening en masse. I've upgrade rstan to 2.16.2 but am not able to replicate this issue in Debian. If anyone can download the source, try the solutions in the mc-stan.org link above, and install the modified source to see if it works, that would be really helpful. In particular there is a reported success with adding some additional Makevars.

**Comment by bgoodri** [comment]
It is not that big a deal. Whenever the next release of prophet is uploaded to CRAN, it will be built against StanHeaders / rstan 2.16.x and the message will go away.

**Comment by nd7141** [comment]
I get similar errors on Windows, just installed the package. How can I resolve it? Is it possible to rollout to previous version of prophet? 

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
failed to create the optimizer; optimization not done
Error in matrix(m$params[[name]], nrow = n.iteration) : 
  'data' must be of a vector type, was 'NULL'
```

**Comment by bgoodri** [comment]
The first three lines of that message are not critical. The second two are unrelated and a different issue.

**Comment by bletham** [comment]
Thanks @bgoodri! @nd7141 could you open a separate issue for your error?

**Comment by bletham** [comment]
This should be resolved now that we pushed a new version to CRAN.
