### ISSUE TITLE
R: prophet() c++ exception error and warning

### ISSUE THREAD

**Issue by syphon5** [facebookincubator/prophet#243]
Running the R implementation on MacOSX.

`web_data_mutate <- rename(web_data, ds = date, y = sessions)`
`web_data_mutate <- web_data_mutate %>% mutate(y = log(y))`
`prophet(web_data_mutate)`

It creates the output, but prophet() throws the following error and warning message:

`Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  c++ exception (unknown reason)
In addition: Warning message:
In set_auto_seasonalities(m) :
  Disabling yearly seasonality. Run prophet with yearly.seasonality=TRUE to override this.
trying deprecated constructor; please alert package maintainer`

My data is simply daily dates and visits for the past two years.

**Comment by mucun1988** [comment]
same issue with #242?

**Comment by bletham** [comment]
This must be the same as #242, let's move the discussion there.
