### ISSUE TITLE
CDF / PMF of sum of forecast

### ISSUE THREAD

**Issue by 1mike12** [facebookincubator/prophet#244]
I apologize if this is too much of a tangent away from prophet but more a math question, but I think this could be relevant to many users of prophet. Is it possible using the models to answer questions like 

"From Jan1st to Jan30th, what's the probability the total # of events is over X?"
"Next week, what's the probability that we receive between 500 and 1000 orders?"

I know the future forecasts can come with confidence intervals, but is there any way to get a CDF of X, where X ~ sum of events from the forecast?

**Comment by mucun1988** [comment]
If issue #174 is fixed, I guess that would be very easy.  @1mike12

**Comment by 1mike12** [comment]
Ah thank you, didn't see that issue.
