### ISSUE TITLE
No module named 'stanfit4anon_model_77e4c4162fb1......

### ISSUE THREAD

**Issue by Ram0987** [facebookincubator/prophet#252]
I have installed both pystan and fbprophet successfully on my machine. But, When I give` import fbprophet`, It is showing an error:

`WARNING:pystan:No module named 'stanfit4anon_model_9c941523472e65f75f241e35a8769919_4289282227191412751' WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.`

`WARNING:pystan:No module named 'stanfit4anon_model_77e4c4162fb17d5855e6b726b68bdd0c_4498328616688083170' WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.`

I'm using:

PyStan Version: 2.15.0.1

Python Version: 3.6.1

Operating System: Windows 10

Please explain how to fix this. Thanks!

**Comment by Ram0987** [comment]
Sorry, but anybody knows why this is happening?

**Comment by bletham** [comment]
I wonder if this might be related to #249. Are you getting any other warnings or errors associated with this?

**Comment by Ram0987** [comment]
Thanks for the response. 
No, Just this one no other warnings or anything.

**Comment by Ram0987** [comment]
@bletham Hi, I reinstall MS Build tools and finally it worked. Thanks

**Comment by bletham** [comment]
Wonderful, thanks for the tip!
