### ISSUE TITLE
Feature Request: Return success/failure of model fitting (convergence)

### ISSUE THREAD

**Issue by peacej** [facebookincubator/prophet#255]
When calling predict(), would be great if somehow the success/failure of model fitting could be returned in addition to the predictions. This could be a column in the dataframe, or another variable, maybe a boolean. By "success" I mean when the Stan output shows "Optimization terminated normally: Convergence detected".  A failure would be something like "Optimization terminated with error:   Line search failed to achieve a sufficient decrease, no more progress can be made"

Returning this would allow the user to add handling logic for when failure happens (e.g. choose to not use the prediction at all).

**Comment by maskani-moh** [comment]
@peacej 

> Line search failed to achieve a sufficient decrease, no more progress can be made

This, in itself is **not an Error**. It would rather be a simple Warning.

What you want to know is if the L-BFGS has **reached the precision you indicate**, right? 

That's part of the optimization and does not mean that your **prediction** failed. When the optimization works, the prediction also works (no matter how good is the convergence).

How would you define the **failure** of your prediction? You'd like compare it to other benchmark models (ARIMA, ARMA ...)?

As for your optimization, you might experiment different parameters, like regularization, to optimize your model.

**Comment by bletham** [comment]
This would be good to include.

**Comment by peacej** [comment]
@maskani-moh You're right. I shouldn't have used the word "error". Sometimes the prediction is obviously way off when observed by a human and that's because there was not enough input data to fit the model. It would be nice to be able to some way indicate this when returning the result from the predict() function. Maybe an indication of precision reached would be one way.

**Comment by bletham** [comment]
That's somewhat related to #194 and #261, providing a convenient way to estimate forecast accuracy. This should be part of the next version.

**Comment by bletham** [comment]
The diagnostic functions included in v0.2 provide a way of estimating forecast error, as described here: https://facebookincubator.github.io/prophet/docs/diagnostics.html

I think that should resolve this issue but if it does not please reopen.
