### ISSUE TITLE
Can I make a PR for cross-validation of time series?

### ISSUE THREAD

**Issue by teramonagi** [facebookincubator/prophet#257]
It might be helpful for all *prophet* user to implement "rolling forecasting origin" type cross-validation for time series as the following link says:

- https://robjhyndman.com/hyndsight/tscv/
- https://en.wikipedia.org/wiki/Forecasting#Forecasting_accuracy

Should I implement it and make a pull request for the Prophet?

**Comment by maskani-moh** [comment]
@teramonagi 

FYI, the term used for cross-validating TS in [**BackTesting**](https://en.wikipedia.org/wiki/Backtesting).

**Feel free** to implement any feature you want and make a PR.

Your changes will be reviewed, discussed and eventually accepted or not ;)

**Comment by teramonagi** [comment]
OK, I'll give it a try :)
I know the word `BackTesting`, but it sounds like financial word.

**Comment by bletham** [comment]
This is great, thanks!

**Comment by Steviey** [comment]
How can I use this new feature?

**Comment by teramonagi** [comment]
It is not released yet.
If you want to use development version, run the following commands.
```
$ git clone -b v0.2 https://github.com/facebookincubator/prophet.git
$ cd prophet
$ pip install .
```

**Comment by Steviey** [comment]
Thank you. I would need the corresponding syntax in R for install and usage.

**Comment by bletham** [comment]
I'll add it to R in the next few days.

**Comment by teramonagi** [comment]
@bletham 
Let me know if you have any help!

**Comment by bletham** [comment]
This can now be installed in R using the devtools package:
```
devtools::install_github('facebookincubator/prophet', subdir='R', ref='v0.2')
```
It provides functions `cross_validation` and `simulated_historical_forecasts`. You can see the docstring for how to use the functions (`?cross_validation`). The output of both is a dataframe with actual values (`y`) and forecasted values (`yhat`) using a bunch of historical cutoff points. You can compare `y` and `yhat` to eachother using whichever error metric you'd like.

**Comment by bletham** [comment]
This is now in v0.2 on CRAN and pypi, with documentation here:
https://facebookincubator.github.io/prophet/docs/diagnostics.html

Thanks again!
