### ISSUE TITLE
Has prophet been adapted to discrete, non-integer type of series as X instead of ds?

### ISSUE THREAD

**Issue by liangtianumich** [facebookincubator/prophet#259]
I am thinking about whether it already has this implemented to make it more general? Thanks
Liang

**Comment by bletham** [comment]
Just to be clear, you mean having y as a function of something other than time?

The value of Prophet comes from modeling things like seasonality and holiday effects, which are pretty specific to time series.

**Comment by liangtianumich** [comment]
Yeah. I mean ds as a function of something other than time. Just exploring
the possibility whether Prophet can be extended to do something other than
time.

**Comment by bletham** [comment]
We haven't looked into an extension like that. The model is pretty specifically designed around time series and I'm a bit skeptical that it would be useful for general regression problems (for which there are a lot of really great methods), but if you have something in mind I'd love to hear it.
