### ISSUE TITLE
Initialization failed due to unknown causes

### ISSUE THREAD

**Issue by tle4336** [facebookincubator/prophet#262]
I was loading the attached dataset, and tried using FB Prophet to fit it. But then when I tried running the following code, it keeps giving me this error message: RuntimeError: Initialization failed. Don't really understand how this could happen;p Could you please help take a look?

`import datetime 

datapath = "./"
df = pd.read_csv(datapath+"CompleteOrder_HANOI_Alltime.csv") #FB requires y-variable
df = df.drop(df[df.completed_orders < 0].index)
df['y'] = np.log(df['completed_orders'])
df = df.drop('completed_orders', axis = 1)
df = df.drop('percent_completed', axis = 1)
df['ds'] = df['to_char']
df = df.drop('to_char', axis = 1)
df['ds'] = pd.to_datetime(df['ds'])
articles = pd.DataFrame({
  'holiday': 'publish',
  'ds': pd.to_datetime([ '2015 - 04 - 30', '2015 - 05 - 01', '2015 - 09 - 02',
                        '2016-04-30', '2016-05-01', '2016 - 02 - 06', '2016 - 02 - 07', '2016 - 02 - 08', 
                        '2016 - 02 - 09', '2016 - 02 - 10', '2016 - 02 - 11', '2016 - 02 - 12',
                        '2016 - 02 - 13', '2016 - 02 - 14', '2016-09-02', '2016 - 12 - 31',
                        '2017 - 01 - 01', '2017 - 01 - 02', '2017 - 01 - 26', '2017 - 01 - 27',
                        '2017 - 01 - 28', '2017 - 01 - 29', '2017 - 01 - 30', '2017 - 01 - 31',
                        '2017 - 02 - 01', '2017-04-30', '2017-05-01', '2017-09-02']),
  'lower_window': 0,
  'upper_window': 5,
})

m = Prophet(holidays=articles, mcmc_samples=1000, yearly_seasonality=True, changepoint_prior_scale = 0.04)
model = m.fit(df)

`

**Comment by bletham** [comment]
Could you post the full output of the error? Is it giving any sort of stacktrace?

It seems that something is wrong with the data being sent over to Stan. Is it possible for you to post a csv of `df` so I can replicate this?

**Comment by tle4336** [comment]
@bletham it happens at the line `model = m.fit(df)`. Attached is the csv.

**Comment by bletham** [comment]
Thanks! This dataset has several rows with completed_orders=0, which are turning into Inf when you take the log. Best to rectify those in same way (e.g. replace 0s with 1s). The current version on github checks for this and gives a useful error message instead of just erroring out, and will be pushed to pip soon!

**Comment by bletham** [comment]
This fix (better error message) has been pushed to CRAN and pypi in v0.2.
