### ISSUE TITLE
[Question] Weekly and Yearly Trends in the TS

### ISSUE THREAD

**Issue by gvyshnya** [facebookincubator/prophet#265]
Hi guys,

This is just a question, not a bug or feature request :-) (sorry if posting questions here is not good option to go).

I wonder if I can initialize Prophet modeller with both yearly and weekly seasonal trends on. Something like the case demonstrated in the Python code fragment below

`model = Prophet.Prophet(yearly_seasonality=True, weekly_seasonality=True)`

Will it impact the logic of Prophet forecasting? (provided my actual TS data does indicate both the short-term weekly seasonality and longer-term annual seasonality).

Thank you in advance.

George

**Comment by bletham** [comment]
Yes, `yearly_seasonality` and `weekly_seasonality` can be set to True exactly as you indicated to enable yearly and weekly seasonality. Their default values of 'auto' will enable yearly seasonality if there is >2 years of data, and weekly seasonality if there is >2 weeks of data and sub-weekly data frequency. If this is the case for your data then specifying them as True will not change anything.

**Comment by gvyshnya** [comment]
thanks, Ben - appreciated your explanations!
