### ISSUE TITLE
"Docs" link broken on tablet/mobile

### ISSUE THREAD

**Issue by samzhang111** [facebookincubator/prophet#267]
When you visit https://facebookincubator.github.io/prophet/ on tablet or mobile, the link to "Docs" in the expandable menu links to https://facebookincubator.github.io/docs/

On desktop it correctly links to https://facebookincubator.github.io/prophet/docs/

Hopefully this is the right place to file this issue..!

**Comment by seanjtaylor** [comment]
Resolved.
