### ISSUE TITLE
Forecasting Decline

### ISSUE THREAD

**Issue by JKPoynter** [facebookincubator/prophet#268]
The model is capable of forecasting growth where there is usually some maximum achievable value (a cap), but the same is true of decline where the will be some lower bound or floor. Is there a clean way of dealing with this scenario at present?

I guess as a work around I could subtract the input values from the max value in the time series, so that the "floor" becomes a "cap" but these feels a bit messy. 

Additionally there might be scenarios where there is both a floor and a cap.

**Comment by bletham** [comment]
This is in #81, and I think there is a fairly simple solution; check out the notebook pdf that I just attached there and post over there if you are able to try it out.

**Comment by JKPoynter** [comment]
Thanks perfect, of course the offset is a much better option!

**Comment by bletham** [comment]
This is now available in v0.2 in CRAN and pypi, documentation here:
https://facebookincubator.github.io/prophet/docs/saturating_forecasts.html
