### ISSUE TITLE
Error in new_CppObject_XP - "Please alert package maintainer"

### ISSUE THREAD

**Issue by robertdknight** [facebookincubator/prophet#269]
I just received this today when running scripts through R that worked normally.  It still produces the images.  It just says the following:

```
The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Initial log joint probability = -3.33041
Optimization terminated normally: 
  Convergence detected: relative gradient magnitude is below tolerance
```
Not sure what this means.

**Comment by bletham** [comment]
Thanks for the alert:-) This is discussed a bit in #242. tl;dr, everything is fine and you can safely ignore the message. The CRAN version just needs to be rebuilt against the updated StanHeaders, which will happen in a few weeks when we push a new version.
