### ISSUE TITLE
Missing tick in weekly forecast components plot (Python API)

### ISSUE THREAD

**Issue by Tafkas** [facebookincubator/prophet#27]
In the Python API, the first tick seems to be missing in the weekly forecast components plot. You can see this comparing the two images in the documentation:

 - Python API
     ![](https://facebookincubator.github.io/prophet/static/quick_start_files/quick_start_14_0.png)
     
- R API
    ![](https://facebookincubator.github.io/prophet/static/quick_start_files/quick_start_28_0.png)
    
The result is, that all other ticks move by one position, leaving the last one empty.

**Comment by bletham** [comment]
Fixed in #28 . Thanks!
