### ISSUE TITLE
How to install brach v2 to OS X ?

### ISSUE THREAD

**Issue by ofir887** [facebookincubator/prophet#277]

**Comment by reubenmc** [comment]
Are you using Python?

For Python, there are 3 steps.

1. Clone the repository to your local machine in terminal using **git clone https://github.com/facebookincubator/prophet.git**

2. Change the branch of the clone from master to v0.2. Navigate to where the prophet folder is and run **git checkout v0.2**. You can use **git branch -a** to make sure you are now on the v2 branch. 

3. Install the package. Navigate to prophet/python and run **python setup.py install**. This will install version 0.2. The version may still show up as 0.1.1 but you will have all the current features like `m.add_regressor`

**Comment by aydinhan** [comment]
You can also use **`pip`**:
`pip install git+git://github.com/facebookincubator/prophet@v0.2#subdirectory=python`

**Comment by bletham** [comment]
v0.2 has now been pushed to CRAN and pypi, so you can upgrade with `pip install`.
