### ISSUE TITLE
Optimization terminated with error:   

### ISSUE THREAD

**Issue by ashapattani** [facebookincubator/prophet#279]
[revenue_amount.zip](https://github.com/facebookincubator/prophet/files/1238418/revenue_amount.zip)
Hi,

    I was trying to make forecast using package prophet for the sample data attached  (revenue_amount.zip)

> qplot(Month,Amount, data=revenue_amount)
> 
> revenue_amount$Month = as.Date(revenue_amount$Month,"%m/%d/%Y")
> qplot(Month,Amount, data=revenue_amount)
> ds <- revenue_amount$Month
> y <- revenue_amount$
+ y <- revenue_amount$Amount
> y <- revenue_amount$Amount
> df <- data.frame(ds,y)
> qplot(ds, y, data = df)
> view(df)
> library(prophet)
m <- prophet(df)
Initial log joint probability = -2.77243
Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made
Warning messages:
1: In set_auto_seasonalities(m) :
  Disabling yearly seasonality. Run prophet with `yearly.seasonality=TRUE` to override this.
2: In set_auto_seasonalities(m) :
  Disabling weekly seasonality. Run prophet with `weekly.seasonality=TRUE` to override this.
3: In .local(object, ...) : non-zero return code in optimizing
> m <- prophet(df,yearly.seasonality=TRUE)
Initial log joint probability = -2.77243
Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made
Warning messages:
1: In set_auto_seasonalities(m) :
  Disabling weekly seasonality. Run prophet with `weekly.seasonality=TRUE` to override this.
2: In .local(object, ...) : non-zero return code in optimizing
> m <- prophet(df,yearly.seasonality=TRUE,weekly.seasonality=TRUE)
Initial log joint probability = -2.77243
Optimization terminated with error: 
  Line search failed to achieve a sufficient decrease, no more progress can be made
Warning message:
In .local(object, ...) : non-zero return code in optimizing

  Can someone pls let me know what is the exact issue.

**Comment by bletham** [comment]
This may be related to #200, could you try installing the latest from github just to be sure you have all of the bugfixes?
```
devtools::install_github('facebookincubator/prophet', subdir='R', ref='v0.2')
```
Also, from #200 for some time series the L-BFGS optimization seems to struggle and you might have success with a different optimizer. Try:
```
m <- prophet(df, algorithm='Newton')
```

**Comment by bletham** [comment]
The bugfixes mentioned above have been pushed to CRAN and pypi. Reinstall with `install.packages("prophet")` and if the issue persists please reopen.
