### ISSUE TITLE
A way to include accuracy to the plotted data?

### ISSUE THREAD

**Issue by arvindacumos** [facebookincubator/prophet#280]
Hello,

Am I correct that accuracy has been implemented to the new version? if yes, is there a way to include accuracy i.e. percentage to the plotted data?

TIA

**Comment by bletham** [comment]
The v0.2 branch currently has functionality for creating a dataframe with actual values `y` and forecasted values `yhat`, where the `yhat`'s are out-of-sample estimates using historical cutoff dates.

It is currently up to the user to apply an error metric to `y` and `yhat` and do any visualization of that. This would thought be great to have built-in. v0.2 will be pushed next week and I don't think this will make it by then, but hopefully soon after. Anyone can feel free to PR for this too, we can discuss what types of plots are likely to be useful.

**Comment by arvindacumos** [comment]
@bletham thanks will look at 0.2

**Comment by bletham** [comment]
The diagnostics in v0.2 have now been pushed to CRAN and pypi, and are documented here:
https://facebookincubator.github.io/prophet/docs/diagnostics.html
We do still need to add actual error metrics and visualizations. I'm going to keep that in #194.
