### ISSUE TITLE
c++ exception(unknown reason) when use prophet

### ISSUE THREAD

**Issue by xinai57** [facebookincubator/prophet#291]
When I use prophet, the example:

```
history <- data.frame(ds = seq(as.Date('2015-01-01'), as.Date('2016-01-01'), by = 'd'),
                      y = sin(1:366/200) + rnorm(366)/10)
m <- prophet(history)
```

I get the following in my console:

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  c++ exception (unknown reason)
```

but the model is fitted successfully.

**Comment by bletham** [comment]
Thanks, this is the issue from #242 which basically was that our CRAN version needed to be rebuilt against an update of rstan. It didn't actually break anything or have any negative effects, just the strange message. We have now pushed a new version (v0.2) to CRAN and so if you re-install prophet from CRAN you will no longer get that message.
