### ISSUE TITLE
Missing R Prophet Functions

### ISSUE THREAD

**Issue by gmikels** [facebookincubator/prophet#294]
I've installed the "prophet" package from CRAN and appear to be missing functions that are in the CRAN documentation, like get_changepoint_matrix(). Only four functions appear to be included: fit.prophet, make_future_dataframe, prophet, and prophet_plot_components. I believe the version I have is the most up to date (prophet_0.1.1). Please advise

![image](https://user-images.githubusercontent.com/9043244/30184693-7ae8acc0-93e4-11e7-8034-d4f5afb762e7.png)

![image](https://user-images.githubusercontent.com/9043244/30184759-b0d61a02-93e4-11e7-8cd7-5f16a97433b3.png)

**Comment by bletham** [comment]
Basically not all functions in a package are exported (made available after `library`). The pdf documentation on CRAN has been updated to include only exported functions. Documentation for not-exported functions is still available in their docstrings (with `?`). To access a not-exported function, you use `prophet:::`, like `prophet:::plot_weekly(m)`

In addition to the four functions you list, we use the generic `plot` and `predict` functions - this is now reflected in the documentation pdf on CRAN.
