### ISSUE TITLE
When i run pip3 install --user hg+http://bitbucket.org/pygame/pygame, i meet a issue as follows. Who can help me?Thanks

### ISSUE THREAD

**Issue by XKC1025** [facebookincubator/prophet#295]
xkc@ubuntu:~/桌面/A$ pip3 install --user hg+http://bitbucket.org/pygame/pygame
Collecting hg+http://bitbucket.org/pygame/pygame
  Cloning hg http://bitbucket.org/pygame/pygame to /tmp/pip-15gxaath-build
    Complete output from command python setup.py egg_info:
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "freetype-config" failed!
    SDL     : found 1.2.15
    FONT    : found
    IMAGE   : found
    MIXER   : found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: found
    PORTTIME: found
    FREETYPE: not found
    Missing dependencies
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-15gxaath-build/

**Comment by bletham** [comment]
This doesn't seem to be related to our package, but best of luck getting it to work.
