### ISSUE TITLE
AttributeError: 'Prophet' object has no attribute 'add_regressor'

### ISSUE THREAD

**Issue by lmsanch** [facebookincubator/prophet#306]
```
def nfl_sunday(ds):
    date = pd.to_datetime(ds)
    if date.weekday() == 6 and (date.month > 8 or date.month < 2):
        return 1
    else:
        return 0
df['nfl_sunday'] = df['ds'].apply(nfl_sunday)

m = Prophet()
m.add_regressor('nfl_sunday')
m.fit(df)

future['nfl_sunday'] = future['ds'].apply(nfl_sunday)

forecast = m.predict(future)
m.plot_components(forecast);
```
Returns

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-38bdc63ee11f> in <module>()
      8 
      9 m = Prophet()
---> 10 m.add_regressor('nfl_sunday')
     11 m.fit(df)
     12 

AttributeError: 'Prophet' object has no attribute 'add_regressor'

**Comment by bletham** [comment]
Merge with #304
