### ISSUE TITLE
Group by and use an aggregation

### ISSUE THREAD

**Issue by blahster** [facebookincubator/prophet#32]
`fit` fails if there is more than one record with the same timestamp.
Could you add an optional user-supplied aggregation function that could be applied on a `group by` instead?

**Comment by bletham** [comment]
Conceptually we can handle multiple observations on a day as coming from the noise term, but could you give some context for the application that you have in mind?

**Comment by blahster** [comment]
The system I'm working on captures transactions end of day and the timestamp is truncated to just the date. So, if there are more than one, I'd typically just take the mean and go with it.

The thing is, Prophet's error message is not easily interpreted as this problem. It just says,
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'slice'

Perhaps, a more user-friendly error message could help to begin with..

**Comment by korymath** [comment]
Thank you for capturing the duplicate error @xhesc. I have a similar use case. I am projecting ticket sales, but on some evenings we have more than one show, and thus more than one entry for a given date. In this case a mean doesn't make as much sense and grouping by date (day, week, month) would make more sense.

**Comment by bletham** [comment]
The latest commit should fix the issue with not allowing multiple observations on a date. Could you install the Github version and check if it works for you?

The model now treats multiple observations on a day similar to how a linear regression would. We do assume homoscedastic noise, which here means that the variance in the values for a single day is constant. @korymath I can imagine in your application there would be a difference in variance from weekdays vs. weekends, but if you sum sales in a day then I'd think weekly seasonality should capture that nicely.

Now that repeated observations aren't a problem, I'm inclined to leave other aggregations as a data pre-processing step that would be taken care of outside of Prophet.

**Comment by korymath** [comment]
I think you are right. Nice job with the fix and I agree that data pre-processing can help other cases. Great work.

**Comment by korymath** [comment]
Looks good python wise, didn't test R.
Great work on commit: https://github.com/facebookincubator/prophet/commit/443d475468f7425fecf6011d0bdf35b89c508694
