### ISSUE TITLE
Two rows with same date object throws issue

### ISSUE THREAD

**Issue by korymath** [facebookincubator/prophet#36]
--------------------------------------------------------
TypeError              Traceback (most recent call last)
<ipython-input-27-8f3f2f0741f4> in <module>()
      1 m = Prophet()
----> 2 m.fit(df);

/Users/korymathewson/anaconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in fit(self, df)
    340 
    341         self.set_changepoints()
--> 342         A = self.get_changepoint_matrix()
    343         changepoint_indexes = self.get_changepoint_indexes()
    344 

/Users/korymathewson/anaconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in get_changepoint_matrix(self)
    191 
    192     def get_changepoint_matrix(self):
--> 193         changepoint_indexes = self.get_changepoint_indexes()
    194 
    195         A = np.zeros((self.history.shape[0], len(changepoint_indexes)))

/Users/korymathewson/anaconda2/lib/python2.7/site-packages/fbprophet/forecaster.pyc in get_changepoint_indexes(self)
    184                 # the historical data.
    185                 indexes.append(row_index.get_loc(cp))
--> 186             return np.array(indexes).astype(np.int)
    187 
    188     def get_changepoint_times(self):

TypeError: long() argument must be a string or a number, not 'slice'

**Comment by korymath** [comment]
Seems to be happening when there are two rows for a given date

**Comment by xhesc** [comment]
Related: #32

**Comment by bletham** [comment]
The latest commit fixes this issue. Could you install from Github and make sure it is working for you?

**Comment by Coriou** [comment]
Hey @bletham, had the same error and installing the latest version from Github did indeed fix this error. Thank you
