### ISSUE TITLE
Duplicate holiday dates produces an error

### ISSUE THREAD

**Issue by wjhrdy** [facebookincubator/prophet#37]
With a large list of holidays I've found that there will be accidents with the manual creation process. It is helpful if the error message tells you what is wrong instead of giving you an error that doesn't mean anything.

If you run this:
```
library(prophet)
data = read.csv("https://raw.githubusercontent.com/facebookincubator/prophet/master/R/tests/testthat/data.csv")

holidays <- data_frame(
  holiday = 'duplicate',
  ds = as.Date(c("2012-05-18", "2012-05-18")),
  lower_window = 0,
  upper_window = 0
)

prophet(data, holidays = holidays)
```

This is the error:
```
Error in seq.default(.$lower_window, .$upper_window) : 
  'from' must be of length 1
```

A fix would be to check for duplicate dates and throw an error that says there are redundant holiday dates.

**Comment by bletham** [comment]
Thanks, since this was working in Python I went ahead and made a commit that fixes it in R. If you install from github it should work for you.
