### ISSUE TITLE
Unable to fit model: absolute parameter change was below tolerance

### ISSUE THREAD

**Issue by dstaley** [facebookincubator/prophet#40]
When attempting to run `Prophet().fit(df)`, I receive the following error:

```
           ds     y
0  2014-04-01    47
1  2014-05-01    94
2  2014-06-01    93
3  2014-07-01   277
4  2014-08-01   195
5  2014-09-01   190
6  2014-10-01   649
7  2014-11-01   584
8  2014-12-01  1440
9  2015-01-01   607
10 2015-02-01  1272
11 2015-03-01   637
12 2015-04-01   414
13 2015-05-01  1151
14 2015-06-01   555
15 2015-07-01   134
16 2015-08-01   455
17 2015-09-01   617
18 2015-10-01   744
19 2015-11-01  1310
20 2015-12-01  2849
21 2016-01-01   657
22 2016-02-01  1684
23 2016-03-01  1096
24 2016-04-01   155
25 2016-05-01   223
26 2016-06-01   152
27 2016-07-01   205
28 2016-08-01   255
29 2016-09-01   301
30 2016-10-01   141
31 2016-11-01    71
32 2016-12-01   680
33 2017-01-01   378
34 2017-02-01   118
STAN OPTIMIZATION COMMAND (LBFGS)
init = user
save_iterations = 1
init_alpha = 0.001
tol_obj = 1e-12
tol_grad = 1e-08
tol_param = 1e-08
tol_rel_obj = 10000
tol_rel_grad = 1e+07
history_size = 5
seed = 1749226207
initial log joint probability = -3.26242
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
      99       53.3753    0.00233329       77.8508      0.6097      0.6097      146
     156       54.4942   0.000250196        95.193   2.407e-06       0.001      264  LS failed, Hessian reset
     199       54.5156   2.51015e-07       85.6303      0.3645      0.3645      321
     219       54.5157   9.72858e-09       72.2706      0.3959      0.3959      346
Optimization terminated normally:
  Convergence detected: absolute parameter change was below tolerance
```

From what I can tell, this is an error from the R package [gmo](https://github.com/stan-dev/gmo). However, I'm not familiar enough with the underlying statistics to understand what exactly about my data is causing the issue.

**Comment by bletham** [comment]
It looks like there wasn't an error, rather this is a normal end of the optimization because it has found the best fit. If you make predictions and plot does it seem reasonable?

**Comment by dstaley** [comment]
Ah, from the examples I wasn't aware that I needed to output the plot myself. Since there was no output besides the previous, I figured it was an error.

This is how I'm outputting the graphs.
```python
model = Prophet().fit(df)
future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)
figure = model.plot(forecast)
figure.savefig('output')
```

**Comment by pldeepesh** [comment]
I was wondering what does the LS Failed and Hessian Reset mean. Does that mean the model is working? when I have predicted this data the data seemed more than reasonable, it was pretty much accurate. But I am unable to understand what this means <h3>LS Failed and Hessian Reset</h3>

**Comment by bletham** [comment]
The L-BFGS optimization algorithm uses an approximate Hessian that is calculated from the results of the past few iterations. It is then used to do a line search in the descent direction. Sometimes this approximation can become poor, and the line search fails (fails to find an improvement in the descent direction). When this happens, the approximate Hessian is reset which typically fixes the issue. In situations like the one in the first post here, we can see that after the Hessian reset, the optimization continued to progress and so there is nothing to worry about then. Generally I would not worry about this note, especially if it reports that the optimization terminated normally.
