### ISSUE TITLE
predict is recompiling stan model each time

### ISSUE THREAD

**Issue by cprosser** [facebookincubator/prophet#42]
The pre-compiled model from CRAN doesn't work on my machine. Forcing a recompilation every time prophet() is called. I'm on windows x64.

I stepped through the loading code, and it was all working, but stanm@mk_cppmodule(stanm) always threw an error. This could be because I have my stan compiler default set to -O3 (and the module was compiled with -02). Not sure. 

Most importantly, uninstalling the package, then re-installing from source fixed it all up. Maybe windows binary packages don't work great? Probably worth a line of documentation. Much faster now :).

**Comment by seanjtaylor** [comment]
@cprosser yes you caught a very ugly hack that we used for Windows.  Looks like we should advise source installs on Windows for now.  Thanks for reporting!  I'm going to leave this bug open until we know how to solve the Windows problem.

**Comment by bletham** [comment]
I tried this in a fresh install on windows 10 x64 and didn't run into this issue, it probably is due to your non-default stan settings. We should mention this in the install instructions.

**Comment by bletham** [comment]
Documentation updated in https://github.com/facebookincubator/prophet/commit/aabb7e0547aeba2d761b728b0fd07577734e1e36. Thanks!
