### ISSUE TITLE
R: Weekday Plot fails on non-English locales

### ISSUE THREAD

**Issue by heidekrueger** [facebookincubator/prophet#45]
In `prophet_plot_components`, the following snippet for the weekly seasonality plot fails on non-english locales:

`df.s <- df %>% dplyr::mutate(dow = factor(weekdays(ds), 
      levels = c("Sunday", "Monday", "Tuesday", "Wednesday", 
        "Thursday", "Friday", "Saturday")))`

This produces `NA` for all weekdays due to the hardcoding of factor names.

As a result no useful weekday plot is created.

![image](https://cloud.githubusercontent.com/assets/9562632/23401960/ebd024a8-fda9-11e6-878a-8ac6fc492442.png)

**Comment by seanjtaylor** [comment]
@heidekrueger Thanks for the bug report!  We definitely hadn't tested with other locales, so this is valuable to know.  We can get this fixed up pretty easily.

**Comment by alain2208** [comment]
saw the same with R on French Windows

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/5cec062fced05dcba0e62e737a028a9f03ca355f fixes this. Can you install from Github and check that it is working for you?
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```

![weekly_locales](https://cloud.githubusercontent.com/assets/6339760/23470275/a94215dc-feae-11e6-8eb1-b7565b158541.png)

**Comment by heidekrueger** [comment]
I can confirm that it's working now for me, after installing the latest head. (German locale)

Thanks for the quick fix!
