### ISSUE TITLE
Sample-data suggestion in quick start no longer works

### ISSUE THREAD

**Issue by smach** [facebookincubator/prophet#47]
FYI the suggestion in this package's [quick start docs](https://facebookincubator.github.io/prophet/docs/quick_start.html) to use the R wikipediatrend package for downloading Wikipedia pageview data doesn't seem to work anymore. That package depends on  stats.grok.se, which is now showing an internal server error, and the [Wikipedia analytics tools page](https://en.wikipedia.org/wiki/Wikipedia:Pageview_statistics#Pageviews_Analysis) says it's been deprecated. It might be better to suggest people download data from the current Wikipedia analytics tool at [tools.wmflabs.org](https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-20&pages=Cat|Dog).

**Comment by bradfox2** [comment]
It still works.  
`wikipediatrend::wp_set_cache_file("data/test.csv")
wikipediatrend::wp_trend(page = "Dogs","2015-01-01", Sys.Date())`

**Comment by seanjtaylor** [comment]
Looks like this was just unfortunate timing!
