### ISSUE TITLE
Which other dependencies for Python+Linux?

### ISSUE THREAD

**Issue by mcnemesis** [facebookincubator/prophet#48]
Am following the instructions in the official docs, and had all the mentioned deps in place to install fbprophet in my virtualenv (see screen below):

![The Error](https://s30.postimg.org/3xws8jgqp/pip_fbprophet_error.png)

But apparently, there seem to be some other (OS-specific?) dependencies one might need to have in place, so as to finally successfully install the package. It's rather annoying, because the package deps-check indicated all other deps are satisfied, but during the build, possibly around pystan phase, the build fails, and the error seems to indicate there's some other package - possibly a library package, that's required for the build to work.

So, for those who have gotten this to work on a vanilla Debian, which other packages did you have to install? 

Note: I've already tried to install python-dev, build-essentials, libxml2-dev and libxslt1-dev. But none of these seem to solve this. I hate having to just follow blind-install workarounds as some popular SO answers for such scenarios recommend. So, what do we do?

**Comment by bletham** [comment]
I'm on vanilla Debian (testing) and I don't think I have any special packages installed. Can you verify that pystan is working?
```
>>> import pystan
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)
>>> y = model.sampling(n_jobs=1).extract()['y']
>>> y.mean()  # with luck the result will be near 0
```
I'm wondering if it could be something like this: https://github.com/stan-dev/pystan/issues/207

**Comment by mcnemesis** [comment]
First, concerning the pystan-issue you linked to; the eventual solution to that thread involved ensuring that Cython was >=0.22 (mine is Cython==0.25.2), and that both Cython and Pystan were installed via pip. I've installed both via pip, and have pystan==2.14.0.0. Yet, even with this, the problem persists.

But, when I attempt to run your sample code, it fails at the 3 step:

![image](https://cloud.githubusercontent.com/assets/445723/23414272/653eeb66-fdec-11e6-8534-86c1982acfb3.png)

Note: the error is the same as that I was getting when running PIP above!

When I checked the logs during the running of your provided code-snippet, I noticed that it  got stuck at this step for a while...

> INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.

And so made me think there might be issues with memory or something... So, I went to look at my memory usage (while that line continued running), and on my VPS, this processed seemed to be the one consuming the most memory:

> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nemesis+ 41377 31.1 72.4 1355292 1243220 pts/2 D+   16:24   0:46 /usr/lib/gcc/x86_64-linux-gnu/5/cc1plus -quiet -I /tmp/tmpeqBpLN -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan/stan/src -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan/stan/lib/stan_math_2.14.0 -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan/stan/lib/stan_math_2.14.0/lib/eigen_3.2.9 -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan/stan/lib/stan_math_2.14.0/lib/boost_1.62.0 -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/pystan/stan/lib/stan_math_2.14.0/lib/cvodes_2.9.0/include -I /home/nemesisfixx/labs/prophet/env/local/lib/python2.7/site-packages/numpy/core/include -I /usr/include/python2.7 -imultiarch x86_64-linux-gnu -D_GNU_SOURCE -D_REENTRANT -D NDEBUG -D _FORTIFY_SOURCE=2 -D BOOST_RESULT_OF_USE_TR1 -D BOOST_NO_DECLTYPE -D BOOST_DISABLE_ASSERTS /tmp/tmpeqBpLN/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7653448178952472436.cpp -quiet -dumpbase stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7653448178952472436.cpp -mtune=generic -march=x86-64 -auxbase-strip /tmp/tmpeqBpLN/tmp/tmpeqBpLN/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7653448178952472436.o -g -g -O2 -O2 -Wall -Wstrict-prototypes -Wdate-time -Wformat=1 -Werror=format-security -Wno-unused-function -Wno-uninitialized -fwrapv -fno-strict-aliasing -fstack-protector-strong -fPIC -ftemplate-depth=256 -fstack-protector-strong -Wformat-security -o /tmp/ccIpjIZM.s


Am just hypothesizing, but it could be that a lack of sufficient memory could cause the building of the model to fail? Am not at all experienced with Pystan or Stan itself, and so, I might be going over the edge here, but someone more experienced could help look more into this.

Note: am running this on a "micro" server via Microsoft's Azure cloud, with just 1GB of RAM. So, perhaps that is a show-stopper?

**Comment by mcnemesis** [comment]
Memory!

I increated the memory of the vm to 3.5G, and when I run the code sample, am now able to finish the entire demo... [@bletham mean is 0.011148514562947815 ;-) ]

Also, the installation now works effortlessly. So, clearly, having enough RAM seems to be a hidden /implicit requirement here. How much is enough? The experts can tell us, but in my case, the above solved this.

What's not clear now, is how much more RAM I might need when using the lib itself -- but, that's kind obvious - bigger workloads, more memory sir!
