### ISSUE TITLE
ValueError: Changepoints must fall within training data

### ISSUE THREAD

**Issue by keyunluo** [facebookincubator/prophet#5]
I try to fit the dataframe, but got ValueError, how to avoid this?

shop_2
Out[91]: 
             ds      y
358  2016-06-18   71.0
359  2016-06-19   45.0
360  2016-06-20   62.0
361  2016-06-21   52.0
362  2016-06-22   76.0
363  2016-06-23   68.0
364  2016-06-24   63.0
365  2016-06-25  106.0
366  2016-06-26   64.0
367  2016-06-27   68.0
368  2016-06-28   58.0
369  2016-06-29   53.0
370  2016-06-30   46.0
371  2016-07-01   55.0
372  2016-07-02   55.0
373  2016-07-03   75.0
374  2016-07-04   54.0
375  2016-07-05   55.0
376  2016-07-06   57.0
377  2016-07-07   54.0
378  2016-07-08   94.0
379  2016-07-09   83.0
380  2016-07-10   77.0
381  2016-07-11   59.0
382  2016-07-12   59.0
383  2016-07-13   57.0
384  2016-07-14   57.0
385  2016-07-15   57.0
386  2016-07-16   62.0
387  2016-07-17   60.0
..          ...    ...
464  2016-10-02  110.0
465  2016-10-03  102.0
466  2016-10-04   90.0
467  2016-10-05  121.0
468  2016-10-06   93.0
469  2016-10-07   90.0
470  2016-10-08   70.0
471  2016-10-09   77.0
472  2016-10-10   68.0
473  2016-10-11   68.0
474  2016-10-12   63.0
475  2016-10-13   56.0
476  2016-10-14   71.0
477  2016-10-15  119.0
478  2016-10-16   97.0
479  2016-10-17   75.0
480  2016-10-18   59.0
481  2016-10-19   71.0
482  2016-10-20   88.0
483  2016-10-21  103.0
484  2016-10-22  127.0
485  2016-10-23  125.0
486  2016-10-24   47.0
487  2016-10-25   80.0
488  2016-10-26   61.0
489  2016-10-27   68.0
490  2016-10-28  103.0
491  2016-10-29  102.0
492  2016-10-30  104.0
493  2016-10-31   67.0

[136 rows x 2 columns]

In [92]: m.fit(shop_2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-92-c290c6fd45ff> in <module>()
----> 1 m.fit(shop_2)

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in fit(self, df)
    339         seasonal_features = self.make_all_seasonality_features(history)
    340 
--> 341         self.set_changepoints()
    342         A = self.get_changepoint_matrix()
    343         changepoint_indexes = self.get_changepoint_indexes()

/usr/local/lib/python3.5/dist-packages/fbprophet/forecaster.py in set_changepoints(self)
    159                 too_high = max(self.changepoints) > self.history['ds'].max()
    160                 if too_low or too_high:
--> 161                     raise ValueError('Changepoints must fall within training data.')
    162         elif self.n_changepoints > 0:
    163             # Place potential changepoints evenly throuh first 80% of history

ValueError: Changepoints must fall within training data.

**Comment by walterreade** [comment]
I experienced this when I fit a model, and then fit the same instantiated model object on a different slice of the data. When I created a new model instantiation, the problem went away.
