### ISSUE TITLE
holiday label error

### ISSUE THREAD

**Issue by niklosb** [facebookincubator/prophet#50]
If you label a holiday with an underscore it causes an error in parsing. "promo_100" and "promo_150" will be sliced to "promo" and only one will be evaluated.

Causes plotting error when you plot components

**Comment by seanjtaylor** [comment]
Bummer!  Thanks for reporting @niklosb.  I think we're relying on underscores as a separator but that's pretty easy to fix.

**Comment by bletham** [comment]
https://github.com/facebookincubator/prophet/commit/4b7a41812167aa440b8294698ba9e94dccc5231b fixes this, can you install from Github and make sure it is working for you?

**Comment by niklosb** [comment]
Works! Thanks
