### ISSUE TITLE
Minimum pystan version

### ISSUE THREAD

**Issue by rolando** [facebookincubator/prophet#53]
The setup.py file declares the minimum version as `pystan>=2.8`. However, with that version I get the following error:

```
ValueError: Failed to parse Stan model 'anon_model_35bf14a7f93814266f16b4cf48b40a5a'. Error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Illegal statement beginning with non-void expression parsed as
  gamma[i]
Not a legal assignment, sampling, or function statement.  Note that
  * Assignment statements only allow variables (with optional indexes) on the left;
    if you see an outer function logical_lt (<) with negated (-) second argument,
    it indicates an assignment statement A <- B with illegal left
    side A parsed as expression (A < (-B)).
  * Sampling statements allow arbitrary value-denoting expressions on the left.
  * Functions used as statements must be declared to have void returns


ERROR at line 33

 32:      for (i in 1:S) {
 33:        gamma[i] = -t[s_indx[i]] * delta[i];
            ^
 34:      }

PARSER EXPECTED: "}"
```

Digging further the operator ``=`` has been introduced in ``v2.10.0`` release. See https://github.com/stan-dev/stan/blob/develop/RELEASE-NOTES.txt#L141

I think prophet should either state ``pystan>=2.10.0`` as requirement or fix the assignment operator to be ``<-``. I'd say the former option is better looking forward as ``<-`` is actually deprecated in latest ``pystan`` releases.

**Comment by seanjtaylor** [comment]
Good catch @rolando.  We'll get on this.

**Comment by lgaliano** [comment]
@seanjtaylor: Also observed the same thing on the R side with rstan = 2.9.x. Updating to latest 2.14.1 resolved the issue.

**Comment by bletham** [comment]
I added the requirement in https://github.com/facebookincubator/prophet/commit/20aca85bbbd475b0bf6f422aaa5d49c473972c89. I set it at 2.14 since the MCMC sampler was broken from Stan 2.9 through 2.13, so they are recommending everyone to update to 2.14 (https://github.com/stan-dev/cmdstan/releases).
