### ISSUE TITLE
Possible licensing issue re: BSD vs GPL

### ISSUE THREAD

**Issue by MarkEdmondson1234** [facebookincubator/prophet#55]
Hi, looks like a great package, planning on using it.  However, just wanted to give you a heads-up about possible licensing issues that a colleague bought up:

"The package is based on Stan and Rstan (+PyStan). Prophet claims it is under a 3-clause BSD licence. While Stan itself also uses a BSD licence, RStan and Pystan use GPLv3 licences. GPL licences require all derived work to be also GPL licensed. It may be possible to claim it's a linking scenario but I'm not sure whether that's the case or if the claim holds at all."

**Comment by seanjtaylor** [comment]
Hey Mark,

Thanks for your feedback.  We can't respond to legal inquiries through github issues but I will pass this on to our legal team.
