### ISSUE TITLE
Clarification on how prophet deals with weekly data (holidays)

### ISSUE THREAD

**Issue by azmorley** [facebookincubator/prophet#59]
Hi,

My data is weekly (Mondays), and I've been using a holidays dataframe like so:

```
BlackFridays <- data_frame(
  holiday = 'BlackFriday',
  ds = as.Date(c('2007-11-26', '2008-12-01', '2009-11-30', '2010-11-29', '2011-11-28', '2012-12-10', 
                  '2013-12-02', '2014-11-28', '2015-11-27', '2016-11-25', '2017-11-24')),
  lower_window = 3,
  upper_window = 3
)
```

When I set the lower/upper windows, for my weekly data would this be the number of weeks either side, or would it be the number of days still? Does it make any difference if the holiday dates are Mondays (same as  my weekly data) or on other days? Just trying to get to grips with how Prophet actually sees and deals with weekly data.

Thanks

**Comment by bletham** [comment]
If you have a holiday (or holiday+offset) that doesn't show up in your data, then Prophet will not be able to fit its coefficient in the model and the predictions moving forward could be bad. (This is similar to the challenge with yearly seasonality and monthly data that is described in the documentation). Reducing the `holiday.prior.scale` would help force these towards 0.

Ideally Prophet should automatically 0 coefficients for holidays that don't show up in the training data.

**Comment by azmorley** [comment]
Thanks for this.

In terms of the lower/upper windows, when using weekly data do these refer to a number of days or a number of weeks either side?

**Comment by bletham** [comment]
It's the number of days. To get e.g. holiday+1week, you would need to define it separately in your holidays dataframe.

**Comment by azmorley** [comment]
Ah ok then, thanks for the clarification.
