### ISSUE TITLE
Python plot methods should accept axes arguments

### ISSUE THREAD

**Issue by lemonlaug** [facebookincubator/prophet#62]
Plot methods should accept axes arguments so the plots generated by that code can be flexibly plotted in alternative layouts.

The [Pandas Series plot method](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.plot.html) is a good example of how this could work (it generates an axes if none is provided.

**Comment by seanjtaylor** [comment]
Another great point.  Also filing this under a 0.2 release enhancement.

**Comment by lemonlaug** [comment]
#84
