### ISSUE TITLE
Python plotting methods should return Artist objects instead of Figure.

### ISSUE THREAD

**Issue by lemonlaug** [facebookincubator/prophet#63]
Per the matplotlib [recommended function signature](http://matplotlib.org/faq/usage_faq.html) here, it is best to return `Artist` objects from plotting functions so that user-defined matplotlib functions have the same behavior as built-in functions like `ax.plot` which returns a list of Artists.

**Comment by seanjtaylor** [comment]
Hey @lemonlaug! Thanks for pointing this out.  I'm adding this as an enhancement for the 0.2 release, but you can feel free to submit a pull request if it's a quick fix.
