### ISSUE TITLE
fit error

### ISSUE THREAD

**Issue by dhdsjy** [facebookincubator/prophet#65]
I have installed the prophet for python in Linux, but when i use the command
 m = Prophet()
 m.fit(df);
there is a error as follow:
AttributeError: StanModel instance has no attribute 'fit_class'

can you tell me the cause?Please

**Comment by seanjtaylor** [comment]
Can you provide more details:

- what platform / Python version?
- what PyStan version?
- provide a csv for your dataframe or describe the data.
- does another csv file (e.g. the example we provide) display the same issue?

**Comment by simonb83** [comment]
Hi Sean, I am having the same issue although I am on Mac (El Capitan 10.11.4)

I am using:
- Anaconda 3 / python3.5
- pystan (2.14.0.0)

This happens both with my own data and also with all of the test examples provided.

My test data is pretty simple and has a simple data column and an integer:
````
 	y 	ds
0 	5 	2015-08-01
1 	7 	2015-08-02
2 	11 	2015-08-03
3 	10 	2015-08-04
4 	10 	2015-08-05
````

I also tried downgrading pystan to 2.12.0.0 but I still get the same error.

**Comment by simonb83** [comment]
Ok, an update. I was very (stupidly) not looking at the jupyter console, and realized there was a problem with unpickling the model:

````
WARNING:pystan:dlopen(/var/folders/8t/0hdwf_0n7n73x1jjlb6g0p180000gn/T/tmpxzeuq7v1/stanfit4anon_model_35bf14a7f93814266f16b4cf48b40a5a_7237902482839548574.cpython-35m-darwin.so, 2):
Library not loaded: @rpath/./libstdc++.6.dylib
````
I did `conda install libgcc` and everything is working fine now.

Sorry and thanks.

**Comment by tle4336** [comment]
@simonb83: I got the same error as you did, and I followed your solution by installing libgcc onto my Anaconda. But now I still get the same error message;p

**Comment by bletham** [comment]
Can you try installing prophet through conda?
```
conda install -c conda-forge fbprophet
```

**Comment by tle4336** [comment]
I already did that. When I did not include the last line 'm.fit(HAN_BIKE)', the whole code still executes perfectly. I only got that error message when including this line. The whole code is the following:

`import pandas as pd
import numpy as np
from fbprophet import Prophet

datapath = "/Users/tuanle/DynamicPricing/Data/"
HAN_BIKE = pd.read_csv(datapath+"HAN-BIKE_1month_CompletedOrders.csv")
# HAN_BIKE['Log_Completed'] = np.log(HAN_BIKE['completed_orders'])
HAN_BIKE = HAN_BIKE.drop("hourr", axis=1)
HAN_BIKE['to_char'] = pd.DatetimeIndex(HAN_BIKE['to_char'])
HAN_BIKE = HAN_BIKE.rename(columns={'to_char': 'ds',
                        'completed_orders': 'y'})
m = Prophet(interval_width = 0.95)
m.fit(HAN_BIKE)`
