### ISSUE TITLE
Will  prophet work  for discontinuous  seasonal data?

### ISSUE THREAD

**Issue by saby1989** [facebookincubator/prophet#67]
we have two months(dec and jan) data for 4 years (2013-2016) we trying to predict for (dec 2017- jan 2018). It is non-continuous data which is seasonal for which we are trying to forecast using prophet.
will prophet account for this discontinuity if not please let us know how to implement.

Thanks in advance :-)

**Comment by seanjtaylor** [comment]
We always suggest you try this and see what sorts of problems ensue.  Is suspect the model will have trouble learning the yearly period from only 2 months of data, and it will cause some identification problems for the remaining parameters.

Although we almost never advocate this, one way to get around this is to interpolate your missing data before fitting.

Anyway, my advice is to try both:  fit the model with no interpolated values and with a (say) linear interpolation and see if it can pick up the seasonality.
