### ISSUE TITLE
Prophet plot 2 figures instead of 1

### ISSUE THREAD

**Issue by mitbal** [facebookincubator/prophet#69]
Hey, I do not know what's wrong with my code, but every time I invoke Prophet plotting function it's always plot 2 figures instead of just 1.

Example:
![prophet_plot](https://cloud.githubusercontent.com/assets/326048/23507109/0a3627c8-ff7e-11e6-9d8f-d91cfd5e33ea.png)

I'm running python2.7, on Ubuntu 14.04 laptop.
Thanks!

**Comment by seanjtaylor** [comment]
If you're in a Jupyter notebook environment, you should add `;` to the end of the line with the plot (or assign it to a variable).  By default the notebook will render the last line you execute.
