### ISSUE TITLE
Adding daily seasonality

### ISSUE THREAD

**Issue by wtcooper** [facebookincubator/prophet#70]
When I pass data with multiple observations per day via a date-time stamp, it appears to truncate the time and produce daily estimates only.  Is it possible to add daily seasonality (e.g. hour granularity)?  We have strong daily, weekly and yearly signals in our operations data which we would like to flag as anomalous.  

Thanks for the great tool.

**Comment by seanjtaylor** [comment]
Yes this is a feature we're adding for the 0.2 release.  You can track in #29!

**Comment by wtcooper** [comment]
Excellent thanks!
