### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by m-stanley** [facebookincubator/prophet#71]
Now there have been updates after the 0.1 release, it'd be useful if the 0.1 version had a tag so we can see exactly what repo state was pushed to CRAN and PyPI as which version numbers. Could you please [create a release](https://github.com/facebookincubator/prophet/releases/new) for 0.1 and maintain them going forward?

**Comment by seanjtaylor** [comment]
Great point @m-stanley m-stanley.  We'll get the 0.1 release tagged.

**Comment by bletham** [comment]
I marked the 0.1 release and we'll definitely keep marking them in the future.

**Comment by Jeffthro** [comment]
get 0.1
