### ISSUE TITLE
Prophet for loop crashes R

### ISSUE THREAD

**Issue by gehusi** [facebookincubator/prophet#73]
Running prophet models with 10,000 time series in a for loop causes this error:

> This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

> Error: Unable to establish connection with R session.

**Comment by seanjtaylor** [comment]
I suspect this is a memory problem.  It would be interesting profile memory usage as Prophet is run repeatedly but it's not a priority for us.  We typically will only run 100 or so forecasts on any given R process, so have never hit this issue.  A simple workaround is write a short script creates a new R process for a batch of your forecasts.
