### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'fbprophet/stan_models/linear_growth.pkl'

### ISSUE THREAD

**Issue by AlexOugh** [facebookincubator/prophet#74]
I'm just following the "Quick Start" instructions using Python API, but I'm getting this error when executing m.fit(df);

`>>> m.fit(df);
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fbprophet/forecaster.py", line 368, in fit
    model = self.get_linear_model()
  File "fbprophet/forecaster.py", line 113, in get_linear_model
    with open(model_file, 'rb') as f:
IOError: [Errno 2] No such file or directory: u'fbprophet/stan_models/linear_growth.pkl'
`

**Comment by lemonlaug** [comment]
@AlexOugh, did you install using `pip` or from source?

**Comment by AlexOugh** [comment]
I installed using pip.

**Comment by bletham** [comment]
This is the same issue as #57. 
It looks like you downloaded the source and started the python console in the `python/` directory, is that correct? Then when you `from fbprophet.forecaster import Prophet`, it is using the `fbprophet` in your current directory and not the installed package from site-packages. The .pckl files are created during install and put into site-packages, hence it is unable to find them.

At least that is how I can replicate this issue. Is that what's happening for you? If you start Python from a directory that doesn't have an `fbprophet` directory in it do you still have this issue?

**Comment by AlexOugh** [comment]
It works now as you suggested. BTW, I'm not sure if this is the right place for this, but is 'csv' file the only way to feed the input source?

**Comment by bletham** [comment]
Great!
The input source just has to be a pandas dataframe. Pandas has quite a few ways of instantiating dataframes other than csv: http://pandas.pydata.org/pandas-docs/stable/io.html

**Comment by Ffisegydd** [comment]
Extra bit of advice: make sure you don't install using `pip install -e .` when installing from source code. Drop the `-e` and use `pip install .`

**Comment by rolando** [comment]
@Ffisegydd here is a fix to build models in-place: https://github.com/facebookincubator/prophet/pull/100
