### ISSUE TITLE
Adapt plot_component to frequency

### ISSUE THREAD

**Issue by LaurentBerder** [facebookincubator/prophet#76]
I've been using monthly data, with a frequency freq="MS".
Therefore, when plotting components, I get an irrelevant weekly tend plot.

Instead of me having to drop the 3 weekly columns of the forecast data frame, they did not be generated.

**Comment by bletham** [comment]
As an immediate fix you could set `weekly.seasonality = FALSE` when you instantiate the Prophet object, but let's move the discussion of doing this automatically to #78.
