### ISSUE TITLE
Hide capacity in plot_component

### ISSUE THREAD

**Issue by LaurentBerder** [facebookincubator/prophet#77]
My initial data contains a "cap" column (as many values as "y" column, which is great for the plot function.

But I don't expect the capacity to be plotted on the annual trend of the plot_component it's not relevant, as not to the same scale).
So far, I remove the column from the forecast data frame, but I find that a bit destructive, and I think it shouldn't be included in the plot in the first place.

**Comment by seanjtaylor** [comment]
Point taken.  I guess we can add a "plot_capacity" line as well.  We'll get that into the 0.2 release.

**Comment by LaurentBerder** [comment]
Not a specific "plot_capacity" function. I do believe the capacity belongs to the forecast plot. Just not on the components pot.

**Comment by bletham** [comment]
This feature was added in https://github.com/facebookincubator/prophet/commit/8155143af04ed35eb4d7ea6af0bd564b60ebc828, as an optional argument to both `plot` and `plot_components`.
