### ISSUE TITLE
Error in periods

### ISSUE THREAD

**Issue by ashawky84** [facebookincubator/prophet#82]
The predict function will always be a month short i.e if the last TS date is 2017-01-01 and the frequency is set to month i.e (freq= "m") and the period is set to (periods = 6) last date of forecast is  2017-06-01 while it should be 2017-07-01.

Cheers,

Ahmed Shawky

**Comment by stevenjk2012** [comment]
If freq=D,it's ok.I test TS date =2008-12-10,period=1,freq = m, it output two months;2008-12-31 and 2009-11-311

**Comment by bletham** [comment]
Thanks for pointing this out, this was a bug, fixed by https://github.com/facebookincubator/prophet/commit/1d37f7f6fe5803f041873ff09256104ca82d6511. If you install the latest from Github it should now be working:
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```
