### ISSUE TITLE
Holidays being excluded from the model

### ISSUE THREAD

**Issue by kennmyers** [facebookincubator/prophet#87]
I'm having an issue where a specific group of holidays is being excluded from my model if the lower window is greater than 0.

The specific dates I'm using are the following (basically christmas, vday, mothers day and fathers day):
```
2013-02-14 
2014-02-14
2015-02-14 
2016-02-14 
2017-02-14 
2013-05-12
2014-05-11
2015-05-10
2016-05-08
2017-05-14 
2013-06-16 
2014-06-15 
2015-06-21 
2016-06-19 
2017-06-18 
2013-12-25 
2014-12-25
2015-12-25
2016-12-25
2017-12-25 
```

If I add these with a tag 'hday' and add some other groups with tags like 'thanksgiving' and 'newyearseve' the hday columns are absent from the forecast (but only if lower bound is greater than 0, the other holidays remain regardless of their upper and lower windows).

For example, when the lower window is 0, this:

```
h = pd.read_csv('./holidays/holidays2.csv')
upper_lowers = {
    'hday':{
        'upper':0,
        'lower':0
    },
    'thanksgiving':{
        'upper':4,
        'lower':0
    },
    'newyearseve':{
        'upper':1,
        'lower':0
    },
    'other':{
        'upper':5,
        'lower':3
    }
}
holidays = pd.DataFrame({})
for col in h.columns:
    this_holiday = pd.DataFrame({
            'holiday':col,
            'ds':pd.to_datetime(h[h[col].notnull()][col]),
            'lower_window':upper_lowers[col]['lower'],
            'upper_window':upper_lowers[col]['upper']
        })
    holidays = pd.concat((holidays, this_holiday))

print('holiday tags: ', set(holidays['holiday']))
m = Prophet(holidays=holidays)
m.fit(orders_2013_2015_end[['ds', 'y']])
future = m.make_future_dataframe(periods=366)

forecast = m.predict(future)
print('forecast columns: ', forecast.columns)
```

Produces this:
```
holiday tags:  {'other', 'hday', 'thanksgiving', 'newyearseve'}
forecast columns:  Index(['ds', 't', 'trend', 'seasonal_lower', 'seasonal_upper', 'trend_lower',
       'trend_upper', 'yhat_lower', 'yhat_upper', 'other', 'other_lower',
       'other_upper', 'hday', 'hday_lower', 'hday_upper', 'newyearseve',
       'newyearseve_lower', 'newyearseve_upper', 'thanksgiving',
       'thanksgiving_lower', 'thanksgiving_upper', 'weekly', 'weekly_lower',
       'weekly_upper', 'yearly', 'yearly_lower', 'yearly_upper', 'seasonal',
       'yhat'],
      dtype='object')
```

But changing the lower window of 'hday' to 6 produces this:

```
holiday tags:  {'other', 'hday', 'thanksgiving', 'newyearseve'}
forecast columns:  Index(['ds', 't', 'trend', 'seasonal_lower', 'seasonal_upper', 'trend_lower',
       'trend_upper', 'yhat_lower', 'yhat_upper', 'other', 'other_lower',
       'other_upper', 'newyearseve', 'newyearseve_lower',
       'newyearseve_upper', 'thanksgiving', 'thanksgiving_lower',
       'thanksgiving_upper', 'weekly', 'weekly_lower', 'weekly_upper',
       'yearly', 'yearly_lower', 'yearly_upper', 'seasonal', 'yhat'],
      dtype='object')
```

I am not sure if this is a bug or just an unintended consequence of the data I'm using.

If it's useful at all, my data I'm training on uses dates between 2013-2015 and predicts on 2016 dates.

**Comment by kennmyers** [comment]
Actually I've narrowed this down further, the model is removing any holiday whose lower window is greater than the upper window. Is this a bug or a feature?

**Comment by bletham** [comment]
Sorry about that, this feature was not very well documented. The lower window should actually be a _negative_ number, so to get holiday features for the 6 days prior to the date you would set `lower_window` to -6. https://github.com/facebookincubator/prophet/commit/f89faf2c6a4acd2cd005c5fe0d5d1af39cda1207 adds some input validation to hopefully avoid running into this problem in the future. If you set -6 then things are working as expected?

**Comment by kennmyers** [comment]
Ahhh that makes sense, thanks!
