### ISSUE TITLE
Can anyone provide a .whl file?

### ISSUE THREAD

**Issue by jindongwang** [facebookincubator/prophet#89]
Hi all, I'm having trouble with installing prophet under Window 10 with python 3.5. Can anyone offer a .whl file so I don't need to compile anymore? I believe it's the fastest way to setup.
Anyway, it'd be great if FB can officially offer the .whl file. Why do we need to build...

**Comment by tommybutler** [comment]
It **_would_** be nice ;-)

**Comment by bletham** [comment]
There are some ongoing issues with Python-in-Windows which will prevent the installation from working. See #2 for some discussion. Basically there is an upstream issue with PyStan-in-Windows that prevents the Prophet model from compiling correctly, which can be tracked at https://github.com/stan-dev/pystan/issues/308.

**Comment by bash-j** [comment]
I am using Win7 64 and Python 3.5

Today I was able to install pystan using:
` conda install pystan`

I was also able to build the latest version of prophet from github. Not sure if this will work, I uploaded the compiled whl to my google drive: [link](https://drive.google.com/open?id=0BzMGAo5ScKasN1ZseUR1S2k2MTA)

**Comment by bletham** [comment]
It looks like conda-forge provides a whl. I think for now we're going to rely on that being the solution for now.
```
conda install -c conda-forge fbprophet
```

**Comment by WilliamPourmajidi** [comment]
I have windows 10, Anaconda 3, Python 3.6 and used this method to install fbprophet and worked fine! 
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>python -m pip install -U pip
Requirement already up-to-date: pip in c:\users\william\anaconda3\envs\testtime\lib\site-packages

(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>conda install -c conda-forge pystan
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\William\Anaconda3\envs\Testtime:

The following NEW packages will be INSTALLED:

    backports:                     1.0-py36_1            conda-forge
    backports.functools_lru_cache: 1.4-py36_1            conda-forge
    ca-certificates:               2017.11.5-0           conda-forge
    cycler:                        0.10.0-py36_0         conda-forge
    cython:                        0.27.3-py36_0         conda-forge
    freetype:                      2.7-vc14_1            conda-forge [vc14]
    icc_rt:                        2017.0.4-h97af966_0
    icu:                           58.2-vc14_0           conda-forge [vc14]
    intel-openmp:                  2018.0.0-hd92c6cd_8
    jpeg:                          9b-vc14_2             conda-forge [vc14]
    libpng:                        1.6.34-vc14_0         conda-forge [vc14]
    matplotlib:                    2.1.0-py36_0          conda-forge
    mkl:                           2018.0.1-h2108138_4
    numpy:                         1.13.3-py36ha320f96_0
    openssl:                       1.0.2m-vc14_0         conda-forge [vc14]
    pyparsing:                     2.2.0-py36_0          conda-forge
    pyqt:                          5.6.0-py36_4          conda-forge
    pystan:                        2.17.0.0-py36_vc14_0  conda-forge [vc14]
    python-dateutil:               2.6.1-py36_0          conda-forge
    pytz:                          2017.3-py_2           conda-forge
    qt:                            5.6.2-vc14_1          conda-forge [vc14]
    sip:                           4.18-py36_1           conda-forge
    six:                           1.11.0-py36_1         conda-forge
    tornado:                       4.5.2-py36_0          conda-forge
    zlib:                          1.2.11-vc14_0         conda-forge [vc14]

Proceed ([y]/n)? Y

ca-certificate 100% |###############################| Time: 0:00:00 934.83 kB/s
intel-openmp-2 100% |###############################| Time: 0:00:00   1.93 MB/s
mkl-2018.0.1-h 100% |###############################| Time: 0:01:38   1.66 MB/s
openssl-1.0.2m 100% |###############################| Time: 0:00:02   1.91 MB/s
zlib-1.2.11-vc 100% |###############################| Time: 0:00:02  55.40 kB/s
icu-58.2-vc14_ 100% |###############################| Time: 0:00:12   1.90 MB/s
jpeg-9b-vc14_2 100% |###############################| Time: 0:00:00   1.86 MB/s
libpng-1.6.34- 100% |###############################| Time: 0:00:00   1.56 MB/s
backports-1.0- 100% |###############################| Time: 0:00:00 908.55 kB/s
cython-0.27.3- 100% |###############################| Time: 0:00:02 983.09 kB/s
freetype-2.7-v 100% |###############################| Time: 0:00:00 771.60 kB/s
pyparsing-2.2. 100% |###############################| Time: 0:00:00   1.01 MB/s
pytz-2017.3-py 100% |###############################| Time: 0:00:00   1.20 MB/s
qt-5.6.2-vc14_ 100% |###############################| Time: 0:00:29   1.99 MB/s
sip-4.18-py36_ 100% |###############################| Time: 0:00:00 673.16 kB/s
six-1.11.0-py3 100% |###############################| Time: 0:00:00   1.80 MB/s
tornado-4.5.2- 100% |###############################| Time: 0:00:00   1.48 MB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.71 MB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:02   1.98 MB/s
python-dateuti 100% |###############################| Time: 0:00:00 706.52 kB/s
backports.func 100% |###############################| Time: 0:00:00   1.36 MB/s
matplotlib-2.1 100% |###############################| Time: 0:00:03   1.83 MB/s
pystan-2.17.0. 100% |###############################| Time: 0:00:07   1.92 MB/s

(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>
(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>conda install -c conda-forge pystan
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\William\Anaconda3\envs\Testtime:
#
pystan                    2.17.0.0            py36_vc14_0  [vc14]  conda-forge

(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>pip install fbprophet
Collecting fbprophet
  Using cached fbprophet-0.2.1.tar.gz
Requirement already satisfied: matplotlib in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from fbprophet)
Collecting pandas>=0.18.1 (from fbprophet)
  Downloading pandas-0.21.0-cp36-cp36m-win_amd64.whl (9.1MB)
    100% |████████████████████████████████| 9.1MB 991kB/s
Requirement already satisfied: pystan>=2.14 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from fbprophet)
Requirement already satisfied: numpy>=1.7.1 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: six>=1.10 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: python-dateutil>=2.0 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: pytz in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: cycler>=0.10 in c:\users\william\anaconda3\envs\testtime\lib\site-packages\cycler-0.10.0-py3.6.egg (from matplotlib->fbprophet)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from matplotlib->fbprophet)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\users\william\anaconda3\envs\testtime\lib\site-packages (from pystan>=2.14->fbprophet)
Building wheels for collected packages: fbprophet
  Running setup.py bdist_wheel for fbprophet ... done
  Stored in directory: C:\Users\William\AppData\Local\pip\Cache\wheels\e7\62\5b\94bb082348b1e1f45d3ab97a33982c5aaaefa7f2fecc1d3c89
Successfully built fbprophet
Installing collected packages: pandas, fbprophet
Successfully installed fbprophet-0.2.1 pandas-0.21.0

(C:\Users\William\Anaconda3\envs\Testtime) C:\Users\William>cd Anaconda3\envs\Testtime

**Comment by albertusfreddi** [comment]
> I am using Win7 64 and Python 3.5
> 
> Today I was able to install pystan using:
> ` conda install pystan`
> 
> I was also able to build the latest version of prophet from github. Not sure if this will work, I uploaded the compiled whl to my google drive: [link](https://drive.google.com/open?id=0BzMGAo5ScKasN1ZseUR1S2k2MTA)

sir can you provide the newest fbprophet whl file please?
