### ISSUE TITLE
Problems Installing in R  package ‘prophet’ is not available (for R version 3.3.2)

### ISSUE THREAD

**Issue by Earththing** [facebookincubator/prophet#91]
I am attempting to follow the documentation for installing in R
when I get to installing the package I get:

install.packages('prophet')
Warning in install.packages :
  package ‘prophet’ is not available (for R version 3.3.2)

I have tried a couple different CRAN mirrors.
Running R 3.3.2 on Windows 7 64bit. I looked at the CRAN page and if I am reading it correctly it should work, I see other people with questions using this version of R and have gotten to the point of having usage questions. It has been a while since I used R. What am I missing?

**Comment by alexisakov** [comment]
Having exactly the same issue with the same configuration (MRO 3.3.2 + Win7 x64).

**Comment by bletham** [comment]
Hm I wonder why it isn't finding it. Could you paste the output of these commands?
```
ap <- available.packages()
nrow(ap)
"prophet" %in% rownames(ap)
```
Also, is this in a fresh R session? One possibility if this is a resumed session might be that it is using a stale cache of CRAN from before Prophet was uploaded.

**Comment by Earththing** [comment]
That gave me the clue I needed. Apparently the version of R I just started using had an old CRAN snapshot that it uses by  default.
Here is the results of the commands and what I did to get Phrophet installed for me:

> ap <- available.packages()
> nrow(ap)
[1] 9393
> "prophet" %in% rownames(ap)
[1] FALSE

Restarting R session...

Microsoft R Open 3.3.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing(using 2 cores).

Default CRAN mirror snapshot taken on 2016-11-01.
See: https://mran.microsoft.com/.

> options(repos = c(CRAN = "https://cran.revolutionanalytics.com"))
> install.packages('prophet')
also installing the dependencies ‘assertthat’, ‘tibble’, ‘lazyeval’, ‘BH’, ‘StanHeaders’, ‘inline’, ‘gridExtra’, ‘RcppEigen’, ‘dplyr’, ‘extraDistr’, ‘rstan’, ‘tidyr’

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.3/assertthat_0.1.zip'
Content type 'application/zip' length 44885 bytes (43 KB)
downloaded 43 KB.....

Not to start using it!
Thanks again!
