### ISSUE TITLE
forecast - conflict with caret package in R

### ISSUE THREAD

**Issue by ramkrisp** [facebookincubator/prophet#94]
Hello all,

I got the following error when trying to forecast my data:
`fcst <- predict(m, future)`
`Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "character"`

It appear that this error is due to collision with the caret package. Any suggestion how to over come this conflict?

Thanks,
Rami

**Comment by bletham** [comment]
Thanks @ramkrisp . This should have recently been fixed in https://github.com/facebookincubator/prophet/commit/ecc06829704df7a8b81895842b79bd8aa660fed6. Could you install the latest version from Github and check if it is working for you?
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```
#16 #68

**Comment by ramkrisp** [comment]
Thanks @bletham, both are now working together.
